### ISSUE TITLE
make install

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#100]
There needs to be a make install in the top level folder

1. Do this after 'make'
2. There needs to be instructions on the home page on how to download and build
3. Do make install which
    a. Asks for or figures out where to put the block data
    b. Writes that folder to ~/.quickBlocks/blockScraper.toml (instructions to not remove this file)
    c. builds ethslurp.toml (for use with ethslurp)

**Comment by tjayrush** [comment]
This is literally the easiest to install piece of software I've ever seen. If we can model our install after this, I think that would be great. https://ipfs.io/docs/install/. In fact, I wouldn't mind studying this repo to see how they organize things. They absolutely know how to make things work well.

**Comment by tjayrush** [comment]
Referencing closed issue #130

**Comment by crodnun** [comment]
A bit confused with your post about ipfs.io :-(. I have prepared the basic command at cmake to allow the usage of:

> make install

When we type this command, first we build everything and then we run a predefined command TBD, probably in python to execute the installation steps.

Could you detail a bit more the final installation layout, I mean what you want to do during installation:

1) Select output directory (x)
2) Copy binaries to x/bin
3) Copy file A to Y
4) etc ,..

The make install target is in place now, but now we need to define how it should work.

**Comment by tjayrush** [comment]
Let's push this one off to 0.5.0 as I'm not sure exactly how I want to do it. I referenced the IPFS installer because it works flawlessly, and the documentation they provide on how to get their very complicated project (under the covers) to install is dead simple. I believe that if the install is not dead simple, 80% of all potential users won't use it, so this has to be top notch (as is IPFS).

**Comment by tjayrush** [comment]
Need to set $PATH or copy it into a folder that is already in $PATH.

**Comment by tjayrush** [comment]
Closing for now. Will reopen once 0.2.0 is finished. Referenced by #293.

**Comment by tjayrush** [comment]
It has to create folders (~/.quickBlocks/makeClass, grabABI, chifra, prices, configs, abi, maybe more), plus it must ask for the etherscan API key (unless we can figure out a way to do that with ethslurp better and not wait.

**Comment by tjayrush** [comment]
Reopening because it needs to be fixed before we proceed.

**Comment by tjayrush** [comment]
Closing for #309 which summarizes and cleans up this bug.
