### ISSUE TITLE
Change "seed" to "leech"

### ISSUE THREAD

**Issue by wildmolasses** [Great-Hill-Corporation/quickBlocks#1078]
Just an idea, was wondering your thoughts. In traditional p2p applications, "seeding" is an activity done by the data holder -- the person with the resource. "Leeching" is what's done by the person who has nothing.

To call the initial population of the address index "leeching" might better reflect exactly what's happening -- the user is "leeching" the index from other sources and is playing no part in generating it for herself.

**Comment by tjayrush** [comment]
It also lines up with the mode where QuickBlocks delivers full JSON data to an end user via a web-based API which I've been thinking of calling the "I, the user, acknowledge that I am a freeloading asshole."

Chifra 'leach' it is. Should I change it?

**Comment by tjayrush** [comment]
https://www.google.com/search?rlz=1C5CHFA_enUS740US740&ei=96nDXIK9Nouy5wLxspCgAw&q=define+leach&oq=define+leach&gs_l=psy-ab.3..0i67i70i249j0l3j0i10j0j0i10l2j0l2.9924.10477..10935...0.0..0.73.322.5......0....1..gws-wiz.......0i71j0i67.lwXfxRp8TgI

or


https://www.google.com/search?q=define+leech&rlz=1C5CHFA_enUS740US740&oq=define+leech&aqs=chrome..69i57j0l5.4687j1j7&sourceid=chrome&ie=UTF-8

Personally, I prefer the second one although I totally get the first one being more correct.

**Comment by tjayrush** [comment]
There is no longer any appearance of the word 'seed' anywhere in the code. Closing.
