### ISSUE TITLE
Allow for silent mode in ethprice

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#1087]
As per Ed's comment here: https://github.com/Great-Hill-Corporation/quickBlocks/issues/1085, ethprice should allow for silent mode.

**Comment by wildmolasses** [comment]
Could be seen as a child issue of "where/how to direct output, logs, and errors" (related to #1088 and our phone call yesterday)

**Comment by tjayrush** [comment]
We can use the Tx- family of labels. I put Tx-docker on this issue. This gives us a cross-link to related issues.

By the way TT- is tools, TA- is apps, TX- is cross links, TL- is libraries and then within each of those groups are the individual items.

**Comment by tjayrush** [comment]
The 'price' option to blocks and transactions used to be one by default, but it has a huge negative impact on performance because (especially for the UI) it has to load a pretty big file every time it displays the price. I turned it off, so the inciting reason for this issue is gone. Closing. The issue of pricing will come back naturally.
