### ISSUE TITLE
add git commit hash to console output

### ISSUE THREAD

**Issue by wildmolasses** [Great-Hill-Corporation/quickBlocks#1097]
Add the latest commit hash such that...

```
Powered by QBlocks (GHC-TrueBlocks 0.5.5-alpha) [a40af3a]
```

**Comment by wildmolasses** [comment]
Went [here](https://stackoverflow.com/questions/6526451/how-to-include-git-commit-number-into-a-c-executable), smashed some things around, got it to work.

**Comment by tjayrush** [comment]
Works as desired. Closing.
