### ISSUE TITLE
Things to include in a makefile

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#119]
A few things got lost in the move to cmake: linting, testing, refreshing, auto-create and building readme files.

 I fixed linting and auto-generation. I will fix refreshing as well. I'm sure I can fix the readmes target as well (by creating a different script).

Question: is there an industry standard for testing? Where should the testing folders live? How do people setup testing?

**Comment by crodnun** [comment]
Hi Thomas, there are many ways to integrate unit testing with cmake, the most widely used are CTest that is a tool that comes (it is installed with Cmake) and other alternatives are third party tools, among them there is a library called GoogleTest/GoogleMock (never used before, just know it exists). I have used a couple of times CTest only. For CTest, running a test means running an executable and seeing whether the result of that process is 0 (success) or not 0 (failure). It is also possible to scan the output of the executable for certain regular expressions to determine success or failure.

**Comment by tjayrush** [comment]
I'll look into CTest. Thakns.
