### ISSUE TITLE
Can we use variables for project name?

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#122]
In some of the CMakeLists.txt files, after defining the PROJECT_NAME, we don't use it further down the CMakeLists.txt file. It would be easier to use copies of the CMakeLists.txt files in a new project/folder if I only had to make one edit in each new project.

For example, here:

https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/tools/ethName/CMakeLists.txt#L22

Is there a reason why this isn't: set(TOOL_NAME "${PROJECT_NAME}")?

**Comment by tjayrush** [comment]
For example, here:

https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/tools/ethName/CMakeLists.txt#L23

**Comment by tjayrush** [comment]
Please just answer here, and I will make the change if applicable.

**Comment by crodnun** [comment]
I think that it is no longer required to use project() directive everywhere, we should defie it once o top CMakefile with the name of the project and nowhere else. It does not make sense if you want to treat all now under the same project, my fault.

**Comment by tjayrush** [comment]
I'm confused by your answer here. I think I do want different projects for each folder. Are you saying it should be otherwise?

**Comment by crodnun** [comment]
OK, understood now. Apologies I though that you wanted a different thing there. The variable PROJECT_NAME holds the latest call to project() directive, so yes, you can use it inside current CmakeFileLists.txt (its scope is:  This is the name given to the most recent project() command)

**Comment by tjayrush** [comment]
Got it. Thanks.
