### ISSUE TITLE
What is the scope of defined variables in the CMakeLists.txt files?

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#124]
Clearly, variables defined in a parent folder's CMakeLists.txt files carry over into the children folders. 

My question is, do the variables carry over to 'sisters' or 'parents' of the folder in which the variable is first defined?

**Comment by crodnun** [comment]
They are inherited by included/children directories if you define them before the directive include_subdirectory().

Here you have a link to the set() directive
https://cmake.org/cmake/help/v3.0/command/set.html

If you want to work with cmake help, this is also a good reference where you can find what each directive does

https://cmake.org/documentation/

You can check/search directives and read their documentation there, honestly it is what I do when I have doubts or not sure ,lol

**Comment by tjayrush** [comment]
Got it. Thanks. Closed.
