### ISSUE TITLE
We should have a 'make install' command to install headers and libraries into the proper place

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#130]
I want to do what a 'standard' linux distribution would do. Are you aware of what people do when they are distributing libraries and applications?

Do they build some sort of installer?

Does the installer copy the header files and .a files into a /usr/local or somewhere?

I imagine the installer must have some sort of 'uninstall' option.

**Comment by tjayrush** [comment]
Is it good practice to have the ./libs/include folder in the ./libs folder or should it ship the headers to some system folder such as /usr/local/include.

Also--should the .a files be .so files and should they be posted to /usr/local/libs?

**Comment by crodnun** [comment]
Yes, we have not added yet a target to make install, this should be do running "make install", is the way that software distribution works, running this after running "make" it deploys your headers and libraries inside the system, you need to this with sudo. cmake provides the install directive for the same.
Another important variable that controls installations at cmake is CMAKE_INSTALL_PREFIX, you define with it where you want to create the include and libs structure for your project, normally under /usr

**Comment by tjayrush** [comment]
It should also do two other things:
1. Copy any binaries to the proper location and install a path in the end user's configuration
2. Build the default home folder ~/.quickBlocks with a few known files and folders in it.
