### ISSUE TITLE
Is 'warnings' setting set a maximum level?

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#132]
If not, can we change it so it is for all builds?

If yes, is there a way to force the build to fail with even a single warning?

**Comment by tjayrush** [comment]
If not, how can I turn them on. If yes, do they cause the build to fail even on the least severe warnings? In other words--warnings are errors.

**Comment by crodnun** [comment]
To turn on all warnings and treat them as errors we need to put -Wall -Werror at the directive:
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -Wall -Werror -O2")
Like with CURL, maybe this can be a global setting, adding more options at those targets that require it

**Comment by tjayrush** [comment]
I moved all the CMAKE_CXX_FLAGS to the topmost ./src/CMakeLists.txt file. Removed from all other CMakeList.txt files
