### ISSUE TITLE
Can I make a branch private?

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#134]
Part of my code is not ready to be released, but I want certain people to be able to work on it.

Is it possible to make parts of a repo (i.e. a branch for example) private?

If not, is there a way to share 'unfinished' code to some people and not others?

**Comment by tjayrush** [comment]
Part of my code is not ready to be released, but I want certain people to work on parts of it. Can I make part of a repo (i.e. a branch) private? Of not. how can I proceed?

**Comment by crodnun** [comment]
NO at public/free repositories. On GitHub, your repository is either public or private; you cannot selectively "privatize" just a branch.

**Comment by tjayrush** [comment]
Closed
