### ISSUE TITLE
Why does each individual CMakeFiles.txt test for 'curl' code?

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#135]
Can't we put that code at a higher level of the hierarchy and allow it to be inherited?

**Comment by tjayrush** [comment]
Why does each different CMakeLists.txt file have the CURL code in it? Can't we put that code at a higher level of the hierarchy?

**Comment by tjayrush** [comment]
For example here:

https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/apps/ethprice/CMakeLists.txt#L27

and  here:

https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/apps/ethslurp/CMakeLists.txt#L27

Why not just once at the top level of ./src?

**Comment by crodnun** [comment]
Yes, now the best place to put this would be at root CMakeLists.txt. At the beginning I thought that only some tools depended on CURL but clearly now it is a project requirement. Put it at root before including the child directories and it will be inherited

**Comment by tjayrush** [comment]
Moved to top level CMakeLists.txt file.
