### ISSUE TITLE
Default branch

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#172]
I would like to make the default branch be 'develop' but when I start the process of changing the setting it warns me that it might have unintended consequences for pull requests and clones. Should I worry about that?

**Comment by crodnun** [comment]
We can move this whenever you want, make the current develop branch our new "master" and then start again from scratch. This requires really advanced commands that I can share with you. I always test them in a sandbox first but this step can be done at any moment.

**Comment by tjayrush** [comment]
We can discuss this. I want to think about what it means to have a 'default' branch. For myself, I always want the github website to open to the current 'develop' branch. For my ends users, I want them to get the most stable version if they do 'git clone http://....' Maybe we can't do both, in which case I will leave 'master' as the most stable branch and the default.

**Comment by tjayrush** [comment]
Close
