### ISSUE TITLE
Remove all test case results from 'working' folder prior to running tests

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#178]
1) The run_and_compare.py script has been renamed to testCheck.py;
2) The testCheck.py file was moved to ./src/tools/scripts so it gets built if edited;
3) I would like the testCheck.py script be able to remove the files in the 'working' folder for each test prior to running the tests. Conceptually, this means a 'rm -fR *' at the top of the current folder before each set of tests. Perhaps there could be a function called 'cleanTheFolder' that gets called first in each CMakeLists.txt file

I want to do this because I am constantly adding and removing test cases. If I remove a test, but do not remove it from the 'working' folder, it will remain there forever (unless I remove it by hand, which I won't remember to do). In this way, the files will show up as deleted in 'git' for tests that have been removed.

An alternate would be 'make cleanTest' which would remove all files from the working folder. In fact, this second method might be easier and better because it can be used exactly when needed (as opposed to be part of the regular testing.)

**Comment by tjayrush** [comment]
run_and_compare.py has been renamed to testCheck.py

**Comment by crodnun** [comment]
Hi Thomas from my point of view, to store at github just the temporal output of the tests is a bad practice,
you can store the gold files only and keep this folder empty. I know that you like to have a mirror of everything to use your handy tool to compare files & directories recursively, but this can not last forever, a software control system must store only pieces of software, scripts, configuration files, always parts that can not be generated using other pieces, in this case to store temporal files is discouraged, these files will change a lot and always must be the same that you have at gold folder. My advice is to clean this directory.

**Comment by tjayrush** [comment]
Oh. Okay. This makes perfect sense. So I can simply do 'rm -fR' at the working folder and the entire structure will be re-built by the testing code. Thanks. This is exactly why you're worth every penny. This solves my problem and does it in a way that makes sense from a 'professional' way.  I'll keep this open, but re-assign it to myself.

**Comment by tjayrush** [comment]
Let's discuss this one today when we speak.

**Comment by tjayrush** [comment]
I removed all the .txt files from the 'working' folder as you suggested. Please confirm and if you agree, I will close this issue. I removed all the test generated files but kept the folder structure.

**Comment by crodnun** [comment]
I reviewed the working directory tree and these are the only files pending to remove:

./apps/makeClass/classDefinitions/function.txt
./libs/utillib/tomlTest/test14.toml
./libs/utillib/tomlTest/test01.toml
./libs/utillib/tomlTest/test04.toml
./libs/utillib/tomlTest/test05.toml
./libs/utillib/tomlTest/test10.toml
./libs/utillib/tomlTest/test08.toml
./libs/utillib/tomlTest/test06.toml
./libs/utillib/tomlTest/test13.toml
./libs/utillib/tomlTest/test11.toml
./libs/utillib/tomlTest/test00.toml
./libs/utillib/tomlTest/test07.toml
./libs/utillib/tomlTest/test03.toml
./libs/utillib/tomlTest/test12.toml
./libs/utillib/tomlTest/test09.toml
./libs/utillib/tomlTest/test02.toml
./libs/utillib/jsonTest/test.json
./libs/utillib/jsonTest/parity.json
./libs/utillib/jsonTest/test2.json
./libs/abilib/abiTest/test1.json
./libs/abilib/abiTest/test2.json

They are already present at gold subtree, if duplicated we should keep only the gold ones and remove them here.

**Comment by tjayrush** [comment]
I removed all these files and pushed the changes. I think the working folder now has nothing but the directory structure. Close if you wish.

**Comment by crodnun** [comment]
Hi Thomas, I pulled/updated my local repository with your latest changes but still I can find many files there:

If I run under test/working the following command:

> find . 

I obtain a long list of test files:

.
./apps
./apps/ethprice
./apps/ethprice/ethprice_when_01.txt
./apps/ethprice/ethprice_period_00.txt
./apps/ethprice/ethprice_README.txt
./apps/ethprice/ethprice_no_params.txt
./apps/ethprice/.gitignore
./apps/ethprice/ethprice_verbose_00.txt
./apps/ethprice/ethprice_at_00.txt
./apps/ethprice/ethprice_when_00.txt
./apps/ethprice/ethprice_period_invalid.txt
./apps/ethprice/ethprice_period_02.txt
./apps/ethprice/ethprice_at_invalid.txt
./apps/ethprice/ethprice_invalid_param_1.txt
./apps/ethprice/ethprice_when_invalid.txt
./apps/ethprice/ethprice_period_01.txt
./apps/ethprice/ethprice_verbose_01.txt
./apps/.gitignore
./apps/makeClass
./apps/makeClass/.gitignore
./apps/makeClass/makeClass_noparams2.txt
./apps/makeClass/classDefinitions
./apps/makeClass/classDefinitions/.gitignore
./apps/makeClass/makeClass_edit.txt
./apps/makeClass/makeClass_conflict3.txt
./apps/makeClass/makeClass_run.txt
./apps/makeClass/makeClass_conflict4.txt
./apps/makeClass/makeClass_nonexist.txt
./apps/makeClass/makeClass_list.txt
./apps/makeClass/makeClass_README.txt
./apps/makeClass/makeClass_conflict2.txt
./apps/makeClass/makeClass_run_ns.txt
./apps/makeClass/makeClass_conflict1.txt
./apps/makeClass/makeClass_clear.txt
./apps/makeClass/makeClass_noparams1.txt
./apps/grabABI
./apps/grabABI/grabABI_verbose3.txt
./apps/grabABI/grabABI_README.txt
./apps/grabABI/.gitignore
./apps/grabABI/grabABI_verbose1.txt
./apps/grabABI/grabABI_verbose2.txt
./apps/grabABI/grabABI_generation.txt
./apps/grabABI/grabABI_not_found.txt
./apps/grabABI/grabABI_verbose4.txt
./apps/grabABI/grabABI_encoding.txt
./apps/grabABI/grabABI_verbose5.txt
./apps/grabABI/grabABI_noconst.txt
./apps/grabABI/grabABI_invalid_1.txt
./.gitignore
./README.md
./tools
./tools/.gitignore
./tools/getBalance
./tools/getBalance/getBalance_README.txt
./tools/getBalance/getBalance_tip_4.txt
./tools/getBalance/.gitignore
./tools/getBalance/getBalance_from_file.txt
./tools/getBalance/getBalance_bad_block.txt
./tools/getBalance/getBalance_bad_address.txt
./tools/getBalance/getBalance_e_two_accts.txt
./tools/getBalance/getBalance_e_tip_4.txt
./tools/getBalance/getBalance_noparams.txt
./tools/getBalance/getBalance_dao_1500000.txt
./tools/getBalance/getBalance_two_accts.txt
./tools/getBalance/getBalance_e_dao_1500000.txt
./tools/getBalance/getBalance_no_address.txt
./tools/isContract
./tools/isContract/isContract_no_options_2.txt
./tools/isContract/isContract_no_opts_2.txt
./tools/isContract/isContract_no_options_4.txt
./tools/isContract/isContract_dash_d_2.txt
./tools/isContract/isContract_diff_more_2.txt
./tools/isContract/isContract_dash_dn_1.txt
./tools/isContract/isContract_multiple.txt
./tools/isContract/isContract_no_options_3.txt
./tools/isContract/isContract_verbose_1.txt
./tools/isContract/.gitignore
./tools/isContract/isContract_three_addrs.txt
./tools/isContract/isContract_from_file.txt
./tools/isContract/isContract_dash_n_2.txt
./tools/isContract/isContract_noparams.txt
./tools/isContract/isContract_no_options_1.txt
./tools/isContract/isContract_no_opts_1.txt
./tools/isContract/isContract_verbose_3.txt
./tools/isContract/isContract_seven_addrs.txt
./tools/isContract/isContract_README.txt
./tools/isContract/isContract_dash_dn_2.txt
./tools/isContract/isContract_dash_d_3.txt
./tools/isContract/isContract_dash_n_1.txt
./tools/isContract/isContract_dash_d_1.txt
./tools/isContract/isContract_no_opts_3.txt
./tools/isContract/isContract_verbose_2.txt
./tools/isContract/isContract_dash_d_4.txt
./tools/getTrans
./tools/getTrans/.gitignore
./tools/getTrans/getTrans_by_file.txt
./tools/getTrans/getTrans_bad_index3.txt
./tools/getTrans/getTrans_no_input.txt
./tools/getTrans/getTrans_bad_index2.txt
./tools/getTrans/getTrans_README.txt
./tools/getTrans/getTrans_bad_hash.txt
./tools/getTrans/getTrans_by_file_v.txt
./tools/getTrans/getTrans_three_ways.txt
./tools/getTrans/getTrans_bad_index1.txt
./tools/getTrans/getTrans_by_file_long_v.txt
./tools/ethName
./tools/ethName/ethName_name_long_show_addr_match.txt
./tools/ethName/ethName_addr_long_show_addr_no_match.txt
./tools/ethName/ethName_addr_name_show_addr_match.txt
./tools/ethName/ethName_addr_long_name_case_match_both.txt
./tools/ethName/ethName_w_source.txt
./tools/ethName/ethName_addr_show_addr_no_match.txt
./tools/ethName/ethName_missing_param_1.txt
./tools/ethName/ethName_name_long_count_no_match.txt
./tools/ethName/ethName_addr_long_case_match.txt
./tools/ethName/ethName_name_and_addr_no_match.txt
./tools/ethName/ethName_mixed_options_with_list_2.txt
./tools/ethName/ethName_name_long_show_addr_no_match.txt
./tools/ethName/ethName_addr_long_case_no_match.txt
./tools/ethName/ethName_too_many_terms.txt
./tools/ethName/ethName_missing_param_3.txt
./tools/ethName/ethName_addr_long_source_match.txt
./tools/ethName/ethName_addr_verbose_match.txt
./tools/ethName/ethName_addr_count_no_match.txt
./tools/ethName/ethName_simple_search.txt
./tools/ethName/.gitignore
./tools/ethName/ethName_missing_param_2.txt
./tools/ethName/ethName_name_count_no_match.txt
./tools/ethName/ethName_addr_name_case_match_name.txt
./tools/ethName/ethName_invalid_param_2.txt
./tools/ethName/ethName_addr_long_name_source_no_match.txt
./tools/ethName/ethName_show_version.txt
./tools/ethName/ethName_addr_long_count_no_match.txt
./tools/ethName/ethName_three_params.txt
./tools/ethName/ethName_addr_name_count_match.txt
./tools/ethName/ethName_name_long_count_match.txt
./tools/ethName/ethName_addr_long_long_show_addr_match.txt
./tools/ethName/ethName_addr_long_name_verbose_no_match.txt
./tools/ethName/ethName_no_params.txt
./tools/ethName/ethName_name_long_case_match.txt
./tools/ethName/ethName_addr_name_source_no_match.txt
./tools/ethName/ethName_addr_name_source_match.txt
./tools/ethName/ethName_all_options.txt
./tools/ethName/ethName_duplicated_option_2.txt
./tools/ethName/ethName_addr_long_name_case_no_match.txt
./tools/ethName/ethName_addr_long_name_verbose_match.txt
./tools/ethName/ethName_simple_w_space.txt
./tools/ethName/ethName_duplicated_option_1.txt
./tools/ethName/ethName_invalid_param_3.txt
./tools/ethName/ethName_addr_name_show_addr_no_match.txt
./tools/ethName/ethName_name_verbose_no_match.txt
./tools/ethName/ethName_invalid_param_7.txt
./tools/ethName/ethName_name_verbose_match.txt
./tools/ethName/ethName_addr_name_verbose_match.txt
./tools/ethName/ethName_name_show_addr_match.txt
./tools/ethName/ethName_name_and_addr_match.txt
./tools/ethName/ethName_addr_long_name_case_match_addr.txt
./tools/ethName/ethName_name_match.txt
./tools/ethName/ethName_missing_param_4.txt
./tools/ethName/ethName_addr_no_hex_number.txt
./tools/ethName/ethName_addr_long_verbose_no_match.txt
./tools/ethName/ethName_addr_long_count_match.txt
./tools/ethName/ethName_invalid_param_4.txt
./tools/ethName/ethName_name_show_addr_no_match.txt
./tools/ethName/ethName_name_long_case_no_match.txt
./tools/ethName/ethName_README.txt
./tools/ethName/ethName_invalid_param_8.txt
./tools/ethName/ethName_mixed_options_with_count_2.txt
./tools/ethName/ethName_invalid_param_1.txt
./tools/ethName/ethName_name_case_match.txt
./tools/ethName/ethName_invalid_param_10.txt
./tools/ethName/ethName_name_long_source_match.txt
./tools/ethName/ethName_addr_source_match.txt
./tools/ethName/ethName_addr_long_name_show_addr_match.txt
./tools/ethName/ethName_invalid_param_9.txt
./tools/ethName/ethName_addr_count_match.txt
./tools/ethName/ethName_addr_name_case_match_both.txt
./tools/ethName/ethName_address_no_match.txt
./tools/ethName/ethName_addr_long_name_source_match.txt
./tools/ethName/ethName_addr_case_match.txt
./tools/ethName/ethName_name_long_source_no_match.txt
./tools/ethName/ethName_name_long_verbose_no_match.txt
./tools/ethName/ethName_invalid_param_5.txt
./tools/ethName/ethName_name_long_verbose_match.txt
./tools/ethName/ethName_addr_long_name_case_match_name.txt
./tools/ethName/ethName_addr_show_addr_match.txt
./tools/ethName/ethName_addr_long_source_no_match.txt
./tools/ethName/ethName_mixed_options_with_count_1.txt
./tools/ethName/ethName_name_no_match.txt
./tools/ethName/ethName_addr_name_verbose_no_match.txt
./tools/ethName/ethName_name_source_match.txt
./tools/ethName/ethName_name_source_no_match.txt
./tools/ethName/ethName_full_addr.txt
./tools/ethName/ethName_addr_case_no_match.txt
./tools/ethName/ethName_addr_long_name_show_addr_no_match.txt
./tools/ethName/ethName_addr_long_verbose_match.txt
./tools/ethName/ethName_long_list.txt
./tools/ethName/ethName_invalid_search.txt
./tools/ethName/ethName_invalid_param_6.txt
./tools/ethName/ethName_addr_long_name_count_match.txt
./tools/ethName/ethName_name_count_match.txt
./tools/ethName/ethName_address_match.txt
./tools/ethName/ethName_addr_long_name_count_no_match.txt
./tools/ethName/ethName_addr_name_case_match_addr.txt
./tools/ethName/ethName_addr_name_count_no_match.txt
./tools/ethName/ethName_name_case_no_match.txt
./tools/ethName/ethName_list.txt
./tools/ethName/ethName_addr_name_case_no_match.txt
./tools/ethName/ethName_mixed_options_with_list_1.txt
./tools/ethName/ethName_addr_source_no_match.txt
./tools/ethName/ethName_addr_verbose_no_match.txt
./tools/getReceipt
./tools/getReceipt/.gitignore
./tools/getReceipt/getReceipt_README.txt
./tools/getTrace
./tools/getTrace/.gitignore
./tools/getTrace/getTrace_README.txt
./tools/whereBlock
./tools/whereBlock/.gitignore
./tools/whereBlock/whereBlock_README.txt
./tools/getLogs
./tools/getLogs/.gitignore
./tools/getLogs/getLogs_default.txt
./tools/getLogs/getLogs_README.txt
./tools/whenBlock
./tools/whenBlock/.gitignore
./tools/whenBlock/whenBlock_noparams.txt
./tools/whenBlock/whenBlock_02.txt
./tools/whenBlock/whenBlock_03.txt
./tools/whenBlock/whenBlock_README.txt
./.gitattributes
./libs
./libs/utillib
./libs/utillib/.gitignore
./libs/utillib/exportContext
./libs/utillib/exportContext/.gitignore
./libs/utillib/exportContext/exportContextTest_00.txt
./libs/utillib/tomlTest
./libs/utillib/tomlTest/tomlTest_test01.txt
./libs/utillib/tomlTest/tomlTest_test09.txt
./libs/utillib/tomlTest/.gitignore
./libs/utillib/tomlTest/tomlTest_test02.txt
./libs/utillib/tomlTest/tomlTest_test11.txt
./libs/utillib/tomlTest/tomlTest_test13.txt
./libs/utillib/tomlTest/tomlTest_test10.txt
./libs/utillib/tomlTest/tomlTest_test07.txt
./libs/utillib/tomlTest/tomlTest_test00.txt
./libs/utillib/tomlTest/tomlTest_test05.txt
./libs/utillib/tomlTest/tomlTest_test12.txt
./libs/utillib/tomlTest/tomlTest_test03.txt
./libs/utillib/tomlTest/tomlTest_test04.txt
./libs/utillib/tomlTest/tomlTest_test06.txt
./libs/utillib/tomlTest/tomlTest_test08.txt
./libs/utillib/tomlTest/tomlTest_test14.txt
./libs/utillib/stringTest
./libs/utillib/stringTest/stringTest_00.txt
./libs/utillib/stringTest/.gitignore
./libs/utillib/jsonTest
./libs/utillib/jsonTest/jsonTest_test02.txt
./libs/utillib/jsonTest/.gitignore
./libs/utillib/jsonTest/jsonTest_test00.txt
./libs/utillib/jsonTest/jsonTest_nothing.txt
./libs/utillib/jsonTest/jsonTest_test01.txt
./libs/utillib/colorTest
./libs/utillib/colorTest/colorTest_00.txt
./libs/utillib/colorTest/.gitignore
./libs/utillib/bigIntTest
./libs/utillib/bigIntTest/.gitignore
./libs/utillib/bigIntTest/bigIntTest_00.txt
./libs/.gitignore
./libs/etherlib
./libs/etherlib/.gitignore
./libs/etherlib/sha3
./libs/etherlib/sha3/sha3Test_01.txt
./libs/etherlib/sha3/.gitignore
./libs/etherlib/sha3/sha3Test_00.txt
./libs/etherlib/printFloat
./libs/etherlib/printFloat/.gitignore
./libs/etherlib/printFloat/printFloat_00.txt
./libs/etherlib/printFloat/printFloat_01.txt
./libs/etherlib/convert
./libs/etherlib/convert/.gitignore
./libs/etherlib/convert/convertTest_00.txt
./libs/acctlib
./libs/acctlib/.gitignore
./libs/acctlib/acctTree
./libs/acctlib/acctTree/.gitignore
./libs/acctlib/acctTree/acctTest_README.txt
./libs/acctlib/acctTree/acctTest_01.txt
./libs/abilib
./libs/abilib/abiTest
./libs/abilib/abiTest/abilibTest_03.txt
./libs/abilib/abiTest/.gitignore
./libs/abilib/abiTest/abilibTest_04.txt
./libs/abilib/abiTest/abilibTest_02.txt
./libs/abilib/abiTest/abilibTest_README.txt
./libs/abilib/abiTest/abilibTest_01.txt
./libs/abilib/.gitignore

**Comment by tjayrush** [comment]
I think you have to do 

    cd ./quickBlocks/test
    rm -fR working
 
and then 

    git pull

When I look at the remove repo it seems to have exactly the files I think it should (i.e. only the folder and the .gitignore files). This is in the ./tests/working folder.

**Comment by crodnun** [comment]
Correct, the right command to do this is the following (IMPORTANT: never do rm -RF!!!!!!!! at github unless you want to clone it from scratch).

git reset --hard origin/master

This will sync everything 

Closing now.

**Comment by tjayrush** [comment]
Right. Never do rm -fR. I understand...
