### ISSUE TITLE
Problem with testCheck.py script?

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#179]
I added a test to ./src/tools/ethName/CMakeLists.txt that demonstrates a problem with the testCheck.py script (which I renamed, by the way).

If you open ./ethName/CMakeLists.txt and remove the comment in front of the test that has the word 'broken' in front of, and then do (from ./build) cmake ../src, you will see the problem. On my Mac I get this error:

    CMake Error at tools/ethName/CMakeLists.txt:33 (run_the_test):
        run_the_test Function invoked with incorrect arguments for function named:
        run_the_test
    Call Stack (most recent call first):
        tools/ethName/CMakeLists.txt:38 (run_test)

I'm sure it has to do with the empty parameter, but I do want to be able to test the programs with no parameters. They should display the help page with an error message.

**Comment by crodnun** [comment]
Updated both CMakeLists.txt files involved to deal with optional arguments.

See files pushed today at develop branch:

       modified:  src/CMakeLists.txt
       modified:  src/tools/ethName/CMakeLists.txt

At the functions defined here, you can see how cmake allows us to pass optional parameters to functions. Just not naming them at function definition:

Example (at src/CMakeLists.txt):

function(run_the_test testPath goldPath testName testExe) # Optional argv4 with command parameters

At this function, all the named parameters are mandatory, but we can pass extra ones and retrieve them using the suitable position. To get them we need to use the following syntax:

${argvX} with X starting at 0 for the very first parameter received, in this example 4 for the first optional/not named one.

The same example you can find at src/tools/ethName/CMakeLists.txt.

You can have more parameters, but only name those that are mandatory, let the function logic to manage internally optional ones when present.

**Comment by tjayrush** [comment]
This is working and copied into all CMakeLists.txt files. I am going to close this.
