### ISSUE TITLE
Setting up an Ethereum node

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#181]
ure. I guess there's two separate steps.

Setup a t2.micro instance on AWS running Ubuntu
https://mobisoftinfotech.com/resources/mguide/launch-aws-ec2-server-set-ubuntu-16-04/

Install and run Parity
One line installer linked here: https://parity.io/parity.html

Unfortunately the above requires an AWS account and some familiarity with devOps, SSH, and the command line, and isn't quite point and click...but since the OP suggested that they're trying to run a node as a backend to their web application, they're probably going to have to do that anyway.

**Comment by tjayrush** [comment]
Another link: https://ethereum.stackexchange.com/questions/24322/how-to-install-go-ethereum-on-redhat-linux/24328#24328

Also--we might be able to use QuickNode https://quiknode.io/

**Comment by tjayrush** [comment]
https://quiknode.io/node/05d4f87d-26e0-401a-939b-dd27e93fcaad/jmiSUFXnqkrSV4T0jEautA==

**Comment by tjayrush** [comment]
Referencing #1 : At the very least, you cannot use warp, and you must have tracing = on. For 100% accuracy, you must also have pruning = archive.

**Comment by crodnun** [comment]
Hi Thomas, I have installed parity at an Ubuntu droplet I hired (with 80Gb space). If you want to give it a look I can give you access to this server as root user, let me know what is your public ssh key and I will configure it here to let you enter and check how it works. I am not familiar yet with the terminology but used to install many systems and deploy things at Linux servers (no fear at this point). It seems downloading whole Ethereum DB and something is running, if you have done this before probably you can check the same.

**Comment by tjayrush** [comment]
When I return and we speak on Friday we an look at this right away. I don't want you to have to incur costs for running the node. It will download the database. In its base install, it takes up about 20 gig, but the way I have to run it, it takes up about 500 gig. We will discuss on Friday. Good job getting this done, though. We will need it as we progress into the other test cases / tools / and apps.

**Comment by crodnun** [comment]
We have decided in latest meeting to work on the following path:

Try to setup an full ethereum node for Carlos (if this is affordable :-)), running parity and using quickblock, all this on the same server.

**Comment by tjayrush** [comment]
Agreed. Work on getting an ethereum node running, and then getting quickBlocks running against it. In the meantime, I will try to get the 'Infura' mode working (that is the http://infura.io method). Probably, in the long run, it will be too expensive to run a node on Digital Ocean, but it's worth it to find out.

**Comment by crodnun** [comment]
I have decided so far to go with this setup:

1 Droplet with 60 GB + 500 GB of additional storage.  This is around 90$/month that is affordable for me ;-).

It is slow (should require more CPU and memory) but affordable for the moment, if we reduce the space requirements in the future, we can reduce this amount, but for the moment let's work this way, it will help me a lot to understand and learn many things using directly the real blockchain.

I have done the quickblocks project setup there and also installed parity, now downloading whole blockchain with the interactive command you passed me. Excited to work with real data and integrate quickblocks with ethereum!!!.

Keep you posted here

**Comment by tjayrush** [comment]
You should be able to type `getBlock -r latest` and it should be able to tell you the latest block.

**Comment by crodnun** [comment]
I am now downloading the block 

2017-08-25 12:17:15 UTC Syncing #1866918 

Running this tool you mentioned seems to display similar information but at the same time uncovered an new issue:

carlos@ubuntu-4gb-fra1-01:~/quickblocks/bin$ getBlock -r latest
getBlock argc: 3 [1:-r] [2:latest] 
getBlock -r latest 
getLatestBlockFromCache failed: 2: File does not exist: /Volumes/Samsung_T3/scraper/fullBlocks.bin

        From client: 1865611 inCache: 0 Behind (maybe empty): 1865611


------------------------------------------------------------

It expects a file somewhere:

getLatestBlockFromCache failed: 2: File does not exist: /Volumes/Samsung_T3/scraper/fullBlocks.bin

Anyways, just FYI I will not open a bug for this because I am not testing this tool now, let's keep focused, I let you decide what to do with this. Regarding Ethereum blockchain, it continues downloading, slow but ahead!

**Comment by tjayrush** [comment]
The blockchain download will be very, very slow during certain periods. Especially between around 2,250,000 and 2,675,000. There's not much you can do about it. There was an attack on the network around October of 2016 and this is the result. One of the goals of QuickBlocks is to alleviate this problem.

The bug you found is documented here: #24

**Comment by tjayrush** [comment]
Closed in lieu of #262 until 0.2.0 is released
