### ISSUE TITLE
Building README files

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#186]
Every tool can generate its own README.md file. Currently I do this on my local repo using a shell script. I would like to add the ability to do this:

     cmake ../src
     make
     make readme

and have the build update all the readme files. Every tool has this command line option that will generate the markdown for the README to standard out. That command line option is

     toolName -th

In my script I do this:

     cd toolFolder
     toolName -th >README.md

Can we add this to the build?

**Comment by crodnun** [comment]
Added at tools/ethName/CMakeLists.txt an example of how we can do it using cmake primitives.

We can create a new target to do "make readme" as follows:

# Additional target to make the README.md
set(README_FILE "${CMAKE_CURRENT_SOURCE_DIR}/README.md")
add_custom_target(readme COMMAND ${TEST_EXE} "-th" ">" "${README_FILE}" "2>&1" DEPENDS ${TOOL_NAME})  

Using the add_custom_target() directive we can define our own targets. Important parameters:
COMMAND: The command plust arguments required
DEPENDS: Make it depend on the TOOL itself, must be first compiled before generating the doc, this way you always have the latest help.

**Comment by tjayrush** [comment]
Excellent job. This works. I posted the changes to all the CMakeLists.txt files and can now build all the README.md files for all tools and apps. Thanks.
