### ISSUE TITLE
Running arbitrary shell commands during testing

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#188]
In the folder

    ./src/tools/whenBlocks

there is a test in the CMakeLists.txt file where I want to 'cat' the contents of the two test input files into the test results file. How can I run an arbitrary shell command while testing? In my previous shell script, I used to just do

    cat file.txt file2.txt >results.txt

and then I would have a test case that simply confirmed that the test input had not changed.

The answer to this question may be 'There is no reason to do that,' in which case we can just delete the test.

**Comment by crodnun** [comment]
The best way to do this, is to generate your equivalent in python to concatenate files, a new python script will be required or maybe just a function inside the test one to do this previous step. The following code will do the concatenation of 2 input files:

***********************************************************
import shutil

destination = open("out",'wb')
shutil.copyfileobj(open("file1",'rb'), destination)
shutil.copyfileobj(open("file2",'rb'), destination)
destination.close()

****************************************************************

The following statements do the concatenantion of 2 input files (file1 & file2) into a single output file

**Comment by crodnun** [comment]
You can also use the feature that cmake has to generate on the fly commands, run a command to join both files and then create a dependency with your test. There are many choices here, better if we go directly to the real example and test it.

**Comment by tjayrush** [comment]
The ./src/apps/makeClass folder contains 'makeClass.'  This code will work without an Ethereum node, so it can be tested at any time.  Currently, none of the tests work, but as soon as we get them working, you will see that the last two generate C++ code. The need for this ability to copy and paste a file into a test case is here. The makeClass -r command is supposed to generate a .cpp file. I want to copy that file in as a test case.

**Comment by crodnun** [comment]
I have pushed to repository new CMakeLists.txt at tools/whenBlock with some pseudo-code of what should be done (also includes the function required to concatenate files at cmake level), if you can share more details of how can we obtain the files to be concatenated I can complete the same. But the basics is there, you have a function that concatenates any list of files (not in use for the moment and probably better to move to root CMakeLists.txt - I let you decide this) and then you define commands (custom_commands) that execute things, making the test depend on the command, it is executed just before the test. 
For the makeClass app, I guess that the solution should be quite similar, as far as I see you concatenate several files into one, so you should define a command to obtain the file (maybe running a different test before current) and then make the new test depend on this command.
If you can share more details of the step by step procedure for both scenarios I can do it for you and then let you learn from there. I have many doubts regarding how they work.

**Comment by tjayrush** [comment]
Thanks for this. I see exactly how this works. I will test it in whenBlock and then move it up to the ./src/CMakeLists.txt file soon.

**Comment by tjayrush** [comment]
Carlos commented: 

    # We need to generate for test 01 the input files blocks.txt and dates.txt. How?

Answer: These files are in the gold tree, and when the test cases are run, the testCheck.py program changes the present working folder to the gold folder. In this way, the test cases work (because the test case looks in the current folder.)

**Comment by tjayrush** [comment]
I tried to get this to work, but I am just not able. I'm not sure what I'm doing wrong. The file concatenation seems to work, but the way you do it is to send the resulting file into the whenBlock program as an input parameter. This is not what I was trying to do. I was trying to write the contents of the two files into the test case itself. I want to do this, so I can record (in the test cases) what the input looks like. This makes it easier to compare with the output. I tried to fix it myself, but I couldn't figure it out.

**Comment by crodnun** [comment]
Let's discuss this in our next meeting, I can not understand you goal here, when this happens a meeting and sharing screens will solve the same, no way

**Comment by crodnun** [comment]
As I mentioned we need to see together what you are trying to achieve, if you prefer to close this for the moment, just do it.

**Comment by tjayrush** [comment]
Closed. We can pick this up later if we need to.
