### ISSUE TITLE
Ubuntu compilation error -  misleading indentation

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#189]
Hi Thomas, doing the build again under Ubuntu, there is a new picky warning that is now converted into error with the new policy added at FLAGS (-Werror option). At this file we need to solve the indentation

/home/quickblocks/quickBlocks/src/libs/etherlib/transaction.cpp: In function â€˜qblocks::SFString qblocks::nextTransactionChunk_custom(const qblocks::SFString&, bool&, const void*)â€™:
/home/quickblocks/quickBlocks/src/libs/etherlib/transaction.cpp:321:17: error: this â€˜ifâ€™ clause does not guard... [-Werror=misleading-indentation]
                 if ( fieldIn % "contractAddress" ) return fromAddress(tra->receipt.contractAddress); break;
                 ^~
/home/quickblocks/quickBlocks/src/libs/etherlib/transaction.cpp:321:102: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the â€˜ifâ€™
                 if ( fieldIn % "contractAddress" ) return fromAddress(tra->receipt.contractAddress); break;

It is fixed just converting it into:

if ( fieldIn % "contractAddress" )
                {
                    return fromAddress(tra->receipt.contractAddress);
                }
                break;

I did not modify it just to let you do the same, I do not know in which parts are you working now so I let you fix it opening this issue.

**Comment by tjayrush** [comment]
Every time I push a change to the remote repo, I log into my Ubuntu box and do a pull. And then rebuild the entire thing. I don't get the same warnings, so let's make the first thing we do is figure out why you get warnings but I don't. There must be some setting on your machine that is not on my machine.

**Comment by tjayrush** [comment]
Are you using a linter or something?

**Comment by crodnun** [comment]
I always try to use the latest Ubuntu version available.

I am using now:

1) Ubuntu 17.04
2) gcc compilier 6.3.0

I think that this is the most relevant information of my Ubuntu droplet. Probably only the compiler could be the root cause of the warnings that I obtain and you  don't. From my point of view we should be compatible with everybody so it is nice to detect issues with modern compilers or newest versions. We can say that it has been tested with Ubuntu A, B, C, ..... (that is nice for the community).

**Comment by crodnun** [comment]
Confirmed, it is a new feature added at newest version of gcc compilers (6.X), and the reason you could not detect if before in your Ubuntu machine, probably you have an older version where this warning was not generated. 

You can read a bit more here, this link describes a few features that were added at GCC 6.X.

https://gcc.gnu.org/gcc-6/porting_to.html

So now onwards we should support the latest version of GCC compiler too.

**Comment by tjayrush** [comment]
I will upgrade my Ubuntu to the latest version.

**Comment by tjayrush** [comment]
We can talk about this one today. I think I want you to help me setup a new Digital Ocean account using latest Ubuntu.

**Comment by tjayrush** [comment]
Fixed
