### ISSUE TITLE
Warning to be fixed. When running make, compilation stops at this point

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#191]
[ 65%] Building CXX object test-libs/etherlib/convert/CMakeFiles/convert.dir/convert.cpp.o
/root/workspace/src/test-libs/etherlib/convert/convert.cpp: In function â€˜int main(int, const char**)â€™:
/root/workspace/src/test-libs/etherlib/convert/convert.cpp:19:19: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
     for (int i=0;i<nAddrs;i++) {
                   ^

**Comment by tjayrush** [comment]
At some point, I would like to learn how to work with 'pull requests.' Do pull requests only work if you (Carlos) have done a fork? Maybe we can discuss tomorrow.

When something like this happens, do you simply fix it on your end?

By the way -- every time I post something from my Mac (with git push), I log into my Ubuntu and compile. (Or at least I try.) I must have forgotten to do this with the convert test. Sorry.

**Comment by tjayrush** [comment]
Closed as a dup of #189
