### ISSUE TITLE
More warnings pending at test-libs

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#192]
Using latest pull downloaded today, still I am not able to build it completely with steps: cmake + make

Pending this minor warning yet:

[ 65%] Building CXX object test-libs/etherlib/convert/CMakeFiles/convert.dir/convert.cpp.o
/home/quickblocks/quickBlocks/src/test-libs/etherlib/convert/convert.cpp: In function â€˜int main(int, const char**)â€™:
/home/quickblocks/quickBlocks/src/test-libs/etherlib/convert/convert.cpp:19:19: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
     for (int i=0;i<nAddrs;i++) {

**Comment by tjayrush** [comment]
The first thing we do when we speak tomorrow (Weds. August 9, 9:30 am my time) is have you help me setup a new Digital Ocean droplet for the latest version of Ubuntu. That way, whenever I push, I can login to Ubuntu and build to make sure to avoid these errors.

**Comment by tjayrush** [comment]
Closed as a dup of #189.
