### ISSUE TITLE
Need a way to document the libraries

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#194]
We've discussed documenting the source code for the libraries using doxygen. For all the 'apps' and 'tools' I am satisfied with the documentation produced in the README.md files. For the libraries (utillib, abilib, etherlib, but not acctlib, tokenlib or walletlib) I want to start thinking about how to document. Utillib will be changing significantly once it is safely surrounded with test cases, so I think we can start with the 'abilib' which is small and a good starting point.

I would like to be able to build all the documentation with a single command similar to 'make readme' but perhaps called 'make docs'.  Make docs would populate the ./quickBlocks/docs folder with whatever it needed to be a full documentation of the system (i.e. documents for the libraries, the apps and the tools.

All of the tools produce their own README.md files. The folders that do not have their own tool (i.e. ./src, ./src/apps/, ./src/tools, etc. do have their own README.md file, so 'make docs' would have to account for those files as well.

**Comment by crodnun** [comment]
As we discussed the only multiplatform tool that I know is doxygen (it runs on MAC, Windows and Linux), but probably there will be many nowadays. I have used doxygen to generate PDF, HTML and CHTML documentation, it supports also LATeX.

I let you here some links to projects done with Doxygen (online ones, not mine):

http://dtris.sourceforge.net/doxygen/html/index.html

http://www.dre.vanderbilt.edu/Doxygen/

https://www.abisource.com/doxygen/

http://www.icu-project.org/apiref/icu4c/

**Comment by tjayrush** [comment]
I am going to keep this open, but put it on the back-burner. I will re-assign to myself.

**Comment by tjayrush** [comment]
Delay this one until 0.5.0. Referencing issue #293

**Comment by tjayrush** [comment]
We are not going to document the libraries. We are going to re-write them in Rust and then use cargo to document the Rust libraries.
