### ISSUE TITLE
Question about push vs. pull request

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#198]
Just a simple question: Does a push from a developer who does not have permission to change the repo become a 'pull request from my perspective? 

So, from his/her perspective they are 'pushing', from my perspective they are asking me (requesting me) to pull. Is that what a pull request is?

**Comment by crodnun** [comment]
Hi Thomas, a push always updates the repository everybody shares online (at the branch where the push is done).  Nobody can never push your codes, every developer works always against the public/private repository shared online. When you pull, you update your local repository with the changes that other developer pushed online, when you push: you make your changes available for them, but there is always an intermediate between you an me, I can not get any changes from your side without being pushed firstly /by you) and public. Find attached and screenshot of the repositories involved at git
![git_repositories_and_commands](https://user-images.githubusercontent.com/16229970/29118962-82922bbe-7d04-11e7-9143-b1d0b72edcf8.png)

**Comment by tjayrush** [comment]
I understand this completely. Here's my question: what is a pull request? I think it's a request by another developer asking me (the main owner of the repo) to pull a change that he/she has previously pushed. Is that right?

Excellent chart. I put this on on my desktop too!

**Comment by tjayrush** [comment]
Closed
