### ISSUE TITLE
Bug at ethName

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#203]
When I run the tool with the option -c it seems to have a bug:

When matchs are available, it prints the whole database entry instead printing the count:

quickblocks@ubuntu-1gb-lon1-01:~/quickBlocks/bin$ ./ethName -c  0x17 rob 
{ "addr": "0x1736303b570247313eb445d803185455779b91c7", "name": "@robrigo", "source": "Steem" }

When no match available. prints nothing

quickblocks@ubuntu-1gb-lon1-01:~/quickBlocks/bin$ ./ethName -c  0x01 rob 

Seems that this option is not enabled yet or is buggy

**Comment by tjayrush** [comment]
This is now fixed.

**Comment by crodnun** [comment]
Tested by Carlos and works as intended now
