### ISSUE TITLE
Strange behaviour at ethName passing -t option

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#204]
When we run:

./ethName -t 

Nothing is displayed, is it a valid command?, is it an error?

**Comment by tjayrush** [comment]
-t is an invalid command (unless it's used with -th which is an undocumented way to generate the README.md files. Please confirm and close this.

**Comment by crodnun** [comment]
OK, now we report correctly that it is an invalid command:

~/quickBlocks/bin$ ./ethName -t

Invalid option: -t

  Usage:    ethName [-a|-c|-e|-l|-m|-s|-v|-h] term [name]  
  Purpose:  Find a name given an Ethereum address, or find an address given a name.
