### ISSUE TITLE
Running ethName with more than 2 terms (address + name + other)

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#205]
Running the following command:

./ethName -c  0x17 rob other

It does not error out or shows an output. Is the third parameter considered at search, if so we should indicate the same at help (as a user I understand that only 2 terms can be passed).
If it is an error or this invocation is not supported we should error out here a message to inform user that is not correct.

**Comment by tjayrush** [comment]
I think this test should work as it does. The third parameter (if present) is the 'source', but I made an engineering decision to not document this feature as I felt it would unnessarily complicate the help message. Nice catch, but I am going to close this.
