### ISSUE TITLE
Verbose option at ethName tool seems not operative

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#206]
When I run:

./ethName -v0 rob      (as described in usage message)

It errors out:

quickblocks@ubuntu-1gb-lon1-01:~/quickBlocks/bin$ ./ethName -v0 rob

  Invalid option: -0

Here we need to do:

1) First fix the option or the help
2) Improve the usage message to display the exact syntax and the values for level (range supported)

**Comment by tjayrush** [comment]
The -v option should be either simply -v or --verbose or -v:n where n is greater than zero. I think this one just needs to be better described in the help text.

**Comment by tjayrush** [comment]
I improved the help text for the --verbose option. It's not perfect, but I think we can close this. If a user finds it to be inadequate, they are welcome to write a pull request at a later date. You may close this bug.

**Comment by crodnun** [comment]
OK closed following your request, still not satisfied (as a final user) but let's focus for the moment on the important stuff
