### ISSUE TITLE
Mixing options at ethName

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#207]
Some of the options at ethName are incompatible,

e.g. we can not mix -c with -s or with -l/-e, this should be checked by the program to force the user to use only the suitable ones.

Right now you can invoke the tool passing all them at the same time and the behaviour is not clear, it is difficult to appreciate what is the option really applied.

We can run this:

./ethName -a -m -v -c -s 0x17 rob

or this

./ethName -a -m -v -c -e -l  0x17 rob

or many other combinations, we should check this and do not allow these combinations.

**Comment by tjayrush** [comment]
Just to document how it works:

The edit option always predominates. If it's present, it will open the file and quit when the user saves changes or quits.

-l or --list always premoniates as well. If present the tool will always list all entries.

-c or --count will work with other command and will simply print the number of matches (or the number of items in the list) if present, or '0' if there are no matches.

-m or --matchCase simply changes the way the matching works and will work with all other options.

-a changes the output of the results and should work with any other option.

I actually think it works as designed.

Very nice test, though. But I think we can close this. Also--if the user does this crazy command, they kind of deserve what they get.

**Comment by crodnun** [comment]
OK, as as user I miss all this information you put here. If you want to hide all this information, it works as expected, if you want to help users maybe a couple of lines telling them this will be welcome :-), up to you, let me know if this is your goal and we can close it, I do not pretend to be picky here, just think as a final user and have all the help available for this command.

**Comment by tjayrush** [comment]
I updated the README.md file and the docs/README.tmpl.md file. This may be close, I think, with my next push.

**Comment by tjayrush** [comment]
Major confusion here on my part. The note above is about 'ethprice.' So the text above was copied into the 'ethprice' help file (where it belonged). That tool's README file is improved. I will not open and close a bug for that. For this bug, please close this one, and open another one by copying in the original text and I will answer it based on 'ethName' not 'ethprice' as I did above. Hope that's clear.

**Comment by crodnun** [comment]
OK closing it as requested
