### ISSUE TITLE
Not passing a search criteria to ethName

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#208]
When we run the ethName tool with options but no search criteria (no name, neither address) it does not display any error, seems to use as search key an empty string, but nothing is displayed on screen:

./ethName -m
(nothing)

./ethName -a
(nothing)

./ethName -v
Address '' not found

./ethName -s
(nothing)

We should control this or document the usage in no params can be supplied here.

**Comment by tjayrush** [comment]
Please add these as test cases. This should generate an error.

**Comment by crodnun** [comment]
Added test cases for the same:
run_test("ethName_missing_param_1" "-m")
run_test("ethName_missing_param_2" "-a")
run_test("ethName_missing_param_3" "-v")
run_test("ethName_missing_param_4" "-s")

bug is pending to be fixed by Thomas

**Comment by tjayrush** [comment]
This should be fixed with my next push which I will do before we speak.
