### ISSUE TITLE
Bug at ethprice when passing an unexpected option (-x in this case)

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#209]
./ethprice -x
Data not written because no new data, or no -freshen flag. 2015-01-01 00:00:00 UTC : 0 records

  Usage:    ethprice [-a|-c|-f|-p|-w|-o|-t|-v|-h]  
  Purpose:  Freshen and/or print price quotes for the Ethereum network.

I expected here to show an error "unsupported/unexpected option" but seems to start and then displays the help.

It can be tested passing any option not supported (e.g. -x -w .... ) without more options

**Comment by tjayrush** [comment]
This should be fixed with the next push. Closing.
