### ISSUE TITLE
Question regarding ethprice app setup for testing

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#211]
Do I need any previous setup to test this app?

When I run some tests, is mentions this file that is not present at my machine:

Could not open cache file for writing: '/home/quickblocks/.quickBlocks/prices/poloniex.bin'

**Comment by tjayrush** [comment]
If that file does not exist, it should be created, so this is a bug.

**Comment by crodnun** [comment]
Yes clearly this tool seems buggy, it most of the times displays this message:

Could not open cache file for writing: '/home/quickblocks/.quickBlocks/prices/poloniex.bin'

**Comment by tjayrush** [comment]
I changed this so it should now tell you that you must run with --freshen first or it won't work.

**Comment by crodnun** [comment]
Reviewed, but the error is still displayed when passing the freshen option:

Running this:

$ ./ethprice --freshen

  Could not open cache file for writing: '/home/quickblocks/.quickBlocks/prices/poloniex.bin'

Running this:

$ ./ethprice --freshen -a:1498032000

  Could not open cache file for writing: '/home/quickblocks/.quickBlocks/prices/poloniex.bin'

The file seems not present, neither the directory:

ls -l /home/quickblocks/.quickBlocks/
total 4
drwxr-xr-x 2 quickblocks quickblocks 4096 Aug 10 15:01 configs

To be reviewed.

**Comment by tjayrush** [comment]
The problem is the that if the director doesn't exist, it fails.

**Comment by tjayrush** [comment]
I think this should now be fixed. On first run, the folder ~/.quickBlocks/prices is created if not already exist. Plus the file ~/.quickBlocks/prices/polonies.bin is either freshened (if present already) or created from scratch if not present. The folder should be created for any option given to the tool, but not all options will work before the first --freshen.

This brings up an issue that somewhere during testing, you need to make sure the system that is being tested does not have existing folders under ~/.quickBlocks.

Reassigning to you. If you want to create a new issue for the 'clear the ~/.quickBlocks folder before testing' issue, I will leave that to you.

**Comment by crodnun** [comment]
Closing for the moment, we can open a new issue when testing this tool in depth. For now the original bug seems solved.
