### ISSUE TITLE
The general option --version seems not operative

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#212]
All the tools and app tested so far show at help that they support the --version option, but it seems not operative.

./ethName --version

(nothing is displayed here)

Seems to be a common issue present at every tool/app

**Comment by tjayrush** [comment]
--version is not operative anywhere.

**Comment by tjayrush** [comment]
This is now fixed. Not sure if I should reassign this and let you close it, it simply close it myself. Please advise.

**Comment by crodnun** [comment]
Yes, the best workflow for this is to reassign this to the tester that generates the bug, in this case "me" :-).
Once tested again, the person that should close a bug is the person that opened it.

Added a new test case for this.

Now it works, closed bug
