### ISSUE TITLE
Some tools and options depend on nano editor, this should be a pre-requisite

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#213]
When we invoke commands or tools we edit some files launching the nano editor.

Example:

./ethName -e

Looking at codes we have these statements:

./src/apps/ethslurp/options.cpp:                SFString cmd = "nano -I " + configPath("quickBlocks.toml");
./src/tools/ethName/options.cpp:            SFString command = ("nano -I " + configPath("configs/names.conf"));

If this editor must be installed before using the codes, it should be a pre-requisite, otherwise we can find scenarios where users have not this editor available.

No problem using it everywhere, even for windows they have a downloadable version but clearly we must ensure that is installed first when running cmake ../src

**Comment by tjayrush** [comment]
I am open to any other suggestions for editors. I only picked nano out of a lack of knowledge for other editors. Do you have any suggestions?

**Comment by tjayrush** [comment]
Please suggest an editor other than 'nano,' or, if 'nano' is okay, then please add it to the build if you know how. Reassigning this to you.

**Comment by crodnun** [comment]
I added and pushed the nano dependency at root CMakeLists.txt file.

Now the "cmake ../src" command should look like this 

1) For nano present scenarios:

-- ======== LOOKING FOR PYTHON ========================
-- Found PythonInterp: /usr/bin/python (found version "2.7.13") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "2.7.13") 
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.52.1") 
-- ======== LOOKING FOR nano  ========================
-- Found nano: /bin/nano

2) For those scenarios where nano is not installed or missing:

-- ======== LOOKING FOR nano  ========================
CMake Error at CMakeLists.txt:43 (message):
  Unable to find nano in PATH


The statements added to root CMakeFile are the following:

# ----------------------------------------------------------------------------------------
# We require the nano editor available
# We define a generic variable called DEFAULT_EDITOR to assign maybe other editors in the future
# If not found cmake will fail
set(DEFAULT_EDITOR "nano")
message (STATUS "======== LOOKING FOR ${DEFAULT_EDITOR}  ========================")
find_program(DEFAULT_EDITOR_PATH nano)
if (NOT DEFAULT_EDITOR_PATH)
        message (FATAL_ERROR  "Unable to find ${DEFAULT_EDITOR} in PATH")
else ()
        message (STATUS "Found ${DEFAULT_EDITOR}: ${DEFAULT_EDITOR_PATH}")
endif (NOT DEFAULT_EDITOR_PATH)



Let's double check it at your side and close, you should do it now because I was the developer that did the changes.

**Comment by tjayrush** [comment]
It appears to be working, but then, I have 'nano' on my machine. I can see the message saying it's looking for it.

I am going to close this. If an end-user finds that it doesn't work, someone can later write an issue. Thanks.
