### ISSUE TITLE
ethprice app does not reject unexpected args

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#214]
Running:

./ethprice -x

It displays 

Data not written because no new data, or no -freshen flag. 2015-01-01 00:00:00 UTC : 0 records

  Usage:    ethprice [-a|-c|-f|-p|-w|-o|-t|-v|-h]  
  Purpose:  Freshen and/or print price quotes for the Ethereum network.
             
  Where:    
        -a  (or --at)         Report the price since nearest five minutes to :timestamp
        -c  (or --clear)      Clear the database and re-download price data
        -f  (or --freshen)    Freshen database even if not needed
        -p  (or --period)     Time increment for display. Default 120 mins or :t where t is in [5|15|30|120|240|1440]
        -w  (or --when)       Time of day to start the display. :h determines the hour to start
        -o  (or --output)     Output level (default 1). :2 exposes more data per record
        -t  (or --test)       generate intermediary files but do not execute the commands
        -v  (or --verbose)    set verbose level. Follow with a number to set level (-v0 for silent)
        -h  (or --help)       display this help screen

  Powered, in part, by the Poloniex APIs
  Powered by QuickBlocks

-----------------------------------------------------------------------------------------
COMMENT: Seems that it ignores the option supplied and starts running

**Comment by tjayrush** [comment]
This will be fixed with the next push.
