### ISSUE TITLE
ethprice usage should be improved

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#215]
Usage:    ethprice [-a|-c|-f|-p|-w|-o|-t|-v|-h]  

Seems that it says that parameters are optional and you can use it without arguments that is not true. We at least require one of them

**Comment by tjayrush** [comment]
Please explain how it should look to indicate that at least one option is required.

**Comment by crodnun** [comment]
I am used to deal with optional parameters between brackets [a|b|c|d] and exclusive with "|". Maybe just removing the brackets could be enough to indicate that one is mandatory but all them are mutually exclusive:

What about something like this:

ethprice -a|-c|-f|-p|-w|-o|-t|-v|-h

No optional parameters and mutually exclusive.

**Comment by tjayrush** [comment]
I changed the help to indicate that at least one option is needed as you suggest. This will be fixed with my latest push and can be closed.

**Comment by crodnun** [comment]
Tested and closing it
