### ISSUE TITLE
Command ./grabABI -t seems overlapped with other options

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#218]
When we run the previous command, it errors out but at the same time displays formatted output, seems to do both things.

------------------------------------------------

#### Usage

  Please supply at least one Ethereum address.

`Usage:`    grabABI [-c|-g|-e|-n|-o|-s|-t|-v|-h] addr  
`Purpose:`  Fetches the ABI for a smart contract. Optionally generates C++ source code representing that ABI.
             
`Where:`  

| Option | Full Command | Description |
| -------: | :------- | :------- |
|  | addr | the address(es) of the smart contract(s) to grab |
| -c | --canonical | convert all types to their canonical represenation and remove all spaces from display |
| -g | --generate | generate C++ code into ':dir' for all functions and events found in the ABI |
| -e | --encode | generate the encodings for the functions / events in the ABI |
| -n | --noconst | generate encodings for non-constant functions and events only (always true when generating) |
| -o | --open | open the ABI file for editing, download if not already present |
| -s | --silent | If ABI cannot be acquired, fail silently (useful for scripting) |
| -t | --test | generate intermediary files but do not execute the commands |
| -v | --verbose | set verbose level. Follow with a number to set level (-v0 for silent) |
| -h | --help | display this help screen |

##### Other Options

Enter `--version` to display the current version of the tool.  
Enter `--nocolors` to turn off colored display.  
Enter `--wei` (default), `--ether`, or `--dollars` to alter the way value is displayed.  

All `quickBlocks` command-line tools support the `--file:filename` option. Place valid commands, on separate lines, in a file and include the above option. In some cases, this option may significantly improve performance. Place a semi-colon at the start of a line to make it a comment.

#### Powered by QuickBlocks&reg;

------------------------------------------------------------------

**Comment by tjayrush** [comment]
The intention of the -t option, when present, is that it runs through the command, but does not write any real data or change any 'state.' It's intended to aid testing. Perhaps it doesn't always work, in which case we should either fix it or remove it.

If it's working properly, you should be able to take any command and run it with the -t option to no effect (except any data or files are unchanged.) This applies to all tools and apps.

I'm not sure if I should re-assign this or not.

**Comment by crodnun** [comment]
Ok, we can close this for now. I understood now how it works and it should not be considered a bug, just incomplete instructions

**Comment by tjayrush** [comment]
I wrote this issue #238. I think I will remove the --test command from the help display, but leave it as a 'hidden' option. We can use --test ourselves for testing, but I won't expose it to the end user.
