### ISSUE TITLE
Strange output when running grabABI with "-o" option

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#219]
./grabABI -o 0x1728039ce0d18a799c081c5c7fa2090dd365a8d0
open: invalid option -- 'a'

I expected to do this (or at least to run something):

-o  (or --open)       open the ABI file for editing, download if not already present

**Comment by tjayrush** [comment]
I changed the error message so it now says:

    ABI for '0x1728039ce0d18a799c081c5c7fa2090dd365a8d0' not found. Quitting...

This can be closed.

**Comment by crodnun** [comment]
Still not satisfied, the error is OK but it is necessary to display the help here?

**Comment by tjayrush** [comment]
I removed the help text and added a test case to ./src/apps/grabABI/CMakeLists.txt to cover.

**Comment by crodnun** [comment]
Tested again and closed
