### ISSUE TITLE
Usage of ethprice should be improved, many doubts here as user

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#220]
I detail below the options that I do not understand as final user:
        
        -a  (or --at)         Report the price since nearest five minutes to :timestamp

         DOUBTS: 

         What is the format of this option? What is the format of the timestamp passed?

        -p  (or --period)     Time increment for display. Default 120 mins or :t where t is in [5|15|30|120|240|1440]

         DOUBT:

         Again the same doubt, what is the expected format and how we pass a value here?

        -w  (or --when)       Time of day to start the display. :h determines the hour to start

        DOUBT: 

        How to pass the hour and its supported  format?

        -o  (or --output)     Output level (default 1). :2 exposes more data per record
   
        DOUBT: 

        How to pass the level? and its supported  format? Range of values (only 1 and 2)?

**Comment by tjayrush** [comment]
In all cases you send the option plus ':' plus the value. So for `--at` a valid value would be `--at:42412312312` with a linux timestamp. `--period:120` and so forth.

For all the tools, when I send a value that follows a parameter, I use --option:value with a colon separator. it's not very 'linux' way of doing it, but it's how it works for now.

**Comment by crodnun** [comment]
OK, then again, being a picky user we should detail this a bit more at help, otherwise the user could get confused like happened to me. If you consider  that this is too picky, let me know and I will close it. You requested me to test as a final user, not as a colleague ;-)

**Comment by tjayrush** [comment]
Please close this bug. It's delayed until 0.5.0 release, and it's recorded in #293. I will re-open it once we're done with 0.2.0

**Comment by crodnun** [comment]
Delayed till next milestone

**Comment by tjayrush** [comment]
Close in lieu of eventual total overhaul of command line arguments.
