### ISSUE TITLE
ethName option -s should hit on source where the same search with source won't

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#224]
This test:

    ethName -s GHC

should hit, whereas this one should not

    ethName GHC

The -s option searches the additional field 'source' which is not searched by default. Please add a test (or more). I modified the _source_ test cases to reflect this. Please confirm that they work as you would expect.

**Comment by crodnun** [comment]
Still not clear the behaviour of this command.

It is an additional filter? when supplied we do the search of the input fields in the address, name or source.

Normally we do the search at address or name, if supplied this option we do the search also at source (using the input keys passed)?

**Comment by tjayrush** [comment]
If -s is supplied it search 'name' and 'address' as it did before, but it will also match on source if the search term is found in source. In other words -s will search (and match) in all three 'name,' 'addr,' and 'source.' Without -s, it only searches 'name' and 'addr.'

**Comment by crodnun** [comment]
OK reviewed, what about using a multiple-word key. e. g.

./ethName  -s "Ether Camp"
(no entry found - empty output) ??? Is this supported or just the tricky tester breaking everything? ;-)

It matches the single word search  whenusing any of the previous fields but not the multiple word string:

./ethName  -s "Ether"

xxxxxxxxxxxxxxxxxxxxx  (here we obtain results)

./ethName  -s "Camp"

xxxxxxxxxxxxxxxxxxxxxx (here we obtain results too)

but not with multiple words string. Let me know if this is required or we can close this issue for the moment.

We have many entries with this source value:

{ "addr": "0xfe24cdd8648121a43a7c86d289be4dd2951ed49f", "name": "DAO_id273_cnt417_2mo", "source": "Ether Camp" }
{ "addr": "0xfe9ccd888dfcda8910fb47f492193664ca0ab237", "name": "FailGuyTax_id113_cnt127_5mo", "source": "Ether Camp" }
{ "addr": "0xfeeb8a968f0d7fd58e29fbfc525051f50ee2fedc", "name": "Etheramid2_id175_cnt228_4mo", "source": "Ether Camp" }

**Comment by tjayrush** [comment]
You're a great tester. I'll fix this one.

**Comment by tjayrush** [comment]
Closing for now. Will reopen once 0.2.0 is finished. Referenced by #293.

**Comment by tjayrush** [comment]
Closing. Not really fixed, but not going to fix either.
