### ISSUE TITLE
Procedure for adding gold test cases

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#225]
I think this is how we should make test cases 'gold.'

    1) You write the test. It will fail because there is no 'gold' code.
    2) You can determine if the test case is working as you would expect, and if it is, make it gold by copying the test case from 'working' to 'gold.'
    3) If the test case is not working, do not copy the test result to gold, obviously
    4) Push your work

I will then pull you work and

     1) for new test results in the gold folder, I will confirm that they are working as I would expect them to work. If they are working correctly, I will do nothing.
     2) If a gold test case is not working as I would expect (maybe it's not clear what it should do), I will fix the code and update the gold file.
     3) If a test case has no gold, I will fix the problem and make it gold.
     4) After I add a new gold test case, you must confirm that the test case is behaving as you thought it should or understand why I changed it.

I think we have to do it this way to make sure the 'gold' tests are really gold (that is we need a way to make sure they are accurate). At the end, I want both you and I to agree that the test case is gold. You because it behaves as it seems it should given the documentation, me because I programmed it and I know how I intended it to work.

**Comment by crodnun** [comment]
OK, let's follow this procedure now onwards. Let's discuss this at today's meeting

**Comment by tjayrush** [comment]
If not this exact procedure, we should at least have some procedure.
