### ISSUE TITLE
How do I debug why changes to the CMakeFiles are not working?

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#227]
For some reason, I can't get `make readme` to work this weekend, but as far as I can tell, I didn't change anything. I spent a lot of time trying to figure out what went wrong, but I can't.

I need you to help me to understand how to debug CMake problems. I tried using 'message(STATUS...' but that is highly unproductive. Is there any way to turn on debugging messages? Is there some sort of interactive debugger?

**Comment by crodnun** [comment]
Hi Thomas, there is no interactive debugger for CMake scripts. 

You can debug an issue at two different sides:

1) At cmake side, using the message() and patience, no way. There are some options to show verbose information of the "cmake ../src" step but from my point of view they are useless, only allow you to follow the  scripts executed but no variables or information displayed there.

> cmake ../src --trace   

2) At make side, you can display what are the commands being executed at any moment with:

> make VERBOSE=1  readme  (if you want to run this target)

**Comment by tjayrush** [comment]
Thanks. I was afraid of that. I will close this.
