### ISSUE TITLE
The generation of test stuff (like names.conf) should be incorporated into cmake somehow

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#230]
To test ethName we require the presence of the file:

.quickBlocks/configs/names.conf

We should store this somewhere in the repository and copy it into the expected user's folder when we run the: make test command (using a cmake custom command). This way user always has the latest version present at HOME.

This applies also to any other file that test cases require to run:

1) We should put them at git repository

2) We should put them at the right user's directory when they run "make test". For the moment we did it manually but we can automate this with cmake and git repository. We can keep track of a kind of "gold" input/config files.

I let you decide this but maybe under:

quickBlocks/test/gold/config

would be nice place.

**Comment by tjayrush** [comment]
I totally agree with this comment, but there's a bit of a problem. One 'first run', the file does not exist. It gets created with default values ( you can see that by removing the ~/.quickBlocks/configs/names.conf file--it will be recreated). The test cases need some data to work, so if we use the default, they will all fail, therefore we need to copy in the test data.

I don't want the test data to be the data the actual user uses (each user will have their own set of names they want to take account of).

Perhaps the solution would be to build a 'better' default list of accounts to name (i.e., all the popular addresses). The trouble with this approach is that this list then becomes something that has to be kept up to date as new popular contracts become prevalent.

As I said, I totally agree with what you've written here, but the file we're currently using is not the right one to preserve in the source.

**Comment by tjayrush** [comment]
For the case of `ethPrice`, I think we can store the full price history in the source somewhere, and the first time `ethPrice` runs it should copy the .bin file into its location. The way it works now, it tells the user to run `ethprice --freshen` which takes a long time to run. Referencing #211 and #229.

**Comment by tjayrush** [comment]
This bug was originally written against ethName. I fixed this. The way it works now is this. If the program runs (with any parameters), and the names.conf file is not found, it is created with 'default' data (current list of Ethereum tokens). Also--if the folder the file lives in is not present, it is created. You should be able to delete ~/.quickBlocks, or ~/.quickBlocks/configs, or ~/.quickBlocks/configs/names.conf and it should still work. 

Please test and close if fixed. There is a separate bug for the similar ethprice issue.

**Comment by crodnun** [comment]
Reviewed and closed
