### ISSUE TITLE
Google test api research

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#234]
Do a quick research of the gtest library provided by google to support low level testing (at source code)

**Comment by crodnun** [comment]
I have uploaded a quick guide to install gtest library (under src/others/docs) and you can find here (attached) the quick example I did just to show how it works the low level code testing.
It is just the simplest example you can do, of course we can study a bit more the library doc to add more features, but I just wanted to show you how you can test a class, a function, etc...

Let me know your feedback about the same.

[google_test_library_ubuntu_installation.txt](https://github.com/Great-Hill-Corporation/quickBlocks/files/1227229/google_test_library_ubuntu_installation.txt)
[gtest.tar.gz](https://github.com/Great-Hill-Corporation/quickBlocks/files/1227230/gtest.tar.gz)

**Comment by tjayrush** [comment]
This is excellent. I push a new folder at ./src/test-libs/utillib/gTest which includes a 'shell' for a test using google's test library. I tried to make it work in the current system so that when I do a regular 'make' and then 'make test' from the ./quickBlocks/build folder (as I currently do), it builds and tests the gTest, but I couldn't get it to work.

Can you please take the above gtest.tar.gz file and incorporate it into ./src/test-libs/utillib/gTest. If you do that, I can go ahead and create a whole slew of tests against the libraries. (I'll leave the toml stuff for you, but I can get started on the string class which will be delicate, but is very important to get covered with test cases.

I re-assigned this. I hope that's okay.

**Comment by tjayrush** [comment]
Keep current files as they are and just incorporate the google test code inside the tTest.cpp file. You don't need to create any new files or change the build other than incorporating the google test stuff.

**Comment by crodnun** [comment]
Hi Thomas, I have incorporated the first test at /src/test-libs/utillib/gTest

A dummy one for the moment, I let you define it based on your purposes.

Key points:

1) We now have at root CMakeLists.txt a new dependency: GTEST library. It is checked when you run "cmake ../src"

-- ======== LOOKING FOR GTEST  ========================
-- Found GTest: /usr/local/lib/libgtest.a  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  

2) We link the codes present at /src/test-libs/utillib/gTest to generate a test binary (links also with gtest library itself and pthreads).

3) At /src/test-libs/utillib/gTest/CMakeLists.txt we define a new test with:
   add_test(NAME xxxx COMMAND yyyy)
  This runs the binary obtained from the previous step using the CTest format you already know.

4) Here we have to decide the approach we want to apply because for CTest, all the stuff present at the gTest.cpp is consider a "single test", maybe it is fine to split them into several binaries or consider groups of tests, I let you decide this.

5) When you run "make test"  under build/test-libs/utillib/gTest  you obtain the same output we have seen before:

Running tests...
Test project /home/quickblocks/quickBlocks/build/test-libs/utillib/gTest
    Start 1: gTest
1/1 Test #1: gTest ............................   Passed    0.01 sec

100% tests passed, 0 tests failed out of 1

Success if all the tests defined at gTest.cpp succeeded or fails if any failed.

6) If you want to look at the specific test that failed, you need to run the test itself instead of the CTest wrapper. You can do this with:

<full-path-to-executable>/gTest

This will give you more details of the specific tests run:

[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from COptionsTest
[ RUN      ] COptionsTest.WhatEverYouWant1
[       OK ] COptionsTest.WhatEverYouWant1 (0 ms)
[ RUN      ] COptionsTest.WhatEverYouWant2
[       OK ] COptionsTest.WhatEverYouWant2 (0 ms)
[----------] 2 tests from COptionsTest (1 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (3 ms total)
[  PASSED  ] 2 tests.

**Comment by crodnun** [comment]
Reassigned to Thomas to test and solve doubts

**Comment by tjayrush** [comment]
This works, but I wonder if there is any way to get the test case to output it's results to a ../tests/working/libs/utillib/gTest file for each set of tests. When a test fails, I want a way to easily understand what is broken. Without a 'gold' file to compare against, I have to go to the command line to determine what went wrong. This add an unnecessary step. If we can't get the gTest to write to a file in the ./working folder, I will probably simply write my own testing harness. In fact, there is code in the utillib already that does basically what the Google library does (in a much less capable way, but usable--plus it doesn't impose an installation step on the user.

Just FYI: I am leaning towards not using the google test library. I don't think it brings enough to the table in functionality that I can't easily get myself and it brings an installation step that I very much want to avoid. Plus it feels like its going to add complexity to the testing code, against something Im not interested in for the limited functionality.

**Comment by crodnun** [comment]
OK, then we should decide asap if it makes sense to continue using it. If you prefer to go with gold copies testing we can remove any vestige of the gtest library here.
Let me know how you would like to proceed, if you consider that it adds too much complexity, we should skip it.

**Comment by tjayrush** [comment]
Thanks for the time you spent on this. I've decided we will not be using it. I will remove all the google testing related code from both the test case and the CMakeLists.txt files. You may close this.

**Comment by crodnun** [comment]
Closes, we will not use it
