### ISSUE TITLE
Directory src/other ignored with .gitignore file at src level

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#241]
Today I was trying to add+push the quick guide for Google Test library (gtest) under src/other/docs.

But I detected that we have it included at src/.gitignore file, is this required or just something to remove?

**Comment by tjayrush** [comment]
Probably a mistake on my part. If you remove it, what happens?

**Comment by tjayrush** [comment]
I updated the ./src/.gitignore to remove 'other' and made sure ./src/other/.gitignore excludes everything but ./docs and ./papers. Should work now. Please close.

**Comment by crodnun** [comment]
OK, now works as expected
