### ISSUE TITLE
Output directory for test binaries should be set properly

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#243]
Looking at the output directory where the test binaries are generated, I saw this:

./src/test-libs/utillib/tomlTest/bin/tomlTest
./src/test-libs/utillib/stringTest/bin/stringTest
./src/test-libs/utillib/jsonTest/bin/jsonTest
./src/test-libs/utillib/colorTest/bin/colorTest
./src/test-libs/utillib/bigIntTest/bin/bigIntTest
./src/test-libs/utillib/gTest/bin/gTest
./src/test-libs/abilib/abiTest/bin/abiTest

I think that we should put them under bin/test or at least out of the src directory, it is not a good practice to mix binaries with sources.

**Comment by tjayrush** [comment]
Okay. Do you want to tackle this one? This sounds like it might take some work in the CMake files which (as we've discovered) are not my strong suit.

Please go ahead and make the changes.

One concern I have, and the reason why these test case binaries were not simply copied to the ./quickBlocks/bin folder is that I didn't want to require the end user to modify his/her path for these 'test only' programs. And--I didn't want to 'polute' ./bin.

As long as you can put them in ./bin/test or somewhere and you don't have to modify the end user's path, then it's okay to move them. Thanks. I'm not sure if I should change the assignee or not.

**Comment by crodnun** [comment]
Yes assign it back to me, I will add them at bin/test

**Comment by crodnun** [comment]
Now all the test binaries under test-libs directory will be generated in the output directory bin/test.

I let you double check it at your side before closing (I did the change, you close the issue ;-) when tested).

If I missed any binary that shoul be put there, you just need to modify the CMakeLists.txt to have this:

# Output
set(EXECUTABLE_OUTPUT_PATH "${CMAKE_SOURCE_DIR}/../bin/test")

**Comment by tjayrush** [comment]
This works. Closing.

**Comment by tjayrush** [comment]
Sorry. I guess you need to close it since you created it. You may close this.

**Comment by crodnun** [comment]
OK, If you tested the same, closing

**Comment by tjayrush** [comment]
Yes. It's all working.
