### ISSUE TITLE
Missing GTEST library when building

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#244]
I get this error message when I build now:

-- ======== LOOKING FOR PYTHON ========================
-- ======== LOOKING FOR CURL ========================
-- ======== LOOKING FOR GTEST  ========================
CMake Error at /usr/local/Cellar/cmake/3.8.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR
  GTEST_MAIN_LIBRARY)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.8.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.8.1/share/cmake/Modules/FindGTest.cmake:200 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:40 (find_package)

-- Configuring incomplete, errors occurred!
See also "/Users/jrush/src.GitHub/quickBlocks/build/CMakeFiles/CMakeOutput.log".
<hr>

I understand that I will need to open ./src/other/docs/google_test....insturction.txt, but it doesn't work on my mac.

Also, I don't think our end users will understand that from the above error message.

Is there some way we can make a much more informative instruction if the google test is not installed. I'm concerned that if we can't fix this issue very easily for the end user we will lose 3/4 of all users if this fails.

From my own personal experience---if I get an error like this, no matter how much I think a tool can help me, I will quit using it at this point.

Because the google test library is not central to the operation of the tools (it's for testing), this concerns me if it's worth it. If I have to, I will write my own gTest libraries or hack something together to do functional testing.

**Comment by tjayrush** [comment]
https://github.com/iat-cener/tonatiuh/wiki/Installing-Google-Test-For-Mac

**Comment by tjayrush** [comment]
I did:

    git clone https://github.com/google/googletest.git
    cd googletest
    mkdir build
    cd build
    cmake -G"Unix Makefiles" ..
    make
    cp -r ../include/gtest /usr/local/include
    cp lib* /usr/local/lib

**Comment by tjayrush** [comment]
It now works.

**Comment by tjayrush** [comment]
Please see my notes on #234

**Comment by crodnun** [comment]
OK Thomas, we can joing both issues and decide what to do next. I knew that gtest could be too much for this project, but wanted to show you how you can test low level cpp code using an existing library, widely used at many projects, of course if you prefer to code your own tests and do not add complexity, we should remove it from the project.

**Comment by tjayrush** [comment]
I think it has some good ideas that I think I will steal (i.e. ASSERTs), but I agree. The google test lib is too much. Mostly due to installation issue. I will close this.
