### ISSUE TITLE
Remove gtest support from quickblocks project

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#246]
We are no longer interested in using this third party library. So we should remove it from build steps

**Comment by tjayrush** [comment]
I'll remove it. When it's removed, I will post here and you can confirm and close. I'll do this now.

**Comment by tjayrush** [comment]
Okay. The gtest lib stuff is removed. You may close this. I renamed the test case to apiTest and I will be writing some simply ASSERT macros soon.

**Comment by crodnun** [comment]
Perfect, any dependency with gtest is now removed from the project and it builds smoothly now, closing
