### ISSUE TITLE
Management of API key at ethslurp

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#248]
To start testing ethslurp I would like to know a few details:

It requires an API-KEY, 

1) can I use yours for testing purposes? 
2) Could I generate my own key somehow?

3) Is it mandatory, if I enter any data there (when key is requested), the program seems to start slurping:

Processing: 0000
        Slurping 0000
        Slurping new transactions from blockchain...

  No transactions were found for address '0000'. Is it correct?

  Usage:    ethslurp [-a|-b|-d|-m|-n|-r|-f|-i|-e|-o|-l|-c|-t|-v|-h] addr  
  Purpose:  Fetches data off the Ethereum blockchain for an arbitrary account or smart contract. Optionally formats the output to your specification.
  
4) When I invoke it, it generates the file .quickBlocks/quickBlocks.toml with some kind of configuration, what is its purpose at high level (tester level :-))?

**Comment by tjayrush** [comment]
A couple of things.

1) Ethereum addresses should be 42 characters long and start with 0x, so 0000 should report an error (you found a bug already)
2) You can get an API key here: https://etherscan.io/apis . Unfortunately, I don't think there's anything we can do about this other than make sure the documentation is as helpful as it can be.
3) You should have gotten a message the first time it runs asking for an API key, but it uses gets() to retrieve the input so the test case will appear to hang.
4) You can use mine for test purposes, but I'd rather if you didn't. I worried that they will disable my key if it's being used from multiple locations. I'm even thinking of getting a different key for my Ubuntu box.

Hope this helps. Please let me know if you need anything else.

**Comment by crodnun** [comment]
OK, I managed to get my own API key registering at  https://etherscan.io, will continue with the tests now using this personal key.

**Comment by tjayrush** [comment]
Can this be closed? I posted this bug (#259) to keep track of the "first use" issue.
