### ISSUE TITLE
Windows port

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#249]
I am only putting this here as a reminder of later work.  I made it status-delayed and Milestone 0.5.0.

Please make very short notes on your thoughts on how hard this will be. What would be involved? Is it mostly changes to CMake or will there be code changes?

Also--please note how, very briefly, how to set myself up with a build environment. (but don't actually set anything up).

Once you've added your thoughts, please re-assign this to me.

**Comment by crodnun** [comment]
Perfect Thomas, I will work on this after testing

**Comment by tjayrush** [comment]
Let's wait on this one. I want to do this at some point, but before we do, we have a large amount of testing to do. I pushed it to Release 0.5.0. Let's fix all 0.2.0 issues first.

**Comment by tjayrush** [comment]
Closing for now. Will reopen once 0.2.0 is finished. Referenced by #293.

**Comment by tjayrush** [comment]
No windows port
