### ISSUE TITLE
Handle need for nano editor differently

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#251]
Instead of handling the need for the nano editor by requiring it in order to install the software, I want to wait until the end user first tries to use one of the tools that allows for editing a file via using 'nano.'

I want to do this so, (a) the install has one less dependency, and (b) the end user, by editing a configuration file, can select which ever editor he/she wants.

I will search out all uses of 'open' or 'nano' in the code, abstract out a 'first-use' interaction where the end user selects an editor, and then store that in a config file so they can change it at a later date.

**Comment by crodnun** [comment]
Removed dependency of nano editor at root CMakeLists.txt, to be reviewed and closed.

Let me know if this is what you expected, of course as you mentioned at first post within this issue, you need to take care of the editor at codes.

If this is what you expected, you can close it.

**Comment by tjayrush** [comment]
I will close this in lieu of #272 so we can keep track of the issue.
