### ISSUE TITLE
ethslurp starts the scan with invalid address and invalid key

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#252]
We already knew this, but I open an issue to keep track. I pass as address = "09" and as key a dummy value "g" and seems to start slurping.

Running the following:

$ ./ethslurp 09
Processing: 09

  ***Warning***
  This program needs an api_key from EtherScan in order to work. You may get one at
  http://etherscan.io/apis. See our online help file for more information.
  Please provide an API key or type 'exit'
  > g
        Slurping 09
        Slurping new transactions from blockchain...

  No transactions were found for address '09'. Is it correct?

  Usage:    ethslurp [-a|-b|-d|-m|-n|-r|-f|-i|-e|-o|-l|-c|-t|-v|-h] addr  
  Purpose:  Fetches data off the Ethereum blockchain for an arbitrary account or smart contract. Optionally formats the output to your specification.
             
  Where:    
        addr                  the address of the account or contract to slurp (required)
        -a  (or --archive)    filename of output (stdout otherwise)
        -b  (or --blocks)     export records in block range (:0[:max])
        -d  (or --dates)      export records in date range (:yyyymmdd[hhmmss][:yyyymmdd[hhmmss]])
        -m  (or --max)        maximum transactions to slurp (:250000)
        -n  (or --name)       name this address
        -r  (or --rerun)      re-run the most recent slurp
        -f  (or --fmt)        pretty print, optionally add ':txt,' ':csv,' or ':html'
        -i  (or --income)     include income transactions only
        -e  (or --expense)    include expenditures only
        -o  (or --open)       open the configuration file for editing
        -l  (or --list)       list previously slurped addresses in cache
        -c  (or --clear)      clear all previously cached slurps
        -t  (or --test)       generate intermediary files but do not execute the commands
        -v  (or --verbose)    set verbose level. Either -v, --verbose or -v:n where 'n' is level
        -h  (or --help)       display this help screen

  Powered by QuickBlocks

**Comment by tjayrush** [comment]
Referencing #85

**Comment by crodnun** [comment]
Even when not entering a valid key, we slurp data, why this happens? I have my own API key (I got it from ethscan as you recommended) but seems not used at this tool.

**Comment by tjayrush** [comment]
I think there are two bugs here. Please close this one after confirming that I've captured the two problems in the reference issues below:

#285

**Comment by tjayrush** [comment]
The bug documented here (ethslurp accepts invalid addresses to slurp) should be fixed to the best of my ability.

Here's a definition of a valid Ethereum address:

1) it is 40 characters long
2) the characters are in the range [0-9,a-f,A-F] -- that is valid hexidecimal

Every 40 character string that is all hex is valid. Anything else is invalid. This should apply to all tools and apps. 

I will link to this issue as soon as I fix this, but the fix should apply to every tool and app.

**Comment by tjayrush** [comment]
I think the 'invalid address' problem should be fixed. You may close this if you agree.

**Comment by crodnun** [comment]
Being a bit picky, the validation is done now correctly. But makes sense to show the help when address is OK and API_KEY is OK but none TX was found for this address?

We display now:

carlos@ubuntu-4gb-fra1-01:~/quickblocks/bin$ ./ethslurp 0x0900000000000000000000000000000000000000
Processing: 0x0900000000000000000000000000000000000000
        Slurping 0x0900000000000000000000000000000000000000
        Slurping new transactions from blockchain...

  No transactions were found for address '0x0900000000000000000000000000000000000000'.

-------------------------------  AFTER THIS, makes sense to show help again??? ------------------------

We entered valid data for both eth address and API key, and our search returned no matches, as a user I do not like to see the help again when my command was correct. 

If you consider that this is too picky, we will close it, address validation is done now correctly, just an improvement here not displaying the help again when no matches found.

**Comment by tjayrush** [comment]
Not too picky at all. I love the picky ones.

I now only display the message that no transactions were found. You may close this if you like.

**Comment by crodnun** [comment]
Being picky again, we have a typo :-) at help message:

-------------------------------------------------------------------------------------------
 Please see the full "**documenation**" for more information on display strings. 
-------------------------------------------------------------------------------------------

When this done I think that I will close it, I will update gold copy and tests

**Comment by tjayrush** [comment]
I pushed an update to the typo. Not too picky at all--your exactly the right amount of picky.

Question for you: when you run the tests, do you use `make test`? Some of the gold test cases in ./test/gold/tools/ethslurp seem to have been run from the command line. Is that the case?

They appear broken on my build, but maybe I'm doing something wrong.

**Comment by crodnun** [comment]
Reviewed typo and closed issue
