### ISSUE TITLE
ethereum addresses

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#253]
Hi Thomas I open this as a doubt to request you a way to test ethslurp better.

I have now my own API key (configured at my Ubuntu) and am able to retrieve transactions but I would like to know if there are well known addresses we can test with that have small number of transactions, etc,... or maybe check this online somewhere (I know that there are some websites where you can check this but would like to know your opinion).

The first one I tried with was this (picked from your tests): 

0xB64ef51C888972c908CFacf59B47C1AfBC0Ab8aC

And I obtained a great amount of transactions (I waited for a long while till command finished)

>>>>>   Exported 34275 records in 204.403 seconds 

It is not the best for testing, because it runs for minutes and would like to have an smaller number of transactions to test this command.

**Comment by tjayrush** [comment]
There's a smart contract call EEAR that has a small number of transactions. Address 0x713B73c3994442b533e6A083eC968e40606810Ec. It's pretty old (and it's mine) so I know that no-one is using it any more.

**Comment by tjayrush** [comment]
Also, there's a tool in ./quickBlocks/bin called ethscan that allows you to open the online blockchain scraper to any block, address, or transaction hash. Perhaps we can translate this to python (if that makes sense). It's very useful.

**Comment by crodnun** [comment]
OK closing now and created a low priority issue #258 for the script conversion
