### ISSUE TITLE
Duplicated help message displayed when running wrong command

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#254]
When I run the following command:

>   ./ethslurp -a carlos.txt 0xbf4ed7b27f1d666546e30d74d50d173d20bca754

Processing: -a carlos.txt 0xbf4ed7b27f1d666546e30d74d50d173d20bca754

  -a and -n may not both be empty. Specify either an archive file or a name. Quitting...

  Usage:    ethslurp [-a|-b|-d|-m|-n|-r|-f|-i|-e|-o|-l|-c|-t|-v|-h] addr  
  Purpose:  Fetches data off the Ethereum blockchain for an arbitrary account or smart contract. Optionally formats the output to your specification.
             
  Where:    
        addr                  the address of the account or contract to slurp (required)
        -a  (or --archive)    filename of output (stdout otherwise)
        -b  (or --blocks)     export records in block range (:0[:max])
        -d  (or --dates)      export records in date range (:yyyymmdd[hhmmss][:yyyymmdd[hhmmss]])
        -m  (or --max)        maximum transactions to slurp (:250000)
        -n  (or --name)       name this address
        -r  (or --rerun)      re-run the most recent slurp
        -f  (or --fmt)        pretty print, optionally add ':txt,' ':csv,' or ':html'
        -i  (or --income)     include income transactions only
        -e  (or --expense)    include expenditures only
        -o  (or --open)       open the configuration file for editing
        -l  (or --list)       list previously slurped addresses in cache
        -c  (or --clear)      clear all previously cached slurps
        -t  (or --test)       generate intermediary files but do not execute the commands
        -v  (or --verbose)    set verbose level. Either -v, --verbose or -v:n where 'n' is level
        -h  (or --help)       display this help screen

  Powered by QuickBlocks

  Usage:    ethslurp [-a|-b|-d|-m|-n|-r|-f|-i|-e|-o|-l|-c|-t|-v|-h] addr  
  Purpose:  Fetches data off the Ethereum blockchain for an arbitrary account or smart contract. Optionally formats the output to your specification.
             
  Where:    
        addr                  the address of the account or contract to slurp (required)
        -a  (or --archive)    filename of output (stdout otherwise)
        -b  (or --blocks)     export records in block range (:0[:max])
        -d  (or --dates)      export records in date range (:yyyymmdd[hhmmss][:yyyymmdd[hhmmss]])
        -m  (or --max)        maximum transactions to slurp (:250000)
        -n  (or --name)       name this address
        -r  (or --rerun)      re-run the most recent slurp
        -f  (or --fmt)        pretty print, optionally add ':txt,' ':csv,' or ':html'
        -i  (or --income)     include income transactions only
        -e  (or --expense)    include expenditures only
        -o  (or --open)       open the configuration file for editing
        -l  (or --list)       list previously slurped addresses in cache
        -c  (or --clear)      clear all previously cached slurps
        -t  (or --test)       generate intermediary files but do not execute the commands
        -v  (or --verbose)    set verbose level. Either -v, --verbose or -v:n where 'n' is level
        -h  (or --help)       display this help screen

  Powered by QuickBlocks

It prints twice the help information.

**Comment by tjayrush** [comment]
Technically, this should be

    ./ethslurp -a:carlos.txt 0xbf4ed7b27f1d666546e30d74d50d173d20bca754

(colon between '-a' and 'carlos.txt' . If you do that, it works.

But this brings open a much larger issue that we've seen before. The use of ":" to separate a two part command is definitely wrong. For now, just add a colon between the -a and the carlos.txt and write a new bug about the problem (which appears in all tools). I will try to fix that bug over the weekend.

The 'two help screens' problem is a bug, so we can leave this one open, but let's make the 'two help screens' the real bug here (since adding ':' fixes this).

**Comment by crodnun** [comment]
OK title changed at issue and also updated bug to be fixed

**Comment by tjayrush** [comment]
I just want to not forget the 'colon' separator issue #260

**Comment by tjayrush** [comment]
Referencing #85

**Comment by tjayrush** [comment]
I removed the --name option. To specify the name of an archive file, one should use the -a option. (Note, -n is now a hidden option, but does not need to be tested. I added it to the hidden option issue #238).

You should be able to close this one, I think.

**Comment by crodnun** [comment]
Confirmed, it is solved
