### ISSUE TITLE
ethslurp option not implemented yet

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#256]
When I run:

> ./ethslurp -c

Processing: -c
Clearing the cache is not implemented. You may, if you wish, remove all
files in /home/quickblocks/.quickBlocks/slurps/ to acheive the same thing. If you
do delete the cache, large contracts may take a very long time to re-generate.

Do we need to implement it? or just remove from the available options and help?

**Comment by tjayrush** [comment]
I made this a hidden option (and added it to the list in #238). It will remain un-implemented, but perhaps it will become handy for testing. If you find that it would be helpful for testing, let me know, and I will implement it. For now, I think you can close this one.

**Comment by crodnun** [comment]
OK reviewed and closing it
