### ISSUE TITLE
Doubt regarding ethslurp option (-n)

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#257]
What is the purpose of this option?
At my tests I can not appreciate any change running the command with this option.

-----------------------------------------------------------------------------------------------------------------
If we run:

> ./ethslurp -b:4158089:4158089 0xB64ef51C888972c908CFacf59B47C1AfBC0Ab8aC -n

Processing: -b:4158089:4158089 0xB64ef51C888972c908CFacf59B47C1AfBC0Ab8aC -n
        Slurping 0xb64ef51c888972c908cfacf59b47c1afbc0ab8ac
...
...
...
(seems working and -n option without args is not rejected)

-----------------------------------------------------------------------------------------------------------------
If we run:

./ethslurp -b:4158089:4158089 0xB64ef51C888972c908CFacf59B47C1AfBC0Ab8aC -n myname
Processing: -b:4158089:4158089 0xB64ef51C888972c908CFacf59B47C1AfBC0Ab8aC -n myname
        Slurping myname
        Slurping new transactions from blockchain...

  No transactions were found for address 'myname'. Is it correct?

-----------------------------------------------------------------------------------------------------------------

If we run:

./ethslurp -b:4158089:4158089 0xB64ef51C888972c908CFacf59B47C1AfBC0Ab8aC -n  0xB64ef51C888972c908CFacf59B47C1AfBC0Ab8aC
Processing: -b:4158089:4158089 0xB64ef51C888972c908CFacf59B47C1AfBC0Ab8aC -n 0xB64ef51C888972c908CFacf59B47C1AfBC0Ab8aC
        Slurping 0xb64ef51c888972c908cfacf59b47c1afbc0ab8ac
        Slurping new transactions from blockchain...
        Downloaded 4278 potentially new transactions.
        Download contains blocks from 4158089 to 4172274
Killed

The process seems being killed somehow!

**Comment by tjayrush** [comment]
This is a good bug, but I think we may 'delay' this one. I think the intention was to have the ability to store the results in an 'archive' with the -a option. If -a is present then the 'slurp's' name becomes the archive name. If an archive is not created, you can still create a name. I think the 'name' (whether provided by -a or -n) was intended to be added to the ethName tool so you could easily search for it, but I don't think that aspect was ever completed.

So--just to try to document it:

    If -a is present, then this is the name of the archive file and the 'name' of the address that should be added to the ethName database (-a overrides -n)
    If -a is not present, and -n is present, then add this name to the ethName database
    If neither -n nor -a is present -- no name

    If a name is already associated with this address, and either -a or -n is found, replace the name in the ethName database (not implemented)

    The archive file is called -a:name and may contain '/' and '.' as any path. If -fmt is 'txt', 'json', 'csv' or 'html', and there is no '.', then a file type is attached to the archive of this type, otherwise file type is .txt. An archive string may contain '/' to store in a subfolder of current working folder or to specify any valid path.

**Comment by tjayrush** [comment]
I labeled this 'status-delayed'. I will keep the assignment.

**Comment by tjayrush** [comment]
Referencing #85

**Comment by tjayrush** [comment]
Please close this issue for now. I will re-open it once we're done with the 0.2.0 release. It's noted in #293.

**Comment by tjayrush** [comment]
The -n option has been removed. It had no purpose as you noted above. You may close this bug.

**Comment by crodnun** [comment]
Perfect, option no longer available, so no bug
