### ISSUE TITLE
Convert ethscan script into python

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#258]
I create this issue and assign it initially to Thomas , to let him decide what to do.

The ethscan is right now a shell script and should be converted to a different language, here we have 2 options:

1) Python script
2) C++ code based on curl library (that is currently used along the project and it is a dependency we need)

Thomas to decide what to do here.

**Comment by tjayrush** [comment]
I think Python is fine. You're welcome to do the translation if you wish. (I would do it, but it would take me a million years).

The only reservation I have is this. Does a Python script have to have a .py file type?

I very much would rather it didn't have a .py file type so that it "looks like" a regular 'command line' tool. Having to add .py file type, would make me lean towards writing it in C++.

**Comment by crodnun** [comment]
At all, you can put whatever extensio or just none extension. This is just a good practice to identify files at first glance, but if you want to hide the extension, is perfectly feasible. I keep this assigned to me if you agree.

**Comment by tjayrush** [comment]
Is there a way to open a webpage from a script that is cross-platform? If not, then it probably doesn't make sense to make this a full-fledged tool. Maybe it's only a convenience tool for Mac.

**Comment by tjayrush** [comment]
The script is here: https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/tools/scripts/ethscan

**Comment by crodnun** [comment]
It is converted to python and tested under Ubuntu (with graphical interface) and MAC. At both scenarios we open a browser and launch the suitable URL. 

I kept the old bash script renamed to ethscan_bash (at same directory) just in case you needed it in the future.

I do not use the .py extension at file as you requested, the pity here is that for Windows we will need to invoke it with the interpreter, it is not able to recognize how execute it without the extension. 

Please double check it at your side to close this issue or update the tool with your thoughts

**Comment by tjayrush** [comment]
This is very, very close to exactly what I want.  I run these command against the new script and it works in each case:

// properly opens to home page
$ ethscan 

// properly opens to the dao address 0xbb9...
$ ethscan `ethName -a dao`

// properly opens to a transaction
$ ethscan 0xdf169cc3702f157f37a40515efc54c0f1ad1ca35305ced5f65fb9262e7b6c5a5

// properly opens to a block
$ ethscan 1001001

// The only trouble I found was this case:
$ cat 1001001 | ethscan -
// and this case
$ cat 1001001 | ethscan

// which should open to the block, but open to an error page in the first case and
// the home page in the second case.

Is there some way for your script to read from stdin if it gets no parameters or a single parameter of '-'?

If you can get this to work, I will close this.

**Comment by tjayrush** [comment]
Concerning the name: I'm open to using ethscan.py if you think it's better. You call.

**Comment by crodnun** [comment]
Ok renamed then to ethscan.py, this is more portable (this way it also works for windows users, windows is able to identify the interpreter with the extension).

What I do not understand are the troubles you reported, I tested this against the old bash version at my MAC and I see the same behaviour for both commands.

Testing at MAC with old bash and running:

1) cat 1001001 | ethscan       (we obtain the main page of etherscan.io)
2) cat 1001001 | ethscan  -   (the bash script interprets the '-' as a block number and shows error page)

Testing the new python script at Ubuntu (and at MAC)

1) cat 1001001 | ethscan.py      (main website page)
2) cat 1001001 | ethscan.py      (error page searching '-' as a block number)

Could you clarify a bit what do you mean? I think that both tools behave the same way, how you make the old bash script work this way?

**Comment by tjayrush** [comment]
You're correct. My mistake. As far as I'm concerned, this may be closed.

**Comment by crodnun** [comment]
OK closing it now after confirming that works like previous bash script
