### ISSUE TITLE
make lint

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#267]
I use something called pylint () to do linting on my code. I'd like to build it into our process. I'd rather not have a separate dependency (as I indicated elsewhere I do not like dependencies).  Here's the python code for pylint which has been modified to disable certain warnings that I don't like. Can we get this running with a 'make lint' command?

---> ***removed script***

**Comment by crodnun** [comment]
Of course if we include a new python script within github repository with this content, we can create a new target that invokes this script. Let discuss if this is your goal

**Comment by crodnun** [comment]
Hi Thomas, could you attach  here the original file (that is working) or push a working version to repository under src/tools/scripts/ with name pylint.py. I tried to copy and paste the script content you supplied but it is really a pain to work this way and presents many errors I need to study, probably related with python version or similar.
I will need as much information as possible of how you currently use it, setup (if any), python version you  are using. I did a first attempt copying and pasting it from here but I could not make it run, many python errors there.

**Comment by crodnun** [comment]
make lint is now available at project but for the moment dummy one, pending to see how we want to use this python script.

If you do:
> cmake ../src
> make lint    (this target is alive and runs without no output for the moment, pending to implement its logic)

**Comment by tjayrush** [comment]
I copied a working version of pylint.py into ./src/tools/scripts and it now gets copied into ./bin.  I can use it by changing into a source folder (./src/tools/getBlock for example) and running

    pylint.py *.cpp

And it works exactly as I want it to. 

I think I made a mistake to say it should be part of the build. I can do the linting in each separate folder by just running it directly. If there are errors, I need to be in that folder anyway, so there's no need for a 'make lint' target. The linter is working as I want it to work.

You may confirm that pylint.py gets installed into ./bin and that it runs, but other than that, I will close this issue.

**Comment by crodnun** [comment]
OK, I have removed the lint target from those places where I added it. 
Checked that it builds correctly and is installed under ./bin
Then is up to users to configure the ./bin at PATH, otherwise you will not be able to see it.

If you take care of the PATH setting, we can close this, I see it OK

**Comment by tjayrush** [comment]
I notes the need for setting $PATH in #100
