### ISSUE TITLE
Build broken after cmake + make

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#270]
At 60% it errors out here and I am not able to build whole project:

Scanning dependencies of target cmdLineTest
[ 60%] Building CXX object libs/test-libs/utillib/cmdLineTest/CMakeFiles/cmdLineTest.dir/cmdLineTest.cpp.o
In file included from /home/quickblocks/quickBlocks/src/libs/utillib/basetypes.h:57:0,
                 from /home/quickblocks/quickBlocks/src/libs/utillib/utillib.h:9,
                 from /home/quickblocks/quickBlocks/src/libs/abilib/abilib.h:9,
                 from /home/quickblocks/quickBlocks/src/libs/etherlib/etherlib.h:13,
                 from /home/quickblocks/quickBlocks/src/libs/test-libs/utillib/cmdLineTest/cmdLineTest.cpp:10:
/home/quickblocks/quickBlocks/src/libs/test-libs/utillib/cmdLineTest/cmdLineTest.cpp: In function â€˜bool func_Test1(int)â€™:
/home/quickblocks/quickBlocks/src/libs/test-libs/utillib/cmdLineTest/cmdLineTest.cpp:42:85: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
     if (opts.testNum ==  8) ASSERT_TRUE( "8. uint == -100 (false)", (opts.numOption == NOPOS) );
                                                                                      
/home/quickblocks/quickBlocks/src/libs/utillib/testing.h:47:6: note: in definition of macro â€˜ASSERT_TRUEâ€™
 if ((test)) { \

**Comment by tjayrush** [comment]
Very sorry about this. I know it's a pain in the ass. Are you stuck when this happens? You can always just remove the add_subdirectory line from parent folder's CMakeLists.txt file.

**Comment by tjayrush** [comment]
Bad habits die slowly.

**Comment by tjayrush** [comment]
I commented out the cmdLineTest in ../src/lib/test-libs/CMakeLists.txt

**Comment by crodnun** [comment]
OK, reviewed that now works

**Comment by tjayrush** [comment]
I looked into this. On a Mac a signed to unsigned implicit conversion does not cause a warning to be generated. You must add the -Wconversion mark to the CMAKE_CXX_FLAGS.

**Comment by tjayrush** [comment]
I changed the CMakeFiles.txt to use if(APPLE) to enable -Wconversion on APPLE only.
