### ISSUE TITLE
Duplicated help message at ethslurp

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#274]
When running this command (passing archive param without value), it duplicates the help message:

./ethslurp -a 0x00001111111111111111

Processing: -a 0x00001111111111111111

  -a and -n may not both be empty. Specify either an archive file or a name. Quitting...

  Usage:    ethslurp [-a|-b|-d|-n|-r|-f|-i|-e|-o|-l|-t|-v|-h] addr  
  Purpose:  Fetches data off the Ethereum blockchain for an arbitrary account or smart contract. Optionally formats the output to your specification.
             
  Where:    
        addr                  the address of the account or contract to slurp (required)
        -a  (--archive)       filename of output (stdout otherwise)
        -b  (--blocks)        export records in block range (:0[:max])
        -d  (--dates)         export records in date range (:yyyymmdd[hhmmss][:yyyymmdd[hhmmss]])
        -n  (--name)          name this address
        -r  (--rerun)         re-run the most recent slurp
        -f  (--fmt)           pretty print, optionally add ':txt,' ':csv,' or ':html'
        -i  (--income)        include income transactions only
        -e  (--expense)       include expenditures only
        -o  (--open)          open the configuration file for editing
        -l  (--list)          list previously slurped addresses in cache
        -t  (--test)          generate intermediary files but do not execute the commands
        -v  (--verbose)       set verbose level. Either -v, --verbose or -v:n where 'n' is level
        -h  (--help)          display this help screen

  Powered by QuickBlocks

  Usage:    ethslurp [-a|-b|-d|-n|-r|-f|-i|-e|-o|-l|-t|-v|-h] addr  
  Purpose:  Fetches data off the Ethereum blockchain for an arbitrary account or smart contract. Optionally formats the output to your specification.
             
  Where:    
        addr                  the address of the account or contract to slurp (required)
        -a  (--archive)       filename of output (stdout otherwise)
        -b  (--blocks)        export records in block range (:0[:max])
        -d  (--dates)         export records in date range (:yyyymmdd[hhmmss][:yyyymmdd[hhmmss]])
        -n  (--name)          name this address
        -r  (--rerun)         re-run the most recent slurp
        -f  (--fmt)           pretty print, optionally add ':txt,' ':csv,' or ':html'
        -i  (--income)        include income transactions only
        -e  (--expense)       include expenditures only
        -o  (--open)          open the configuration file for editing
        -l  (--list)          list previously slurped addresses in cache
        -t  (--test)          generate intermediary files but do not execute the commands
        -v  (--verbose)       set verbose level. Either -v, --verbose or -v:n where 'n' is level
        -h  (--help)          display this help screen

  Powered by QuickBlocks

**Comment by tjayrush** [comment]
The double error report should be fixed, but the error message is probably wrong. I cannot tell if the 0x00110001 is supposed to be a file name (as it should be if the user intends to use the -a option) or if it's an address (as it appears to be). The error the code reports now indicates that the 0x010110101 string was interpreted as the archive file name.

I'd like to close this bug. The ethslurp code is going to have to undergo (at some future date) a significant re-write. The use of both -a for archive name and -n for name will have to be corrected as it's very confused as it is. I'm noting this here so I can remember it if I ever revisit this issue.

Please close this issue as resolved.

**Comment by crodnun** [comment]
OK no longer present this bug, closing
