### ISSUE TITLE
ethslurp long options (those with --xxxxx) seems not supported yet

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#275]
When we try to launch the app using the options displayed at help, all them are reported as "not supported".

./ethslurp --blocks 
Processing: --blocks

  Invalid option --blocks

quickblocks@ubuntu-1gb-lon1-01:~/quickBlocks/bin$ ./ethslurp --dates
Processing: --dates

  Invalid option --dates

./ethslurp --archive:file 0xb64ef51c888972c908cfacf59b47c1afbc0ab8ac
Processing: --archive:file 0xb64ef51c888972c908cfacf59b47c1afbc0ab8ac

  Invalid option --archive:file

**Comment by tjayrush** [comment]
These are very poorly documented as is clear given how you interpreted their use. Each of these needs an additional value. --blocks needs a range of blocks to 'slurp.'  --dates needs a range of dates to limit the search to, --archive needs a filename.

I made some changes to remove the use of a ':' to separate parameters from these additional values that some parameters need. This recent change, should make the help information a bit more understandable by including the word 'val' next to any parameter that needs another value.

Let's delay this one, as we need to focus on getting the node running as you've documented here: #181

**Comment by tjayrush** [comment]
All of the 'long' options for ethslurp were broken. They were expecting a single dash in front of the option instead of a double dash (--). They should now be fixed, and you may close this bug.

**Comment by crodnun** [comment]
OK, then they (long options) should be removed from the help message to not confuse users.

**Comment by tjayrush** [comment]
I fixed all the long (i.e. --) options, so they should all be working now. Please confirm and close this particular issue (even if the options themselves don't work, you may close this if the --long versions no longer report invalid argument.)

**Comment by crodnun** [comment]
Verified, all options are supported tests, will open new issues when testing them again
