### ISSUE TITLE
Ethereum learning

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#278]
Investigate a bit more about parity, how it works, where it puts its files, what type of information we have, how are the DB organized, etc

**Comment by tjayrush** [comment]
This is excellent. Learn as much as you can.

Did you start parity with --tracing on --pruning archive?

There's another Ethereum node implementation called `geth`. We will want to start taking a look at this at some point. Some of the data delivered by `geth` is slightly different from `parity`, so in the long run, we will have a setup with `parity` (perhaps on my Mac) and `geth` perhaps on a remote digital ocean install, and `infura`.

Let's stick with Parity for now since we don't want to be battling on two fronts.

**Comment by tjayrush** [comment]
This is another thing we might want to look at. It's a "fake" Ethereum node intended to be used for testing. It's supposed to operate exactly like a full node (with totally different data of course), but it's much faster, you can bring it up and down easily, you can save it's state and restore the state easily. Upon reflection, while running and testing against a full node is interesting (and will ultimately be needed), we might be able to set something up where we are both testing against this thing. Sorry I didn't think of this sooner. I was just talking to a friend of mine, and he reminded me of this. Let's spend a little bit of our learning time learning about this: https://github.com/ethereumjs/testrpc

**Comment by crodnun** [comment]
Hi Thomas, I gave a look at the link provided. It looks fine, uses javascript as underlying technology (the tricky part, no fear) but seems to allow you to create your own blockchain for testing purposes.  You can define the accounts you want, initiate transactions, etc....  so more or less to customize your own blockchain and make it evolve based on your requirements/tests. My ethereum node is now at block #2107466 so from my point it is another choice we have for testing, but once ready (up-to-date) the real one, I think that we can use it directly.

**Comment by tjayrush** [comment]
Eventually, QuickBlocks should behave well no matter if the node it's running against is Parity, Geth, TestRPC, or one of the five or six test networks. The goal is for it to run against all of them. I think we should focus on the main-net (either Parity or Geth), and that Parity is better than Geth because I know it doesn't work against Geth (#297). I will re-assign this to you, as it's primarily your issue. Keep learning. The more you know, the better.

**Comment by crodnun** [comment]
Nice progress today, I was able to install test-rpc and play around with the RPC interface.

For the moment I attach you the notes I took, just FYI, I will update them as soon as I get used to manage this environment.

Keep you updated.
[Linux_Ubuntu_testrpc_install.txt](https://github.com/Great-Hill-Corporation/quickBlocks/files/1259206/Linux_Ubuntu_testrpc_install.txt)

**Comment by tjayrush** [comment]
Great stuff.

In your notes, you say 

> When testing, it displays the operations received at command line (while running)

This is great. Try to see if there's a setting that will print more information for each command. If I quit out of Parity, and run testrpc and try to run quickBlocks against testrpc, I can see these commands, but I would love to be able to see the actual parameters that quickBlocks sends.

Also, see if you can't figure out how to save a certain blockchain state and then re-load it later.

**Comment by crodnun** [comment]
Hi Thomas,

Here you have my comments regarding the same (by the way, I renamed this issue to a more general topic like "Ethereum learning").

1) testrpc does not come with logs to show you the RPC request received (bad news).
2) The good news is that I hacked the javascript code used by testrpc to display it :-). Now you can see things like this when sending requests from remote client:

Request coming in: {"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":83}
eth_blockNumber

Let me know if this is what you were looking for, it requires just to add a line at the suitable position to display the request. The big part is to know where, but I am used to hack many things, even when I do not know the language itself (javascript this time, lol)


3) For the second question, how you safe and load later a given blockchain. It comes with an option for the same. Running the following command you can do it:

>  testrpc --db  /path/to/store/blockchain/db       

The first time it stores the DB at the given path, next times picks the blockchain stored at this path to run. So if you want to use an existing blockchain, you need to pass it path at --db option and testrpc will start using the DB/blockchain previously saved on disk.


4) Last but not least, I managed to install truffle too, it is quite easy. And generated my first smart contract against the testrpc blockchain. Of course I do not know yet what it does, but you can see the transactions and blocks generated, so the blockchain itself is updated.

I attach here the notes update with steps 7 to 10 (new ones) that include truffle installation, dummy contract creation, insertion of the contract in blockchain and also at step 10) how you need to start the testrpc to safe/recover your blockchain.


[Linux_Ubuntu_testrpc_install.txt](https://github.com/Great-Hill-Corporation/quickBlocks/files/1260751/Linux_Ubuntu_testrpc_install.txt)

**Comment by tjayrush** [comment]
Great. Question for you: when you attach a .txt file to an issue how can I later find that? I think you should add these files to ./src/other/docs so I can find them easily. Otherwise, I think I have to remember which issue to look at. I know you posted a link to a .txt in another issue recently. Copy that to ./src/other/docs too.

**Comment by crodnun** [comment]
Of course, whatever you consider useful for the project, I will push it into github. I think that it was parity setup,  I will upload both.

**Comment by crodnun** [comment]
L

**Comment by crodnun** [comment]
OK both documents uploaded (parity one updated with latest instructions I used to install parity under Ubuntu)

**Comment by tjayrush** [comment]
Can we close this one? I'm going to try to eliminate all issues over the weekend. I can 'delay' it and then re-open it after 0.2.0 if you want me to. Let me know.

**Comment by crodnun** [comment]
Yes, closing it. We can open a similar one later if required
