### ISSUE TITLE
ethslurp error message should be improved

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#282]
When we run:

-------------------------------------------------------------------------------------------------
./ethslurp -b  0x63c8c29af409bd31ec7ddeea58ff14f21e8980b0
Processing: -b:0x63c8c29af409bd31ec7ddeea58ff14f21e8980b0

  You must supply an Ethereum account or contract address. Use -r flag to rerun the most recently slurped address.

  Usage:    ethslurp [-a|-b|-d|-n|-r|-f|-i|-e|-o|-l|-v|-h] addr  
  Purpose:  Fetches data off the Ethereum blockchain for an arbitrary account or smart contract. Optionally formats the output to your specification.
             
  Where:    

-------------------------------------------------------------------------------------------------

We should say something like invalid/missing blocks range (notice that we are using the -b option but not passing any parameter/range on purpose, so the user should be warned of the expected format there. Error  is too generic

**Comment by tjayrush** [comment]
Totally agree. This is a bug. There are multiple tools that use the block range and all have this same problem. I will delay this one, but it is definitely an issue.

**Comment by tjayrush** [comment]
I made major changes to the command line handling code in ehtslurp. It was one of the first applications written, so its code was pretty poor.

Command line option handling should be much better. Please close this issue and if you find specific problems, please note them in new bugs. The particular issue noted above should be fixed.

**Comment by crodnun** [comment]
OK, now a good error is displayed
