### ISSUE TITLE
ethslurp range management 

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#283]
When we run:

./ethslurp -b:4186279:-1 0x63c8c29af409bd31ec7ddeea58ff14f21e8980b0

(Notice that I put -1 on purpose)

How it considers the -1?? How we deal with upper range if it is not higher than lower? Do we slurp everything?

**Comment by tjayrush** [comment]
Because this bug actually applies to multiple tools (for example, getBlock which also allows a block range), I am going to delay this bug, but it is a real issue. I want to solve it for all tools at once as opposed to solving it each time we find it.

**Comment by tjayrush** [comment]
Please close this issue for now. I will re-open it once we're done with the 0.2.0 release. It's noted in #293.

**Comment by crodnun** [comment]
OK postponed, per Thomas request

**Comment by tjayrush** [comment]
Fixed
