### ISSUE TITLE
Testing tools with gold copies where we display the elapsed seconds is not feasible

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#284]
When we run for example:

-------------------------------------------------------------------------------------------------------------
./ethslurp -b:4186279:4186301 0x63c8c29af409bd31ec7ddeea58ff14f21e8980b0

Processing: -b:4186279:4186301 0x63c8c29af409bd31ec7ddeea58ff14f21e8980b0
        Slurping 0x63c8c29af409bd31ec7ddeea58ff14f21e8980b0
        Slurping new transactions from blockchain...
        Downloaded 2 potentially new transactions.
        Download contains blocks from 4186279 to 4186301
        Loaded 2 total records in 0.444000 seconds
        Filter passed 2 visible records of 2 in 0 seconds

-------------------------------------------------------------------------------------------------------------

The comparison with gold copies depend on the time elapsed that will be different every time we run them, so we will need a kind of "smart testing" to filter those lines that contain specific tags like "seconds", "elapsed", ...  etc, 

Our gold copy should not contain exact values for elapsed time or similar that will depend on the exact moment we run this.

My idea for this would be to:

1) First define gold copies with only those lines we are interested in, removing those lines that are dynamic and will vary depending on the moment.

2) Make smarter our run_the_test() function at Makefiles, to filter those lines that contain specific tags we can define at python like "seconds", "elapsed", etcc... 

This way we can compare safely the gold copies with the output obtained and confirm that tests fail only when we have a difference at the important lines (not the ones that display the time elapsed)

**Comment by tjayrush** [comment]
There is a mechanism [here](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/tools/scripts/testCheck.py#L77) that sets an environment variable. In my code, I can see this setting and simply not print 'temporal' stuff if we're testing (in other words, no need for a solution as there already is one). You should be able to test this with 

    TEST_MODE=true ./ethslurp -b:4186279:4186301 0x63c8c29af409bd31ec7ddeea58ff14f21e8980b0

**Comment by tjayrush** [comment]
Let's close this issue and then if you find a 'temporal' string in a gold test case (I notice there are no `ethslurp` test cases yet), please link to the direct line in the test case and I will remove it. It's very simple, but they are hard to find.

**Comment by crodnun** [comment]
OK, tested that with this mechanism we can hide temporal values. Closing
