### ISSUE TITLE
Extra checkings for date ranges validation to validate only digits

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#286]
Example:

We can run tools using date ranges passing any value (digits validation could be an improvement, rejecting the format when any non-digit char is present)

Example:

Here we pass an arbitrary string for start/end dates and seems to start the search, that obviously will fail later, does not make sense to start if we have an invalid input format.

./ethslurp -d:yyyymmdd:yyyymmdd 0x63c8c29af409bd31ec7ddeea58ff14f21e8980b0

Processing: -d:yyyymmdd:yyyymmdd 0x63c8c29af409bd31ec7ddeea58ff14f21e8980b0
        Slurping 0x63c8c29af409bd31ec7ddeea58ff14f21e8980b0
        Slurping new transactions from blockchain...
        Downloaded 2 potentially new transactions.
        Download contains blocks from 4186279 to 4186301
        Loaded 2 total records in 0.547000 seconds
        Filter passed 0 visible records of 2 in 0 seconds

        Exported 0 records in 0.000999928 seconds

**Comment by tjayrush** [comment]
This is similar to #283 (block range management) in the sense that multiple tools will use this solution. Nice find. This one should be simple to fix, when I find time.

**Comment by tjayrush** [comment]
This should be fixed. It now rejects any dates that are no all digits. You may close this if you agree.

**Comment by crodnun** [comment]
OK, reviewed. Now we validate a bit more the format before running
