### ISSUE TITLE
ethslurp dates range validation missing

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#287]
When passing an end date earlier than start date range we do the search but does not find anything, we should stop search (at this example we have some tx at start date but they are not displayed)

Example:

We pass here start date: 19th May and end date 18th May. This condition should be checked and error out any message because the output is confusing.

 ./ethslurp -d:20170519:20170518  0x1324e7b922b30B49Ab8EA81086341cc41C249346

ethslurp argc: 3 [1:-d:20170519:20170518] [2:0x1324e7b922b30B49Ab8EA81086341cc41C249346] 
ethslurp -d:20170519:20170518 0x1324e7b922b30B49Ab8EA81086341cc41C249346 
Processing: -d:20170519:20170518 0x1324e7b922b30B49Ab8EA81086341cc41C249346
        Slurping 0x1324e7b922b30b49ab8ea81086341cc41c249346
        Slurping new transactions from blockchain...

        Download contains blocks from 3730547 to 4031409

**Comment by tjayrush** [comment]
This should be fixed. You may close it.

**Comment by crodnun** [comment]
Verified and fixed
