### ISSUE TITLE
Passing unsupported format to ethslurp shows and unexpected error

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#288]
When executing:

(Notice that I pass -f:invalid)

./ethslurp  -d:20170519:20170519 -f:invalid 0x1324e7b922b30B49Ab8EA81086341cc41C249346

ethslurp argc: 4 [1:-d:20170519:20170519] [2:-f:invalid] [3:0x1324e7b922b30B49Ab8EA81086341cc41C249346] 
ethslurp -d:20170519:20170519 -f:invalid 0x1324e7b922b30B49Ab8EA81086341cc41C249346 
Processing: -d:20170519:20170519 -f:invalid 0x1324e7b922b30B49Ab8EA81086341cc41C249346
        Slurping 0x1324e7b922b30b49ab8ea81086341cc41c249346
        Slurping new transactions from blockchain...

        Download contains blocks from 3730547 to 4031409
Empty display string 'fmt_invalid_record'. Quiting...

-------------------------------------------------------

As user I expected here a different type of error, the one displayed now does not describe the problem.

**Comment by tjayrush** [comment]
This is actually working as designed. The end user may specify any format they want for the exporte data. All they have to do is make entries in the ~/.quickBlocks/quickBlocks.toml file, and that will be the export format. If there had been an entry in the config file for a format called 'invalid' (we don't care what name they use), it would have worked.

The bug is that it should check for the export format before doing the slurp.

**Comment by tjayrush** [comment]
This should now report an error if the format string is unknown, but it still allows end user to specify customized display strings. You may close this if your think it's fixed.

**Comment by crodnun** [comment]
OK, then I will close it. As a user clearly I miss here many information (regarding customized strings) to use the command and can not understand the error displayed but closing anyways.

**Comment by tjayrush** [comment]
I'll improve the error message to point at the full documentation so the user understand that there is a feature that they may not know about. Re-opening.

**Comment by tjayrush** [comment]
I added a much better error message here briefly explaining the problem and pointing the user to the documentation on display strings (which is here by the way--but way outdated: http://ethslurp.com/doc_dispstr.html).  I think it's okay to close this one. We can revisit it before version 1.0.0 by which time there will be full documentation.

**Comment by crodnun** [comment]
OK, will close it when fixed this typo:

Please see the full "**documenation**" for more information on display strings.

**Comment by tjayrush** [comment]
This should be fixed.

**Comment by crodnun** [comment]
OK, closing it after typo fix
