### ISSUE TITLE
Combination of  date and block search criteria in ethslurp seems not working

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#289]
When we combine the search by block and date like follows:

(Notice that I pass a single day and a single block using at both sides of the ranges the same value for both dates and block height)

./ethslurp  -d:20170519:20170519 -i -b:3730547:3730547 0x1324e7b922b30B49Ab8EA81086341cc41C249346

ethslurp argc: 5 [1:-d:20170519:20170519] [2:-i] [3:-b:3730547:3730547] [4:0x1324e7b922b30B49Ab8EA81086341cc41C249346] 
ethslurp -d:20170519:20170519 -i -b:3730547:3730547 0x1324e7b922b30B49Ab8EA81086341cc41C249346 
Processing: -d:20170519:20170519 -i -b:3730547:3730547 0x1324e7b922b30B49Ab8EA81086341cc41C249346
        Slurping 0x1324e7b922b30b49ab8ea81086341cc41c249346
        Slurping new transactions from blockchain...

        Download contains blocks from 3730547 to 4031409

        {
"hash":"0x5678743a31c0096e3e10459ee695de4f4b09f3a5bcc8fd357ed214ea14283a9b","blockHash":"0xecf4a4750d4b07ee2d3a69894b095c02b6f193704582c3791555186fa4334d33","blockNumber":"3730547","transactionIndex":"16","nonce":"7","timestamp":"1495165137","from":"0x731ad2bfae439955054e576692d456a4affe1328","to":"0x1324e7b922b30b49ab8ea81086341cc41c249346","value":"26911713734980000000000","gas":"21001","gasPrice":"20000000000","cumulativeGasUsed":"379912","input":"0x","isError":"0","isInternalTx":"0","gasUsed":"21000","date":"2017-05-19 03:38:57 UTC","ether":"26911.713734980000000000"
        },
        {
"hash":"0x290b0b5f0a0504df3069f5c65b34386c095af19234f24e9aa222a3f7a7d1823b","blockHash":"0xb16325508885d09880efb6111b5e450f934e77155db250e47e4bc0bfb937b8cf","blockNumber":"3730549","transactionIndex":"17","nonce":"1","timestamp":"1495165176","from":"0x9c6df936c884811b9a6b49f0dd0a62919a6581d4","to":"0x1324e7b922b30b49ab8ea81086341cc41c249346","value":"157900169159979996854272","gas":"21001","gasPrice":"20000000000","cumulativeGasUsed":"1021081","input":"0x","isError":"0","isInternalTx":"0","gasUsed":"21000","date":"2017-05-19 03:39:36 UTC","ether":"157900.169159979996854272"
        },

------------------------------------------------------

We obtain 2 TX but they are at different blocks, first one is at block expected, but second one is at a different block number, so seems that filtering by block is not applied.

If we do not support both filters at the same time, we should error out when both options are supplied. Seems that only the first is applied.

**Comment by tjayrush** [comment]
Excellent catch. This should be disallowed.

**Comment by tjayrush** [comment]
This has been fixed. If a user tries to enter both block range and date they are disallowed. You may close it if you agree.

**Comment by crodnun** [comment]
OK verified
