### ISSUE TITLE
Communication issue, seems we worked on the same files today (ethslurp gold files)

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#290]
As an improvement (now I am pushing you as you requested :-)), we should identify clearly where we are working at each moment or in a weekly basis, remember that there is no tool that can replace the human communication. 

I was working on testing the ethslurp app today (including its gold files) and notice that you were touching the same files I was so probably we changed them at the same time.

We should avoid this type of conflicts if possible just using the communication, that's why I requested you to create a project management issue, this way we can know what is doing everybody and avoid modifying the same files.

We should improve in this, I know that you have to touch everywhere and have in your mind what to do next but if I am helping you with this, we need to improve at this part.

**Comment by tjayrush** [comment]
I understand what you're saying. Can we do it this way?

Can you please post what you're working on for the day in the Project Management issue? I read all of the issues you write each morning when I wake up, so I will see that.

In that way, I can avoid that 'folder' and then range widely across everything else. I do need to be able to move freely throughout the repo making changes to many, many files at a time. (For example, the recent change I made touched fifty files.)

If you put a note at the start of the day saying something like:

    August 25 -- working on ethslurp

then I will try to stay out of that folder (or if I do change anything in there, I will make sure you are finished for the evening and pull your changes). Perhaps you can put a note in that same file when you quit for the day, saying 'Finished."

It's much easier for me to merge two files that have both been changed than for you, so it won't be a problem.

Also--I'm a little confused by what hours you're working. Usually, when I wake up, I see a bunch of changes. And my morning is filled with trying to fix those new bugs, but maybe I should wait until your evening (what time is that) to handle the new bugs you've created.

I work from around 5:30 am EST to around 1:00 am almost every day of the week, just FYI.

**Comment by crodnun** [comment]
Ok let's discuss this on Monday. I think that it has nothing to do with the hours we are working, it is more with the chores distribution and the project management. You as project leader have a clear idea of what you want to achieve for the initial release and what really matters, and at this point we need your help to coordinate this a bit and determine where I can help you. I can not take any issue freely as you expect and work on it because you will probably will use the same files at the same time. So from my point of view you should assign me those chores where you are pretty sure that we will not collide. I see clearly two arwas where we can work now,myou at development and me doing the testing, asking doubts and learning the usage of your tools, being your first client in a word. Today we did testing at the same time and collided, so we need to clearly identify our areas to avoid the same, no more. The development cycle works this way: development, documentation,testing, bug fixing, and repeat again till ready.

**Comment by tjayrush** [comment]
Sorry. I understand. I work too fast sometimes and don't consider the effect on others. I'll try to be better as we work out the kinks. You may close this.

**Comment by crodnun** [comment]
Perfect, just trying to improve the procedures we use.
