### ISSUE TITLE
Readme build is not quite working

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#292]
When I edit one of the README.tmpl.md files and then do this:

    cd ~/quickBlocks/build
    make readme

I would expect it to rebuild the corresponding README.md file, but it doesn't. I have to do this first:

    cd ~/quickBlocks/build
    find . -name "help.txt" -exec rm '{}' ';'
    make readme

and then all the readme files rebuild.

Technically, this is true of the executable as well, but I don't want to re-build if the executable is modified as this would cause all the readmes to re-build all the time.

**Comment by crodnun** [comment]
Hi Thomas, we should fix the "make readme" itself first. I did an attempt from scratch and seems broken.

I did the basic steps any user would do from scratch:

> git clone -b develop xxxxxxx
> mkdir build 
> cd build
> make readme   (this builds the project and tries to create the README files)

It stops here:


Scanning dependencies of target readme
[100%] Generating help.txt
Traceback (most recent call last):
  File "/home/carlos/quickblocks/src/../bin/replaceTag.py", line 73, in <module>
    with open(footerFile, 'r') as file :
IOError: [Errno 2] No such file or directory: '/home/carlos/quickblocks/src/../docs/README.footer.md'
libs/test-libs/utillib/colorTest/CMakeFiles/readme.dir/build.make:57: recipe for target 'libs/test-libs/utillib/colorTest/CMakeFiles/readme' failed
make[3]: *** [libs/test-libs/utillib/colorTest/CMakeFiles/readme] Error 1
CMakeFiles/Makefile2:569: recipe for target 'libs/test-libs/utillib/colorTest/CMakeFiles/readme.dir/all' failed
make[2]: *** [libs/test-libs/utillib/colorTest/CMakeFiles/readme.dir/all] Error 2
CMakeFiles/Makefile2:576: recipe for target 'libs/test-libs/utillib/colorTest/CMakeFiles/readme.dir/rule' failed
make[1]: *** [libs/test-libs/utillib/colorTest/CMakeFiles/readme.dir/rule] Error 2
Makefile:264: recipe for target 'readme' failed
make: *** [readme] Error 2


Let's fix this first, we need an stable readme target to add the changes you requested at this issue, once fixed this I will take care of adding the improvements you requested at cmake level.

**Comment by tjayrush** [comment]
It's weird how things that work on Mac, don't work on your machine. I will look into this and re-assign it once I figure it out.

**Comment by tjayrush** [comment]
I fixed the problem, and then tried to reproduce the issue. I cannot reproduce it, so I think I was just not doing something right. It works now as I would expect. Closing this.
