### ISSUE TITLE
ethslurp usage message should be reviewed

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#296]
Now that we know how it is used this command and understand the options, this usage is not correct:

Usage:    ethslurp [-a|-b|-d|-r|-f|-i|-e|-o|-l|-v|-h] addr  

-------------------------------------------------------------------

We know now that some parameters are mutually exclusive (like -b & -d) or (-i & -e), others can be combined, others are only for admin (maybe these can be hidden), etc,... so as far as I see we should go with something like this.

I see 2 modes of operation, slurping and administrative commands:

Usage:    ethslurp  [-b|-d] [-i|-e] [-a] [-v] [-f] [-h] addr   (for slurping)
               ethslurp  [-r|-l|-o]    (management commands that do not require addr)

I think that maybe for initial releases we can hide away the admin commands and simplify the usage, as a user I am only interested in getting information (slurping mode) and probably the admin ones are too complicated for me ;-).

**Comment by tjayrush** [comment]
Great idea. I think this makes sense. In the README (not the help text from the command line), I can put some notes about these other modes and refer them to better documentation (which does not exist).

**Comment by tjayrush** [comment]
I hid the -l, -o and -r options to simplify the interface. I added them to the 'hidden' option issue #238 to keep track of them.

For the mutually exclusive options (-b|-d and -e|-i) I made a note on the help screen. I totally agree that the options should look as you noted, but the amount of effort it would take to do is not worth it right now.

Please close this issue.

**Comment by crodnun** [comment]
OK reviewed and closed following Thomas request
