### ISSUE TITLE
At ethslurp when doing search by dates and none record found, missing message saying the same

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#298]
If we run:

 ./ethslurp --dates:20170721:20170721 0x63c8c29af409bd31ec7ddeea58ff14f21e8980b0

We obtain:

ethslurp argc: 3 [1:--dates:20170721:20170721] [2:0x63c8c29af409bd31ec7ddeea58ff14f21e8980b0] 
ethslurp --dates:20170721:20170721 0x63c8c29af409bd31ec7ddeea58ff14f21e8980b0 
Processing: --dates:20170721:20170721 0x63c8c29af409bd31ec7ddeea58ff14f21e8980b0
        Slurping 0x63c8c29af409bd31ec7ddeea58ff14f21e8980b0

We do not inform user that "none record was found at this range", it quits silently

**Comment by tjayrush** [comment]
This first time I ran this test (the address was not in the cache), I got this message:

<pre>Thomass-iMac:build jrush$ ethslurp --dates:20170721:20170721 0x63c8c29af409bd31ec7ddeea58ff14f21e8980b0
Processing: --dates:20170721:20170721 0x63c8c29af409bd31ec7ddeea58ff14f21e8980b0
	Slurping 0x63c8c29af409bd31ec7ddeea58ff14f21e8980b0
	Slurping new transactions from blockchain...
	Downloaded 2 potentially new transactions.
	Download contains blocks from 4186279 to 4186301
	Loaded 2 total records in 0.145000 seconds
	Filter passed 0 visible records of 2 in 0.000999928 seconds
	Exported 0 records in 0 seconds
</pre>

The next time I ran it (it was not in the cache), I got this message:

<pre>
Thomass-iMac:build jrush$ ethslurp --dates:20170721:20170721 0x63c8c29af409bd31ec7ddeea58ff14f21e8980b0
Processing: --dates:20170721:20170721 0x63c8c29af409bd31ec7ddeea58ff14f21e8980b0
	Slurping 0x63c8c29af409bd31ec7ddeea58ff14f21e8980b0
	Slurping new transactions from blockchain...
	No transactions were found for address '0x63c8c29af409bd31ec7ddeea58ff14f21e8980b0'.
</pre>

**Comment by tjayrush** [comment]
I looked into this a bit further, and there is definitely something wrong here. This test case ("ethslurp_single_date_range") has been giving me trouble. Sometimes it reports that it found transactions, other times it reports no. The above report is from the command line, but there is a problem here somewhere.

**Comment by crodnun** [comment]
OK Thomas,

For this I struggled a bit to find the best solution and have implemented the following.

1) cmake allows us to set some environment variables before running a given test

I added this part at src/apps/ethslurp/CMakeLists.txt (just next to the test you requested):

# For the previous test case - set CACHE_ADDR at environment, this way we can clean the cache before running it
set_property(TEST ethslurp_single_date_range PROPERTY ENVIRONMENT "CACHE_ADDR=0x63c8c29af409bd31ec7ddeea58ff14f21e8980b0")

This way we pass (using the environment) the address whose cache files we want to delete at a given test.

2) The second modification is done at testCheck.py script. The script we use for all the tests we run,

    It reads this environment variable and clears the cache files for requested address. does nothing if it is not set.

I think that it is the best solution we can do now, and minimizes the impact on your current release. I did not want to spoil current work with big changes and consider that it is an smart solution for our purposes.

Let me know your thoughts regarding the same. Everything is pushed now.

**Comment by tjayrush** [comment]
I ran the test case four times, and it passed each time. Previously, it would fail intermittently, but usually at least once or twice out of ten. Since I can't really think of any other reason why it was failing, and it appeared to be failing because of the cache, and this removes the file from the cache, I am going to close this. If the issue comes back, I will write a brand new bug and reference this one.
