### ISSUE TITLE
whenBlock starts the search with any arbitrary block value (not validated)

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#318]
If we run

./whenBlock 0x01     ------------------------  Notice here I put hex value - it considers it the 0 block
whenBlock argc: 2 [1:0x01] 
whenBlock 0x01 

        block #0 : 1438269960 : 2015-07-30 15:26:00 UTC

If we run 

./whenBlock 1ppppppp          ------------------ arbitrary string, only picks the 1 and ignores the rest
whenBlock argc: 2 [1:1ppppppp] 
whenBlock 1ppppppp 

        block #1 : 1438269988 : 2015-07-30 15:26:28 UTC

Seems that input value is not validated

**Comment by tjayrush** [comment]
This refers to test case whenBlock_invalid_block_1 (https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/test/gold/tools/whenBlock/whenBlock_invalid_block_1.txt) and (https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/test/gold/tools/whenBlock/whenBlock_invalid_block_2.txt).

**Comment by tjayrush** [comment]
I fixed this and updated the gold test cases. Please close this once I push my changes.

**Comment by crodnun** [comment]
Verified hex format search and assumed that it works this way for non-numeric strings. Closed
