### ISSUE TITLE
WhenBlock unexpected message with out of range block value

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#319]
If we run:

 ./whenBlock 400000000000000000000000

whenBlock argc: 2 [1:400000000000000000000000] 
whenBlock 400000000000000000000000 

  Please supply either a JSON formatted date or a blockNumber. Quitting...

  Usage:    whenBlock [-a|-l|-v|-h] date / block  
  Purpose:  Finds the nearest block before the JSON-formatted date, or the nearest date before the given block.
             
  Where:    
        date / block          one of the special values listed below or YYYY-MM-DD-[HH[:MM[:SS]]] or a blockNumber (required)
        -a  (--alone)         show the found block or found date unadorned (useful for scripting)
        -l  (--list)          list special blocks timestamps and dates
        -v  (--verbose)       set verbose level. Either -v, --verbose or -v:n where 'n' is level
        -h  (--help)          display this help screen

  Powered by QuickBlocks

------------------------------------------------------------

I expected here the out of range message to tell us that the limit we can use, like this:

./whenBlock 40000000000000000
whenBlock argc: 2 [1:40000000000000000] 
whenBlock 40000000000000000 

  Block number (40000000000000000) must be less than latest block: 2683207

  Usage:    whenBlock [-a|-l|-v|-h] date / block  
  Purpose:  Finds the nearest block before the JSON-formatted date, or the nearest date before the given block.
             
  Where:    
        date / block          one of the special values listed below or YYYY-MM-DD-[HH[:MM[:SS]]] or a blockNumber (required)
        -a  (--alone)         show the found block or found date unadorned (useful for scripting)
        -l  (--list)          list special blocks timestamps and dates
        -v  (--verbose)       set verbose level. Either -v, --verbose or -v:n where 'n' is level
        -h  (--help)          display this help screen

  Powered by QuickBlocks

**Comment by tjayrush** [comment]
I agree. I fixed this. The test case is updated. Please close it once I push my change.

**Comment by crodnun** [comment]
Verified the fix. Closing
