### ISSUE TITLE
whenBlock starts with an invalid option and reports an strange error

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#320]
If we run this tricky command:

./whenBlock 0-0

It seems to start and reports the following error that as a user I can not understand:

----------------------------------------------------------------------

whenBlock argc: 2 [1:0-0] 
whenBlock 0-0 

  Could not open the mini-block database: /home/carlos/.quickBlocks/cache/miniBlocks.bin.

  Usage:    whenBlock [-a|-l|-v|-h] date / block  
  Purpose:  Finds the nearest block before the JSON-formatted date, or the nearest date before the given block.
             
  Where:    
        date / block          one of the special values listed below or YYYY-MM-DD-[HH[:MM[:SS]]] or a blockNumber (required)
        -a  (--alone)         show the found block or found date unadorned (useful for scripting)
        -l  (--list)          list special blocks timestamps and dates
        -v  (--verbose)       set verbose level. Either -v, --verbose or -v:n where 'n' is level
        -h  (--help)          display this help screen

  Powered by QuickBlocks

**Comment by tjayrush** [comment]
The program interprets any argument that does not start with a dash as either a block number or a date. It interprets dates as any string that contains a dash or a colon, but does not start with a dash.

The message now reports that an invalid date was specified. Any reasonable user will understand what's going on and will correct this input. This may be closed.

**Comment by crodnun** [comment]
Verified that we now report it as invalid date. Closing
