### ISSUE TITLE
whenBlock displays help when block is not downloaded yet

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#321]
If we run:

./whenBlock 5000000  (notice that my blockchain contains now around 3000000 blocks)

We obtain the right errror message but it shows again the help (maybe this is not required because we are using the command correctly, with the message should be enough)

---------------------------------------------------------------------------------------------------------

whenBlock argc: 2 [1:5000000] 
whenBlock 5000000 

  Block number (5000000) must be less than latest block: 2683211

  Usage:    whenBlock [-a|-l|-v|-h] date / block  
  Purpose:  Finds the nearest block before the JSON-formatted date, or the nearest date before the given block.
             
  Where:    
        date / block          one of the special values listed below or YYYY-MM-DD-[HH[:MM[:SS]]] or a blockNumber (required)
        -a  (--alone)         show the found block or found date unadorned (useful for scripting)
        -l  (--list)          list special blocks timestamps and dates
        -v  (--verbose)       set verbose level. Either -v, --verbose or -v:n where 'n' is level
        -h  (--help)          display this help screen

  Powered by QuickBlocks

**Comment by tjayrush** [comment]
Agreed. I fixed this. Please close it once I push my change. The test case was updated.

**Comment by crodnun** [comment]
Verified and closing issue
