### ISSUE TITLE
whenBlock help should be improved a bit

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#322]
this part:
-----------------------------------------------------------------------------------------------------------------
Purpose:  Finds the nearest block before the JSON-formatted date, or the nearest date before the given block.
------------------------------------------------------------------------------------------------------------------

Should say that we can search for special blocks that can be obtained with the -l command
 

The same happens here at this part of the help:

-------------------------------------------------------------------------------------------------------------------
 date / block          one of the special values listed below or YYYY-MM-DD-[HH[:MM[:SS]]] or a blockNumber (required)
------------------------------------------------------------------------------------------------------------------

We say "one of the special values listed below".... where?  as first time user I felt a bit confused till I understood this.

**Comment by tjayrush** [comment]
Help now reports the list of special blocks. You should be able to close this.

**Comment by crodnun** [comment]
I do not see any improvement at help :-(, we keep telling users that there is an special list below, but I can not see it .

carlos@ubuntu-4gb-fra1-01:~/quickblocks/bin$ ./whenBlock -h
whenBlock argc: 2 [1:-h] 
whenBlock -h 

  Usage:    whenBlock [-a|-l|-v|-h] date / block  
  Purpose:  Finds the nearest block prior to a JSON-formatted date, or the nearest date prior to
           the given block. Alternatively, search for one of the special blocks listed below.
             
  Where:    
        date / block          one of the special values listed below or YYYY-MM-DD-[HH[:MM[:SS]]] or a blockNumber (required)
        -a  (--alone)         show the found block or found date unadorned (useful for scripting)
        -l  (--list)          list special blocks timestamps and dates
        -v  (--verbose)       set verbose level. Either -v, --verbose or -v:n where 'n' is level
        -h  (--help)          display this help screen

  Powered by QuickBlocks

**Comment by tjayrush** [comment]
I forgot to turn the feature on. It should be fixed now.

**Comment by crodnun** [comment]
Ok help improved and tested
