### ISSUE TITLE
whenBlock search by date seems broken

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#323]
When I run this (following the command help):

./whenBlock 2017-03-02 

We obtain this strange error. Notice that I am using the date returned for block 0.

I could not make it work with any date, most of the times it returns this error
-------------------------------------------------------------------------------------------------------------------

whenBlock argc: 2 [1:2017-03-02] 
whenBlock 2017-03-02 

  Could not open the mini-block database: /home/carlos/.quickBlocks/cache/miniBlocks.bin.

  Usage:    whenBlock [-a|-l|-v|-h] date / block  
  Purpose:  Finds the nearest block before the JSON-formatted date, or the nearest date before the given block.
             
  Where:    
        date / block          one of the special values listed below or YYYY-MM-DD-[HH[:MM[:SS]]] or a blockNumber (required)
        -a  (--alone)         show the found block or found date unadorned (useful for scripting)
        -l  (--list)          list special blocks timestamps and dates
        -v  (--verbose)       set verbose level. Either -v, --verbose or -v:n where 'n' is level
        -h  (--help)          display this help screen

  Powered by QuickBlocks

**Comment by tjayrush** [comment]
The miniBlock database only exists if one is running the 'monitor' mode tools which are the "private" part that we discussed elsewhere. For the time being, for release 0.2.0, I turned off the ability to search by date. I delayed this issue, closed it, and noted it in issue #226. Once 0.2.0 is finished, I will re-open this issue. Once you've read this, please simply re-assign it to me.

**Comment by tjayrush** [comment]
Fixed by printing a message if run without miniBlock database since it's not feasible to run without it. Too slow.
