### ISSUE TITLE
WhenBlock mixed search criteria (passing both date and block) seems use only block

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#324]
When we run:

./whenBlock 2015-07-31 1000

It only takes into account the block number and does the search.

As a user I expected here the date search or error out telling me that it is incorrect command.

**Comment by tjayrush** [comment]
I changed this so it should now accept any number (and in any combination) blocks, dates, or special names. You should be able to close this.

**Comment by crodnun** [comment]
OK closing now per Thomas request (search by date could not be tested locally)

**Comment by tjayrush** [comment]
The date issue is tracked in #323
