### ISSUE TITLE
whenBlock list command accepts more parameters silently

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#326]
If we run:

arlos@ubuntu-4gb-fra1-01:~/quickblocks/bin$ ./whenBlock -l 213
whenBlock argc: 3 [1:-l] [2:213] 
whenBlock -l 213 

        Special blocks:
          first                0
          iceage          200000
          homestead      1150000
          daofund        1428756
          daohack        1718497
          daofork        1920000
          tangerine      2463000
          spurious       2675000
          stateclear     2718436
carlos@ubuntu-4gb-fra1-01:~/quickblocks/bin$ ./whenBlock -l 2015-07-31
whenBlock argc: 3 [1:-l] [2:2015-07-31] 
whenBlock -l 2015-07-31 

        Special blocks:
          first                0
          iceage          200000
          homestead      1150000
          daofund        1428756
          daohack        1718497
          daofork        1920000
          tangerine      2463000
          spurious       2675000
          stateclear     2718436

WE could validate the parameters here to not get confused and understand clearly that list option goes alone.

**Comment by tjayrush** [comment]
I changed this so the --list option goes alone. If any other commands are on the line, it complains and quits without running.

**Comment by crodnun** [comment]
Verified, fixed now. Closing issue
