### ISSUE TITLE
whereBlock many doubts and confusing tool

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#328]
I could not understand how this command works, so maybe I need some clarifications from your side.

1)First question is how the blocks are inserted in cache, how we can insert them there to then do the search.

2)Second question, is the -b option used and how? I try this 2 combinations and offer me the same result (notice that I pass block directly or with -b option)

carlos@ubuntu-4gb-fra1-01:~/quickblocks/bin$ ./whereBlock  1
whereBlock argc: 2 [1:1] 
whereBlock 1 
The block 1 was not found in the cache.

carlos@ubuntu-4gb-fra1-01:~/quickblocks/bin$ ./whereBlock -b 1
whereBlock argc: 3 [1:-b] [2:1] 
whereBlock -b 1 
The block 1 was not found in the cache.

Seems that -b option can be removed, tool executes the same passing it or not.

**Comment by tjayrush** [comment]
This also touches on the whole purpose of QuickBlocks--being a minimal impact, fully decentralized caching mechanism for the blockchain node. The tool's primary purpose is to check if blocks are being added into the cache. The tool is not really ready for prime time (as you've noticed).

The 'private' part of the system (the part you have not seen) puts blocks in the cache if (and only if) the end user asks for a block during the creation of a per-account transaction index. So:

    getBlock 10010101

should not put the block in the cache, but

    monitor --address 0x1210210931093109310....

should put all the blocks that involved that address into the block.

The tools never put blocks into the cache (unless they use a hidden command line called --forceCache which is not documented). The 'monitors' do put blocks into the cache (so they are fast retrieval the next time they are needed.) In this way, the impact on the end user's machine is minimized.

I removed the -b option and made 'block[s]' a required option. The tool should probably be moved into the 'private' area of the code, but it hardly seems worth it.

Please close this issue. I will revisit it after version 0.2.0 is released.

**Comment by crodnun** [comment]
-b option no longer available: confirmed
Closing per Thomas request
