### ISSUE TITLE
whereBlock starts the search without passing any block (assumes 0 block)

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#329]
If we run this:

 ./whereBlock -a -b   (notice that we do not pass any block value here)

whereBlock argc: 3 [1:-a] [2:-b] 
whereBlock -a -b 
The block 0 was not found in the cache.

--------------------------------------------------------

The search reports that block 0 was not found ?? I did not pass it :-)

**Comment by tjayrush** [comment]
Fixed with latest push. Also improved the help text a bit. Please close this.

**Comment by crodnun** [comment]
Confirmed, closed
