### ISSUE TITLE
isContract returns false result when ethscan.io says it is a contract

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#331]
If we run this:

./isContract 0x0117ef7fdb2a5814dff83c50fb799741904cd28d

isContract argc: 2 [1:0x0117ef7fdb2a5814dff83c50fb799741904cd28d] 
isContract 0x0117ef7fdb2a5814dff83c50fb799741904cd28d 
isContract(0x0117ef7fdb2a5814dff83c50fb799741904cd28d): false

If we do the search of this address at ethscan.io it is considered a contract 

![image](https://user-images.githubusercontent.com/16229970/29957461-e08e05c6-8eed-11e7-9a34-38caca54d321.png)

**Comment by tjayrush** [comment]
The contract was first created at block 3369107. My guess is that your node is not synced past this block. Do `getBlock latest` to tell how far you are synced. When I run this on my computer (which is fully synced), it reports 'true'.

**Comment by crodnun** [comment]
Understood, my fault here. Closing
