### ISSUE TITLE
isContract doubt regarding the limit of input addresses list (number of addresses supported)

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#332]
Is there any limit in the number of input addresses we can search?

I tried with up to 20 :-) and it works but as a tester if there is a limit I would like to see what happens at this limit.

**Comment by tjayrush** [comment]
The maximum number is 100, which I think will be many more than anyone will ever use, and if not, it's okay. I am also interested in what happens when it goes over that limit, but I don't think we want to add a test case. It will take a very long time to run, I think. Please do a test, but do not add a test case. Report what happens here, then close this bug.

**Comment by crodnun** [comment]
Tested with this long input and reports the limit supported correctly:

carlos@ubuntu-4gb-fra1-01:~/quickblocks/bin$ ./isContract 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d  0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d




isContract argc: 111 [1:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [2:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [3:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [4:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [5:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [6:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [7:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [8:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [9:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [10:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [11:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [12:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [13:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [14:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [15:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [16:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [17:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [18:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [19:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [20:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [21:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [22:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [23:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [24:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [25:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [26:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [27:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [28:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [29:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [30:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [31:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [32:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [33:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [34:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [35:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [36:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [37:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [38:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [39:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [40:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [41:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [42:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [43:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [44:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [45:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [46:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [47:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [48:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [49:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [50:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [51:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [52:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [53:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [54:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [55:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [56:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [57:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [58:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [59:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [60:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [61:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [62:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [63:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [64:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [65:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [66:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [67:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [68:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [69:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [70:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [71:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [72:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [73:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [74:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [75:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [76:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [77:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [78:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [79:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [80:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [81:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [82:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [83:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [84:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [85:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [86:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [87:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [88:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [89:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [90:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [91:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [92:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [93:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [94:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [95:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [96:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [97:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [98:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [99:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [100:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [101:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [102:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [103:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [104:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [105:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [106:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [107:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [108:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [109:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] [110:0x26c4e381ffbdc825be9b986c3ba40525f0771e8d] 
isContract 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 0x26c4e381ffbdc825be9b986c3ba40525f0771e8d 

  You may query at most 100 addresses. Quitting...

  Usage:    isContract [-d|-n|-v|-h] addr[s]  
  Purpose:  Returns 'true' or 'false' if the given address(es) holds byte code (optionally displays the code).
             
  Where:    
        addr[s]               a space-separated list of one or more Ethereum addresses (required)
        -d  (--display)       display the byte code at the address(es)
        -n  (--nodiff)        return 'true' if (exactly) two Ethereum addresses have identical code
        -v  (--verbose)       set verbose level. Either -v, --verbose or -v:n where 'n' is level
        -h  (--help)          display this help screen

  Powered by QuickBlocks
