### ISSUE TITLE
isContract does not validates input address format

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#333]
When we run:

./isContract 0xrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr

isContract argc: 2 [1:0xrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr] 
isContract 0xrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr 
isContract(0xrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr): false

It reports that it is not a contract, but I expected to find here an error of "invalid address"

We should validate this because it is not an address and can not report a false here.

**Comment by tjayrush** [comment]
This should be fixed. You may close it if you agree.

**Comment by crodnun** [comment]
Verified, now return:

./isContract 0xrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
isContract argc: 2 [1:0xrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr] 
isContract 0xrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr 

  0xrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr does not appear to be a valid Ethereum address.

**Comment by tjayrush** [comment]
Nice catch. This was true of all tools, so that's a great find.
