### ISSUE TITLE
whenBlock returns the block #0 when an special date is not downloaded yet

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#339]
NOTE: my blockchain is now around block #2696160. so "stateclear" and "latest" are not available yet.

When I try to get some special blocks/dates (that are not downloaded yet at my environment), tool returns the block #0. I expected here to see the same behaviour than passing a block not downloaded yet:

Something like:

The block number you requested (xxxxxxx) is after the latest block (TESTING). Quitting... 

But instead this message, the block #0 is returned:

./whenBlock stateclear
whenBlock argc: 2 [1:stateclear] 
whenBlock stateclear 

        block #0 (stateclear) : 1438269960 : 2015-07-30 15:26:00 UTC

./whenBlock latest
^HwhenBlock argc: 2 [1:latest] 
whenBlock latest 

        block #0 (latest) : 1438269960 : 2015-07-30 15:26:00 UTC

**Comment by tjayrush** [comment]
This should be fixed now.

**Comment by crodnun** [comment]
OK, this is issue is fixed now, but when executing the list command at my side, it displays this:


whenBlock -l 

        Special Blocks:
          first                0
          iceage          200000
          homestead      1150000
          daofund        1428756
          daohack        1718497
          daofork        1920000
          tangerine      2463000
          spurious       2675000
          latest                               >>>>>>>>>>>>>>>>>>> Here no value??? and before stateclear??
          stateclear     2718436

What does this mean? latest block is before stateclear and has no block #value

Let me know if we should open a new issue for this or just has an explanation.

**Comment by tjayrush** [comment]
Fixed. 'latest' should always be last (in both -l mode and -h). If the node is still syncing, it should add the word "(syncing)" to the display so the user understand why it's not fully sorted (latest is earlier than other blocks).

**Comment by tjayrush** [comment]
Excellent issue, by the way.

**Comment by crodnun** [comment]
OK, now "latest" is displayed at  the right position, but could not see any "syncing" word at help, neither at -l option. I only see this output at my side:


carlos@ubuntu-4gb-fra1-01:~/quickblocks/bin$ ./whenBlock -l
whenBlock argc: 2 [1:-l] 
whenBlock -l 

        Special Blocks:
          first                0
          iceage          200000
          homestead      1150000
          daofund        1428756
          daohack        1718497
          daofork        1920000
          tangerine      2463000
          spurious       2675000
          stateclear     2718436
          latest                                ======= empty ====== my node is running parity at block #2702577


Let me know if this is OK for now and I will close this issue, if you want to add "syncing" somewhere, you should fix something somewhere because I can not see this word at my side.

**Comment by tjayrush** [comment]
Can you please copy in the contents of your ~/.quickBlocks/quickBlocks.toml file here?

**Comment by tjayrush** [comment]
I cannot reproduce this. I am going to delay it for now #293

**Comment by tjayrush** [comment]
Please close this. I will re-open it later.

**Comment by crodnun** [comment]
OK, closing per Thomas request
