### ISSUE TITLE
Pending to see how we can enable/disable fallback to infura/other

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#342]
We have defined 3 levels where we can get the information from:

1) Local cache
2) Local node
3) Remote fallback (infura, etc,..)

We need a way to disable/enable the remote fallback feature and test what happens.

**Comment by tjayrush** [comment]
The fallback is now off by default. If you run the test cases like this:

     FALLBACK=infura make test

then it will fallback to infura. Infura should be the only valid value.

I will not document this because I want to think about how it should work (perhaps infura should be the default fallback, perhaps it shouldn't, but then the error message should probably instruct the user of the existence of the fallback.

In any case, please play around with this. I'm not sure it quite works as you might expect, but see what happens and report here. Thanks.

**Comment by crodnun** [comment]
OK, the following behaviour has been confirmed.

Setup: Ubuntu node without parity and without cache.

-----------------------------------------------------------------------------------------------------------------
SCENARIO-1:  Default behaviour, it is not able to find a source to obtain the information. None fallback is defined yet, no parity, no quickblocks
-----------------------------------------------------------------------------------------------------------------

carlos@ubuntu16:~/installation_qb/bin$ ./whenBlock -l

	Warning: The request to the Ethereum node resulted in
	following error message: Couldn't connect to server.
	It is impossible for QuickBlocks to proceed. Quitting...

-----------------------------------------------------------------------------------------------------------------
SCENARIO-2:  Setting a fallback, data is retrieved correctly
-----------------------------------------------------------------------------------------------------------------
carlos@ubuntu16:~/installation_qb/bin$ export FALLBACK=infura
carlos@ubuntu16:~/installation_qb/bin$ ./whenBlock -l

	Special Blocks:
	  first                0
	  iceage          200000
	  homestead      1150000
	  daofund        1428756
	  daohack        1718497
	  daofork        1920000
	  tangerine      2463000
	  spurious       2675000
	  stateclear     2718436
	  latest         4240723


Let me know if this is what you expected, and we can close this issue. I will test all the combinations at the other issue already opened

**Comment by tjayrush** [comment]
This is working as it's coded, so, yes, this is how I expect it to work. Is this how it should work ultimately? I'm not sure. Let's follow through with the rest of the scenarios (as you suggest) so we can see how all the different combinations work.

I'm leaning towards a default like this, but with a much better message saying something like. "You have QuickBlocks properly installed, now you have to make some choices...."

    Infura vs. local node
    Location of QuickBlocks cache
    API keys for etherscan (ethslurp), poloniex (prices), infura (long term)

**What I don't want to do:**
   force my users to sync parity --tracing on --pruning archive
   use Infura without warning users that they are running in a less-than perfect security situtation
**What I do want to do:**
   give my users access to the full blockchain data
   make it easy and quick

**Comment by crodnun** [comment]
This issue can be closed. Let me kno if I can do it. It was just a reminder to clarify how fallback works

**Comment by tjayrush** [comment]
I think this can be closed. The fallback doesn't quite work as I want it to, but I will create a separate issue for myself for that.

**Comment by crodnun** [comment]
OK, closing.
