### ISSUE TITLE
Convert a few shell scripts to python

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#343]
The files in ./tools/scripts are bash shell scripts. I think it should be pretty easy to change them to python. They are getCode and ethgoog. You may rename them to getCode.py and ethgoog.py if you like.

**Comment by crodnun** [comment]
Hi Thomas, 

Under src/tools/scripts/ you have now the script ethgoog.py that should do the same that you did previously with bash. Please double test it at your side. I tested it under Windows and Linux.

Pending points:

1) Remove the bash version at repository whenever you want.  I let you decide what to do with it.
2) I could not find the other script you mention above:  getCode ??? Could you give me more information about the same. Seems not present at the repository, maybe renamed?

**Comment by tjayrush** [comment]
The `getCode` command was an experiment from a while ago. You can ignore it. I never posted it to the repo. You can forget about this.

I also removed old code (and pushed) changes to the ./src/tools folder. The only thing in this folder is now python scripts. I also updated the CMakeLists.txt file (after pulling your changes).

Finally, I tested ethgoog.py and it works as it should.

There are no other scripts.
