### ISSUE TITLE
Compilation of the project broken due to minor error

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#350]
Hi Thomas,

I found this minor error today, that stops the compilation at my side:

[ 17%] Building CXX object libs/etherlib/CMakeFiles/ether.dir/pricequote.cpp.o
/home/carlos/quickblocks/src/libs/etherlib/pricequote.cpp: In function â€˜bool qblocks::loadPriceData(qblocks::CPriceQuoteArray&, bool, qblocks::SFString&, SFUint32)â€™:
/home/carlos/quickblocks/src/libs/etherlib/pricequote.cpp:307:13: error: this â€˜ifâ€™ clause does not guard... [-Werror=misleading-indentation]
             if (verbose < 2)
             ^~
/home/carlos/quickblocks/src/libs/etherlib/pricequote.cpp:308:49: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the â€˜ifâ€™
                 cerr << "Retrieving data...\r"; cerr.flush();
                                                 ^~~~
cc1plus: all warnings being treated as errors
libs/etherlib/CMakeFiles/ether.dir/build.make:230: recipe for target 'libs/etherlib/CMakeFiles/ether.dir/pricequote.cpp.o' failed
make[2]: *** [libs/etherlib/CMakeFiles/ether.dir/pricequote.cpp.o] Error 1
CMakeFiles/Makefile2:231: recipe for target 'libs/etherlib/CMakeFiles/ether.dir/all' failed
make[1]: *** [libs/etherlib/CMakeFiles/ether.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

I fixed it manually at my side just to go ahead, but keep it in mind at your side

**Comment by tjayrush** [comment]
Sorry. This is another one of those Mac vs Ubuntu warnings issue. I will try to figure out how to turn this warning on explicitly on Mac. I pushed a fix to the pricequote.cpp file. You may close this. I opened #353 to track the warning issue.

**Comment by crodnun** [comment]
Confirmed the fix, closing
