### ISSUE TITLE
Segregating 'special' test cases from 'regular' test cases

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#351]
On a new machine, I run Parity with --warp option (without running --tracing on --pruning archive as we require). --warp is a lightweight mode for Parity that many people will be running.

The following test cases fail:

| Tool | Reason for failure |
|------|-------------------|
| ethslurp | this makes sense because on first install there is no Etherscan API |
| getTrace | this makes sense because of no `--tracing on` options, which provides the trace |
| getBalance | this makes sense since no `--pruning archive`, which provides balances |
| whenBlock | this makes sense since there is no fullBlockIndex.bin file without 'monitor' code |
| cacheMan | this makes sense since there is no fullBlockIndex.bin file without 'monitor' code |

None of the test cases failed for un-expected reasons, so this is good. I only create this issue to document for future testers why some test cases may fail on first install.

Is there some way to create a 'make test-all' which would run these test cases only? The regular `make test` wouldn't run these cases that we know will fail on first install.

Also, with a `make test-all` target we could push some of the slower tests cases into this target to speed up the running of the tests on regular operation.

****** 
**UPSHOT:** Can we add a 'make test-all' target into which we can move some of the test cases that we know will fail (such as getTrace and getBalance)?

**Comment by crodnun** [comment]
OK, understood now, will study a bit the choices we have at cmake to accomplish this, will play around with the same.

**Comment by tjayrush** [comment]
Note that you cannot start Parity with --warp or it will kill your --tracing...etc. I think it might do this without warning, so you have to be careful. Or, it may not even start with --warp.  Upshot: don't start parity with anything but the --tracing on --pruning archive so you don't have to restart the sync.

**Comment by crodnun** [comment]
Hi Thomas, I have uploaded at root CMakeLists.txt the target you requested, at the end of the file you can see these new lines (as usual feel free to re-arrange it, I just supply you the tools you can use for the same).


# To run only specific tests, we define a target that only runs those tests with an specific LABEL "-L"
# we must tag them with this label first at the place where they are defined
# Something like this:   
# set_property(TEST test1 PROPERTY LABELS SPECIAL_TEST)
add_custom_target(test-all COMMAND ${CMAKE_CTEST_COMMAND} -L "SPECIAL_TEST")


The key here is that you can define a target, I put here the requested one "test-all" but you can assign any value and this target is linked against the Ctest tool (${CMAKE_CTEST_COMMAND}) ---- This means run all tests ---- but with the "-L" option you filter only those tests labelled with the value you specify as parameter (I use here "SPECIAL_TEST" as dummy value).

This target will run now only those tests labelled as "SPECIAL_TEST", if you run it now, no test is labelled yet, so it will show you this message:

$ make test-all
No tests were found!!!
Built target test-all

So what is pending now is just to label those tests you want to include at this target. This is done just after the test definition, setting the label property of the test like follows:

set_property(TEST my_test_x PROPERTY LABELS my_test_tag)

Example:

set_property(TEST ethslurp_verbose_options_long PROPERTY LABELS SPECIAL_TEST)

Doing this, this test will be included automatically at the "make test-all" target, of course it will be run also with "make test".

Hope this helps, let me know if this is what you were looking for.

**Comment by tjayrush** [comment]
This is close to what I was looking for, but not quite.

When you say above "...of course it will be run also with 'make test'...." that is the part that is not quite right.

I wanted a "make test" which runs all tests **except** the special ones, and "make test-all" which runs all tests **including** the special ones.

The reason I want this is so I can tag the slower tests to only run on demand (i.e. with "make test-all"). This will increase the "turnaround time" for making changes specific tools/apps. As it is now, it takes a couple of minutes to run all 1,000 tests, and this will only get slower over time as we add new tests.

As an example, I would tag most of the 40-50 tests for ethName and only leave seven or eight representative tests run by default. For example, there's no need to test --verbose and -v every time I make a one line change in some other tool. Same applies to ethprice, ethslurp, whenBlock, etc.

For the "parity specific" tests mentioned above, I could use another tag such as "make parity-tests".

Does that make sense?

**Comment by crodnun** [comment]
OK, I have changed the behaviour then,

We keep having both targets "test" and "test-all".

I needed to add a couple of functions to run "special/slow tests".

At root CMakelists.txt I added the function:

# Runs specials tests that are only run with "make test-all"
function(run_the_special_test testPath goldPath testName testExe) # Optional argv4 with command parameters
        set(TEST_FILE "${testPath}/${testName}.txt")
        set(GOLD_FILE "${goldPath}/${testName}.txt")
        if (NOT ${ARGV4} STREQUAL "" )
        # In ARGV4 we receive the parameters to be passed to testExe  (optional)
        add_test(NAME ${testName} COMMAND ${TEST_CHECK} ${testExe} ${ARGN} ${TEST_FILE} ${GOLD_FILE} CONFIGURATIONS test_all)
        else()
                add_test(NAME ${testName} COMMAND ${TEST_CHECK} ${testExe} ${TEST_FILE} ${GOLD_FILE} CONFIGURATIONS test_all)
        endif()
endfunction(run_the_special_test)

It is a clone of the old one, but passing a CONFIGURATIONS parameter to define those tests that we want to skip from "make test".

Every time we want to skip a test from "make test" we should invoke this function instead the old one.

I also added an example at src/tools/ethName/CMakeLists.txt of how you can use it everywhere, you need to do 3 things:

1) First define a wrapper function for the special tests:

function(run_special_test testName)
     run_the_special_test(${TEST_PATH} ${GOLD_PATH} ${testName} ${TEST_EXE} ${ARGN})
endfunction(run_special_test) 


2) Invoke those tests you want to run "as special" with this function. I did an example, feel free to undo it.

#run_test("ethName_README"                            "-th")
run_special_test("ethName_README"                            "-th")

3) Add the  "test-all" target at the CMakeLists.txt (this is handy if you want to run this target individually at each directory, if you prefer only to run from root, you can skip this step)


# test-all target
# To run only specific tests we define a test configuration named "test_all"
add_custom_target(test-all ALL COMMAND ${CMAKE_CTEST_COMMAND} -C test_all)


At this example if you run:

1) make test   (will skip the special one I modified)
2) make test-all (will include all the tests)

Hope this is better now, anyways let me know any change or improvement required. Everything is pushed now.

**Comment by tjayrush** [comment]
This is exactly what I wanted. I think I might rename 'special' to something else (such as 'full') but otherwise it's perfect. I will take care of identifying the 'full' tests (slow ones and ones that don't work on machines without a running Ethereum node).

I'm going to close this, because the issue is solved, but I opened #365 to track it.

**Comment by tjayrush** [comment]
I am re-opening this one because when I uncomment [this line](https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/apps/ethprice/CMakeLists.txt#L31), the build breaks. With the line commented out, `make` builds the code, `make test` runs only test cases specified with `run_test` and `make test-all` runs all tests (as we want it to).

With this line uncommented `make` runs the tests cases for some reason. I tried to figure it out, but I can't. There are other examples (all commented out) in ethslurp, ethName, isContract, etc.

**Comment by crodnun** [comment]
Yes, this is done with the parameter "ALL", when this parameter is present it forces to run the test-all every time we run any target. 

We should remove this dependency if we do not want to run it every time we execute "make", you have an example at root CMakeLists.txt. 

I have changed it and pushed to repository this minor change "removing the ALL parameter".

Double check if now works as you expected

**Comment by tjayrush** [comment]
I see what I did. I copied the line from the top-level CMakeLists.txt instead of from the example on in ./tools/ethName/CMakeLists.txt. I didn't notice the little word 'ALL' which was in the top-level, but not the example. This fixed it. Closing. Thanks.

**Comment by tjayrush** [comment]
I apologize. I am going to re-open this. There's a problem.

Right now--it works almost as I expected. With the recent change (removing 'ALL' from the test-all targets in the child CMakeLists.txt files), it now works correctly by running only the subset of the test cases if I do this command:

    make test

But now, when I run this command:

    make test-all

it does correctly run every test (both run_test and run_special_test). The trouble is that after the running of the full test suite is completed, it re-runs all the test cases in each individual subfolder that has the `test-all` target in it's local CMakeList.txt file.

So, for example, `make test` runs every test correct. `make test-all` runs every test including all the `run_special_test` cases in ./apps/ethslurp/CMakeLists.txt, but then, once it's finished, it re-runs all the test cases in `ethslurp`. (It also re-runs isContract, ethName, ethprice, etc.--all the one with a specialized test-all target).

Note that it only does this when I run `make test-all` from the top level folder. If I change into ./build/apps/ethslurp and run `make test-all` it runs every test, but only once.

**Comment by tjayrush** [comment]
Note that I also changed the title from "Running against Parity --warp" since the issue has changed.

**Comment by crodnun** [comment]
OK I reviewed the cmake documentation and we should remove this line from root CMakeLists.txt,

## add_custom_target(test-all COMMAND ${CMAKE_CTEST_COMMAND} -C test_all)  

only keep the target at those directories where we want to have special tests.

Test again removing the line from root CMakeLists.txt and let me know the results, I did not modify it just to not collide with your changes.

**Comment by tjayrush** [comment]
Okay. Now we have a different behaviour--but--to be honest, I think I like this better.

Now, if I run `make test` it runs the speedy tests (as it did before), but when I run `make test-all` it runs only the run_special_test test cases. I actually like this, because now I can do this:

    make
    make test
    make test-all

and it will run each test case once and only once. Even though `make test-all` doesn't test all (it should probably be called test-special), I want to close this issue. I think it's good enough for now. Thanks for all your work on this.
