### ISSUE TITLE
Installation instructions on project home page

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#355]
In [this file](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/README.md), after the first `QuickBlocks` section but before the `More Quickly` section insert instructions on how to download, build and install the project. You may remove the file ~/quickBlocks/BUILD.md so as to not confuse people.

**Comment by crodnun** [comment]
Added a first draft with basic installation instructions. BUILD.md removed from repository.

We have there the basic information, I think that accurate, but should test it again against Droplets to confirm that every user following these instructions will success.

Of course, I let you decide the format and cosmetic details of how you would like to organize this information, I would prefer to create separated README_xxx.md files for each platform. Maybe putting them somewhere under docs folder and creating links from root README.md. 

For the moment it contains all the information we have so far, let me know your feedback about the same.

**Comment by tjayrush** [comment]
I see that BUILD.md was removed.

Yes. I agree about different README_xxx.md files for each platform and less detail (i.e. just links) on the main page. I think ./src/other/install would be a likely place to put the files.

Is there instructions for installing on Mac?

Please go ahead and create these other files, etc. I will fix up the formatting / design later after the structure is in place.

**Comment by tjayrush** [comment]
I merged develop into master and then went to Ubuntu and deleted everything related to QuickBlocks (~/quickBlocks source, ~/.quickBlocks config, /usr/local/qblocks SDK). I then followed the instructions in UBUNTU_BUILD.md and ran `FALLBACK=infura make test`.

The build was flawless. Every test passed (except those few that are known to fail due to no API key, or no trace support).

It's starting to look good. Thanks for all your excellent work.

When you consider this issue to be finished, you may close it. I created #364 to track the issue of editing for clarity and consistency.

**Comment by crodnun** [comment]
OK, let's close this for now and open new ones when any enhacement required over current version
