### ISSUE TITLE
Build step seems broken with latest changes at cmake

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#361]
Downloading develop branch from scratch and doing the initial steps:

mkdir build
cd build
cmake ../src

It stops here (seems not finding some test files added recently):

-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ======== LOOKING FOR PYTHON ========================
-- Found PythonInterp: /usr/bin/python (found version "2.7.13") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "2.7.13") 
-- ======== LOOKING FOR CURL ========================
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.52.1") 
CMake Error at libs/test-libs/utillib/jsonTest/CMakeLists.txt:28 (file):
  file COPY cannot find
  "/home/carlos/quickblocks/src/libs/test-libs/utillib/jsonTest/tests/blocks.json".

CMake Error at libs/test-libs/utillib/jsonTest/CMakeLists.txt:29 (file):
  file COPY cannot find
  "/home/carlos/quickblocks/src/libs/test-libs/utillib/jsonTest/tests/traces.json".

CMake Error at libs/test-libs/utillib/jsonTest/CMakeLists.txt:30 (file):
  file COPY cannot find
  "/home/carlos/quickblocks/src/libs/test-libs/utillib/jsonTest/tests/random.json".

-- Configuring incomplete, errors occurred!
See also "/home/carlos/quickblocks/build/CMakeFiles/CMakeOutput.log".

**Comment by tjayrush** [comment]
First thing I did this morning was look at what I did last night and realized I had broken the build again. Damn .gitignore. Sorry.... It should be fixed now.

**Comment by crodnun** [comment]
OK, solved and closing issue
