### ISSUE TITLE
FreeBSD compilation errors out

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#368]
I thought that this was solved before, anyways I let you decide what to do here. It is a minor issue related with deprecated functions and the -Werror flag we added lately

Compilation errors out with this message under FreeBSD:

$ make
Scanning dependencies of target util
[  0%] Building CXX object libs/utillib/CMakeFiles/util.dir/basenode.cpp.o
In file included from /usr/home/test/quickBlocks/src/libs/utillib/basenode.cpp:8:
In file included from /usr/home/test/quickBlocks/src/libs/utillib/basetypes.h:26:
/usr/include/sys/timeb.h:42:2: error: "this file includes <sys/timeb.h> which is deprecated" [-Werror,-W#warnings]
#warning "this file includes <sys/timeb.h> which is deprecated"
 ^
1 error generated.
*** Error code 1

Stop.
make[2]: stopped in /usr/home/test/quickBlocks/build
*** Error code 1

Stop.
make[1]: stopped in /usr/home/test/quickBlocks/build
*** Error code 1

Stop.
make: stopped in /usr/home/test/quickBlocks/build

**Comment by tjayrush** [comment]
I think this should be fixed on FreeBSD, but I am not able to test it as I have no FreeBSD computer. Please confirm and close if fixed. Pretty simple change referenced above.

**Comment by crodnun** [comment]
OK Thomas, it improved a bit, compilation reachs now the 9% and errors out at this point:

[  9%] Building CXX object libs/utillib/CMakeFiles/util.dir/sfos.cpp.o
/usr/home/test/quickBlocks/src/libs/utillib/sfos.cpp:276:16: error: taking the max of unsigned zero and a value is always equal to the other value [-Werror,-Wmax-unsigned-zero]
        return max(0U, count);
               ^~~ ~~
/usr/home/test/quickBlocks/src/libs/utillib/sfos.cpp:276:16: note: remove call to max function and unsigned zero argument
        return max(0U, count);
               ^~~ ~~~
1 error generated.
*** Error code 1

**Comment by crodnun** [comment]
If you can share a public key I can let you do ssh into "test" user to debug this part in the FreeBSD node I hired for this. These days as you know will be complicated for me (with the festivities) and you can debug quickly other compilation warnings there.

Steps I do normally:

1) ssh as "test" user into the host
2) Go to $HOME/quickBlocks directory
3) Update the git locally (git pull)
4) And then the stuff we do everywhere:

    cd build
    cmake ../src
    make     (and here fix any raised issue, probably all minor warning issues treated as errors)

Let me know if this works for you and I can configure ssh access to the freeBSD node.

**Comment by tjayrush** [comment]
I'll be back in my office in about an hour I'll send you an email through Upwork with my public

--------
Thomas Jay Rush
jrush@greathill.com

**Comment by tjayrush** [comment]
Sent public key via upWork site (I think!)

**Comment by crodnun** [comment]
OK, configured your key at FreeBSD server. Feel free to play around with it, fixing the picky warnings it generates.  I tested it today but seems that warnings are not fixed now.

Shared at Upwork the IP addresses of the servers and the Linux users you have to use.

**Comment by tjayrush** [comment]
### For the Ubuntu box (the warp box):

I logged in to the `carlos` user. The build worked perfectly. Some of the tests fail, but I'm going to ignore these for now. As an aside, can you please run this command on that machine? `apt-get install colordiff` It's a pretty useful tool that I use to compare tests with the `diffTest` command in ./quickBlocks/bin.

### For the FreeBSD box:

Here's what I found:

1. The build seems to work fine for the library code (ignoring a few warnings/errors which were fixed and pushed).
2. The first app/tool that tries to link to the libraries fails to link. If I remove the -O2 option from [this line](https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/CMakeLists.txt#L47) in the ./src/CMakeLists.txt file, and then it links.

Can you figure out either (a) how to get the benefit of the optimizers on every platform, or (b) how to isolate the setting for FreeBSD. I'm not willing to forgo the use of the optimizer flag on other platforms (the project is called 'quick' after all), so if we can't isolate it on FreeBSD, then I would argue for dropping support for FreeBSD.

**Comment by crodnun** [comment]
OK Thomas, colordiff installed at Ethereum node.

Regarding FreeBSD I let you here what I did:

1) I tried to compile it (using latest version, after git pull)
2) It errors out at this point, when linking:

[ 49%] Linking CXX executable /usr/home/test/quickBlocks/bin/test/jsonTest
/usr/home/test/quickBlocks/src/libs/libether.a(node.cpp.o): In function `qblocks::etherlib_init(qblocks::SFString const&)':
/usr/home/test/quickBlocks/src/libs/etherlib/node.cpp:(.text+0x1d1): undefined reference to `qblocks::CAbi::registerClass()'
/usr/home/test/quickBlocks/src/libs/etherlib/node.cpp:(.text+0x1d6): undefined reference to `qblocks::CFunction::registerClass()'
/usr/home/test/quickBlocks/src/libs/etherlib/node.cpp:(.text+0x1db): undefined reference to `qblocks::CParameter::registerClass()'
/usr/home/test/quickBlocks/src/libs/etherlib/node.cpp:(.text+0x1ea): undefined reference to `qblocks::CNameValue::registerClass()'
/usr/home/test/quickBlocks/src/libs/libether.a(transaction.cpp.o): In function `qblocks::CTransaction::finishParse()':

This just means that the etherlib is using symbols from the abilib, so at BASE_LIBS you need to change their order,  put "abi"  after "ether" at root CMakeLists.txt (where we define the BASE_LIBS variable).

I did not modify it, only tested it locally and after this change, the project builds perfectly at FreeBSD. I do not know if this was your error, but at my side doing this change I am able to compile everything.

Do this change and try again at FreeBSD server, use it on your own.

**Comment by tjayrush** [comment]
Totally understand, however, now it fails on Ubuntu. When I first looked at this, I thought "Why is it in that order?" A more natural order would be what you changed it to. But I did remember switching that order because it didn't build on Ubuntu.

The trouble is that there's a circular dependency. One library calls into the other--and at the same exact time the other library calls into the first.

Please close this as the build issue itself is solved, and I created a new issue to track the circular dependency: #371.

**Comment by tjayrush** [comment]
By the way. Building on FreeBSD and running with 

    FALLBACK=infura make test

only fails on these tests:

	224 - getTrace_00 (Failed)
	225 - getTrace_01 (Failed)
	226 - getTrace_02 (Failed)
	227 - getTrace_25 (Failed)
	228 - getTrace_26 (Failed)
	229 - getTrace_27 (Failed)
	230 - getTrace_28 (Failed)
	320 - cacheMan_list (Failed)
	321 - cacheMan_check (Failed)

which are totally understandable (and I will be changing these to test_all.  Soon--on all platforms--we should be able to run `make test` and get no failed tests. (Although the data will be wrong in some cases because the node isn't delivering the data--but that's a different issue).

You may close this.

**Comment by tjayrush** [comment]
From now on--for all platforms other than Mac--when you're testing try to test on `master` and use `make tests`. After tonight, all tests should pass.

**Comment by tjayrush** [comment]
You may close this. I removed the circular dependency and pushed the changes to both develop and master. It should build now on both Ubuntu and FreeBSD.

If you do `FALLBACK=infura make test` it will pass all the tests on FreeBSD and all the tests on Ubuntu (if you stop running parity --warp).

**Comment by crodnun** [comment]
OK confirmed that "FALLBACK=infura make test" works at both environments (Ubuntu and FreeBSD) using master branch. 

100% tests passed, 0 tests failed out of 309

No issues at compilation.
