### ISSUE TITLE
Review README.md file, there are some links no longer available

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#383]
Reviewing the README.md at main github page, seems that we have broken links (links pointing to nothing now).

I fixed one, but if would be recommended to review it line by line, as a final user I hate when instructions are not accurate or they have broken links, it gives a bad image so I think that I could help you with this. I created the build part but noticed now that some of the descriptions you have there, describing the wonderful quickblocks is, can have broken/old links that are outdated now.

If you agree I can take care of this.

**Comment by tjayrush** [comment]
There's a lot of work to do on the readmes. You're welcome to either fix them directly or write issues about any of them. Thanks. I haven't gotten around to it.

**Comment by crodnun** [comment]
Ok, I will review it. At least the content, links and consistency. I will not modify the format just ensure that any user feels confortable when arrives to the repository and does not close the page frustrated...lol. I assign this to me.

**Comment by crodnun** [comment]
Fixed a few README.md with broken links that now should point to the right directory/destination.
Done at development branch, feel free to merge these changes to master one when suitable and close the issue.

**Comment by tjayrush** [comment]
I see that you fixed the links. Thanks. You may close this. I'm tracking the READMEs in #364

**Comment by crodnun** [comment]
OK closing now per Thomas request
