### ISSUE TITLE
Small change to build

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#394]
Edit ./src/other/install/qb_config.cmake to include these commands

        cp -fp  ./bin/makeClass                         ~/.quickBlocks/makeClass
        cp -fp  ./src/apps/makeClass/templates/blank*   ~/.quickBlocks/makeClass
        cp -fp  ./src/apps/grabABI/templates            ~/.quickBlocks/grabABI
        cp -fp  ./src/apps/grabABI/known_contracts      ~/.quickBlocks/cache/abi
        cp -fpR ./src/apps/chifra/templates             ~/.quickBlocks/chifra

Resulting folders should look like this:

        ~/.quickBlocks/cache
        ~/.quickBlocks/cache/abis
        ~/.quickBlocks/cache/abis/0xTokenLib.json
        ~/.quickBlocks/cache/abis/0xWalletLib.json

        ~/.quickBlocks/chifra
        ~/.quickBlocks/chifra/config.toml
        ~/.quickBlocks/chifra/README.md

        ~/.quickBlocks/grabABI
        ~/.quickBlocks/grabABI/accounting.cpp
        ~/.quickBlocks/grabABI/CMakeLists.txt
        ~/.quickBlocks/grabABI/debug.cpp
        ~/.quickBlocks/grabABI/debug.h
        ~/.quickBlocks/grabABI/display.cpp
        ~/.quickBlocks/grabABI/docs
        ~/.quickBlocks/grabABI/docs/README.tmpl.md
        ~/.quickBlocks/grabABI/main.cpp
        ~/.quickBlocks/grabABI/options.cpp
        ~/.quickBlocks/grabABI/parselib
        ~/.quickBlocks/grabABI/parselib/CMakeLists.txt
        ~/.quickBlocks/grabABI/parselib/parselib.cpp
        ~/.quickBlocks/grabABI/processing.cpp
        ~/.quickBlocks/grabABI/processing.h
        ~/.quickBlocks/grabABI/rebuild

        ~/.quickBlocks/makeClass
        ~/.quickBlocks/makeClass/blank.cpp
        ~/.quickBlocks/makeClass/blank.h
        ~/.quickBlocks/makeClass/makeClass

        ~/.quickBlocks/quickBlocks.toml

**Comment by crodnun** [comment]
Small doubt here Thomas, what is the exact name for this directory:

~/.quickBlocks/cache/abis

or 

~/.quickBlocks/cache/abi

**Comment by tjayrush** [comment]
'abis' is correct. This works as I wish. Closing.
