### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#396]
I'm mostly done with what I'm working on for #226, so I'm ready to create the 0.2.0 release. Can you help me understand how to do that?'

Before we do that though, I want to test the remaining tools in ./src/tools that we haven't tested yet.

When you've completed test cases for a particular tool, post your issues for that tool, and then move on to the next tool (don't wait until the end of the week as I said earlier today). Once you post your issues, I will fix those bugs. 

Let's shoot for making the release this week or next. If you can do the testing and post your issues as they become available that would be great.

**Comment by crodnun** [comment]
OK Thomas, first round passed to all the available tools, let me know when the rest are ready to be tested or stable to do the same, at least the first round.

**Comment by tjayrush** [comment]
This is an example of what I want to do: https://github.com/tomusdrw/rust-web3/releases/tag/v0.1.0

**Comment by tjayrush** [comment]
As we move towards the release, I want to go one by one with each tool. I am finalizing the README files. I want you to use the README file as the 100% ground truth as to what the tool should do and make one final pass on the testing to make sure the tests, the tool, and the README are all in sync.

**Comment by tjayrush** [comment]
https://github.com/Great-Hill-Corporation/quickBlocks/releases/tag/v0.2.0-alpha
