### ISSUE TITLE
Compilation seems broken with latest updates at develop branch

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#400]
Hi Thomas, 

After latest updates, the compilation fails at the parity Ubuntu server at 78%:

[ 79%] Building CXX object tools/getAccounts/CMakeFiles/getAccounts.dir/getAccounts.cpp.o
/home/carlos/quickBlocks/src/tools/getAccounts/getAccounts.cpp: In function â€˜int main(int, const char**)â€™:
/home/carlos/quickBlocks/src/tools/getAccounts/getAccounts.cpp:30:13: error: â€˜balâ€™ was not declared in this scope
         if (bal > 0 || !options.noZero) {
             ^~~
/home/carlos/quickBlocks/src/tools/getAccounts/getAccounts.cpp:30:33: error: â€˜class COptionsâ€™ has no member named â€˜noZeroâ€™
         if (bal > 0 || !options.noZero) {
                                 ^~~~~~
/home/carlos/quickBlocks/src/tools/getAccounts/getAccounts.cpp:31:25: error: â€˜class COptionsâ€™ has no member named â€˜asDataâ€™
             if (options.asData) {
                         ^~~~~~
/home/carlos/quickBlocks/src/tools/getAccounts/getAccounts.cpp:32:25: error: â€˜blockâ€™ was not declared in this scope
                 cout << block << "\t" << token << "\t" << holder << "\t" << sBal << "\n";
                         ^~~~~
/home/carlos/quickBlocks/src/tools/getAccounts/getAccounts.cpp:32:42: error: â€˜tokenâ€™ was not declared in this scope
                 cout << block << "\t" << token << "\t" << holder << "\t" << sBal << "\n";
                                          ^~~~~
/home/carlos/quickBlocks/src/tools/getAccounts/getAccounts.cpp:32:59: error: â€˜holderâ€™ was not declared in this scope
                 cout << block << "\t" << token << "\t" << holder << "\t" << sBal << "\n";
                                                           ^~~~~~
/home/carlos/quickBlocks/src/tools/getAccounts/getAccounts.cpp:32:77: error: â€˜sBalâ€™ was not declared in this scope
                 cout << block << "\t" << token << "\t" << holder << "\t" << sBal << "\n";
                                                                             ^~~~
/home/carlos/quickBlocks/src/tools/getAccounts/getAccounts.cpp:34:65: error: â€˜holderâ€™ was not declared in this scope
                 cout << "    Balance for account " << cGreen << holder << cOff;
                                                                 ^~~~~~
/home/carlos/quickBlocks/src/tools/getAccounts/getAccounts.cpp:35:50: error: â€˜blockâ€™ was not declared in this scope
                 cout << " at block " << cTeal << block << cOff;
                                                  ^~~~~
/home/carlos/quickBlocks/src/tools/getAccounts/getAccounts.cpp:36:46: error: â€˜sBalâ€™ was not declared in this scope
                 cout << " is " << cYellow << sBal << cOff << "\n";
                                              ^~~~
/home/carlos/quickBlocks/src/tools/getAccounts/getAccounts.cpp:43:1: error: expected â€˜}â€™ at end of input
 }

**Comment by tjayrush** [comment]
It should build now. Sorry about that.

**Comment by crodnun** [comment]
Fixed and confirmed. Closing
