### ISSUE TITLE
getReceipt: Not ready for testing

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#401]
Hi Thomas, at Upwork you told me that I could test the following tools:

getBalance, getLogs, getReceipt, getTrans, getTokenBal

But when I run getReceipt, I obtain the following output:

-------------------------------------------------------------------------------------------------
 The getReceipt tool is not yet implemented. Quitting...

  Usage:    quickBlocks [-v|-h]  
  Where:    
        -v  (--verbose)       set verbose level. Either -v, --verbose or -v:n where 'n' is level
        -h  (--help)          display this help screen

  Powered by QuickBlocks

-------------------------------------------------------------------------------------------------

It is not ready yet, isn't it?

**Comment by tjayrush** [comment]
My bad. No, it's not ready yet. I will work on this today.

**Comment by tjayrush** [comment]
This tool is now ready to test in full. This issue may be closed.

**Comment by crodnun** [comment]
First test round passed. Closing this
