### ISSUE TITLE
getBalance does not check the block format, it assumes that is block 0

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#403]
When I run this command (notice that I used here an invalid block number=ttttt):

./getBalance 0x6f46cf5569aefa1acc1009290c8e043747172d89 tttttt

It returns balance for block 0 and I expected and error:

getBalance argc: 3 [1:0x6f46cf5569aefa1acc1009290c8e043747172d89] [2:tttttt] 
getBalance 0x6f46cf5569aefa1acc1009290c8e043747172d89 tttttt 
Balance of address 0x6f46cf5569aefa1acc1009290c8e043747172d89 at block 0: 0

We should check that block is a valid value and error out.

**Comment by tjayrush** [comment]
This should be fixed with the next push.

**Comment by crodnun** [comment]
OK, reviewed and fixed now. Closed
