### ISSUE TITLE
getBalance at out of range scenarios (block higher than max available) says 0 balance

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#405]
When a user requests balance for a block that is above the latest we have, it returns 0 balance that is a bit confusing.

At my node I have now 4130000 blocks and I executed the following (balance at a block that is out of the range I have so far, 6000000 in this case):

./getBalance 0x6f46cf5569aefa1acc1009290c8e043747172d89 6000000

getBalance argc: 3 [1:0x6f46cf5569aefa1acc1009290c8e043747172d89] [2:6000000] 
getBalance 0x6f46cf5569aefa1acc1009290c8e043747172d89 6000000 
Balance of address 0x6f46cf5569aefa1acc1009290c8e043747172d89 at block 6000000: 0

This is a bit confusing, because the user does not detect that is an "out of range" block, just sees that it has 0 balance, we should check here for the max limit available and inform the user that:

1) Or it is an error, we do not have this information yet
2) Is out of range, sorry we can only supply latest block available

**Comment by tjayrush** [comment]
This should be fixed with the next push.

**Comment by crodnun** [comment]
Tested and fixed now. Closing
