### ISSUE TITLE
Strange command line behaviour at getBalance --noZero

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#407]
When I run this command:

./getBalance  -n 0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359 

I get this:

0xf27daff52c38b2c373ad2b9392652ddf433303c4 3000
getBalance argc: 5 [1:-n] [2:0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359] [3:0xf27daff52c38b2c373ad2b9392652ddf433303c4] [4:3000] 
getBalance -n 0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359 0xf27daff52c38b2c373ad2b9392652ddf433303c4 3000 

But the prompt presents this line afterwards, seems that it continues writing at command line or something is not working properly when managing stdout/stderr, it flushes the last line after finishing

carlos@ubuntu-4gb-fra1-01:~/quickBlocks/bin$ d2b9392652ddf433303c4 at block 3000  

Normally the commands finish and do the flush before the prompt but this time it seems that it does afterwards, I expected here an empty prompt but seems that it flushes later the content. Seems that something is not managed properly at output/error.

**Comment by tjayrush** [comment]
When I run the above command from the command line, I get:

    (develop)@./build:jrush>$ getBalance -n 0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359
        Balance for account 0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359 at block 4320601 is 2906480783625980069700
    (develop)@./build:jrush>$

**Comment by crodnun** [comment]
OK, do now ask me why, but seems fixed now. So forget this.
