### ISSUE TITLE
getLogs: Not ready for testing

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#408]
Hi Thomas, 

Does it make sense to test the getLogs tool?

When we run the help command it says this (note: This tool is incomplete):

Usage:    getLogs [-f|-a|-v|-h] < hash | bn.transID | bh.transID | address >
            **-- note: This tool is incomplete.**
  
  Purpose:  Retrieve logs from an Ethereum transaction using either QuickBlocks or a running node.
            --note: 'hash' and 'blockHash' must start with '0x'.  
  Where:    
        hash                  one or more hashes of Ethereum transactions, or
        bn.transID            blockNumber.transactionID of one or more Ethereum transactions, or
        bh.transID            blockHash.transactionID of one or more Ethereum transactions, or
        address               if --address, then an Ethereum address
        -f  (--fromNode)      retrieve the transaction from the running node (from QuickBlocks otherwise)
        -a  (--address)       retrieve all logs (from node) given a list of one or more Ethereum addresses
        -v  (--verbose)       set verbose level. Either -v, --verbose or -v:n where 'n' is level
        -h  (--help)          display this help screen

  Powered by QuickBlocks

**Comment by tjayrush** [comment]
This tool is now ready to test in full. This issue may be closed.

**Comment by crodnun** [comment]
OK, now it is ready for testing and tests passed. Does not make sense to keep this opened.
