### ISSUE TITLE
getTrans: accepts invalid parameters and returns a result

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#409]
When I run  the tool passing ".whatever" parameter we obtain results (I expected and error after parameter validation, it is not any of these formats:  hash|bn.transID|bh.transID

$ ./getTrans .whatever

getTrans argc: 2 [1:.whatever] 
getTrans .whatever 
{
  "hash": "0x0",
  "blockHash": "0x0",
  "blockNumber": 0,
  "transactionIndex": 0,
  "nonce": 0,
  "timestamp": 0,
  "from": "0x0",
  "to": "0x0",
  "value": 0,
  "gas": 0,
  "gasPrice": 0,
  "cumulativeGasUsed": 0,
  "gasUsed": 0
}

**Comment by tjayrush** [comment]
This is fixed. getTrans is now ready to test in full. You may close this issue.

**Comment by crodnun** [comment]
Confirmed and closing
