### ISSUE TITLE
getTrans: Improvement at getTrans

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#410]
Hi Thomas we should indicate at the tool help that we support multiple queries on the same command, for example the following command is valid and returns both results:

./getTrans 4000000.4 4000000.3

As a final user, and only using the help, I do not know this and should be described somehow to know that we can request many transactions at the same time, using combined options

**Comment by tjayrush** [comment]
The getTrans tool is now ready to test in full. This issue may be closed.

**Comment by tjayrush** [comment]
The getTrans tool is now ready to test in full. This issue may be closed.

**Comment by crodnun** [comment]
Confirmed and closing
