### ISSUE TITLE
getTrans: -f option seems not operative

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#411]
When I run the help for this tool, I see that it has the following options:

./getTrans -h
getTrans argc: 2 [1:-h] 
getTrans -h 

  Usage:    getTrans [-f|-t|-v|-h] <hash|bn.transID|bh.transID>  
  Purpose:  Retrieve an Ethereum transaction from either QuickBlocks or a running node.
            --note: 'hash' and 'blockHash' must start with '0x'.  
  Where:    
        hash                  one or more hashes of Ethereum transactions, or
        bn.transID            blockNumber.transactionID of one or more Ethereum transactions, or
        bh.transID            blockHash.transactionID of one or more Ethereum transactions
        -f  (--fromNode)      retrieve the transaction from the running node (from QuickBlocks otherwise)
        -t  (--trace)         return the trace of the transaction in addition to regular details
        -v  (--verbose)       set verbose level. Either -v, --verbose or -v:n where 'n' is level
        -h  (--help)          display this help screen

  Powered by QuickBlocks

--------------------------------------------------------------------------

When I try to run it with the -f option, it returns an error , saying that this option is not supported:

/getTrans -f 4000000.4
getTrans argc: 3 [1:-f] [2:4000000.4] 
getTrans -f 4000000.4 

  Invalid option: -f

  Usage:    getTrans [-f|-t|-v|-h] <hash|bn.transID|bh.transID>  
  Purpose:  Retrieve an Ethereum transaction from either QuickBlocks or a running node.
            --note: 'hash' and 'blockHash' must start with '0x'.  
  Where:    
        hash                  one or more hashes of Ethereum transactions, or
        bn.transID            blockNumber.transactionID of one or more Ethereum transactions, or
        bh.transID            blockHash.transactionID of one or more Ethereum transactions
        -f  (--fromNode)      retrieve the transaction from the running node (from QuickBlocks otherwise)
        -t  (--trace)         return the trace of the transaction in addition to regular details
        -v  (--verbose)       set verbose level. Either -v, --verbose or -v:n where 'n' is level
        -h  (--help)          display this help screen

  Powered by QuickBlocks

Seems that this option is not operative, neither the long version :  --fromNode

**Comment by tjayrush** [comment]
The getTrans tool is now ready to test in full. This issue may be closed.

**Comment by crodnun** [comment]
OK, option no longer available, so does the issue. Closing

**Comment by tjayrush** [comment]
The --fromNode options was changed to --raw to be the same as other tools. It now works, I think.
