### ISSUE TITLE
Doubt regarding getTokenBal

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#413]
When we run the command, it shows a kind of "header" in one of the first lines

This line contains this (what is its purpose???):

block   token   holder  token balance

Example:

getTokenBal 0xd26114cd6EE289AccF82350c8d8487fedB8A0C07 0x5e44c3e467a49c9ca0296a9f130fc433041aaa28 0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98 
getTokenBal argc: 4 [1:0xd26114cd6EE289AccF82350c8d8487fedB8A0C07] [2:0x5e44c3e467a49c9ca0296a9f130fc433041aaa28] [3:0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98] 
getTokenBal 0xd26114cd6EE289AccF82350c8d8487fedB8A0C07 0x5e44c3e467a49c9ca0296a9f130fc433041aaa28 0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98 
block   token   holder  token balance

**Comment by tjayrush** [comment]
This should be fixed with the next push. The header should only appear when using the --data option.

**Comment by crodnun** [comment]
OK, confirmed. Closed
