### ISSUE TITLE
getTokenBal should detect out of range blocks

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#414]
When we run the command using a block that is out of range (5 millions in this case)

./getTokenBal 0xd26114cd6EE289AccF82350c8d8487fedB8A0C07 0x5e44c3e467a49c9ca0296a9f130fc433041aaa28 0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98 5000000

We obtain a result saying that it has 0 balance, 

 For token contract: 0xd26114cd6EE289AccF82350c8d8487fedB8A0C07
    Balance for account 0x5e44c3e467a49c9ca0296a9f130fc433041aaa28 at block 5000000 is 0
    Balance for account 0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98 at block 5000000 is 0

We should error-out or say that max current block is X

**Comment by tjayrush** [comment]
This should be fixed with the next push.

**Comment by crodnun** [comment]
Confirmed. Closed
