### ISSUE TITLE
getToken balance --nonZero option combined with ByAcct

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#415]
When I combine both options, it removes the balance from those contracts where it has 0 balance, 

Is this correct? 

I run this example:

getTokenBal 0xb9e7f8568e08d5659f5d29c4997173d84cdf2607 0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98  0x6b65353ac052f6c3a0c9688911b078bd025d6ab3 0xa25d04fa348f107428708ba19c95d1c79b3744bf --byAcct 4151262 4151261 4151260 --noZero

We request information from different contracts for a give account, we obtain as output the following:

   Balance of token contract 0xb9e7f8568e08d5659f5d29c4997173d84cdf2607 at block 4151262 is 435000000000000000000000
    Balance of token contract 0xb9e7f8568e08d5659f5d29c4997173d84cdf2607 at block 4151261 is 435000000000000000000000
    Balance of token contract 0xb9e7f8568e08d5659f5d29c4997173d84cdf2607 at block 4151260 is 435000000000000000000000
    Balance of token contract 0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98 at block 4151262
    Balance of token contract 0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98 at block 4151261
    Balance of token contract 0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98 at block 4151260
    Balance of token contract 0x6b65353ac052f6c3a0c9688911b078bd025d6ab3 at block 4151262
    Balance of token contract 0x6b65353ac052f6c3a0c9688911b078bd025d6ab3 at block 4151261
    Balance of token contract 0x6b65353ac052f6c3a0c9688911b078bd025d6ab3 at block 4151260

We do not display the latest part of the line for those contracts with 0 balance, 

makes sense to use both options combined? should we remove the line completely? Displaying only the first part of the line seems confusing,

**Comment by tjayrush** [comment]
This is an amazing find. Great job. Subtle, weird bug, but it should be fixed with the latest push.

**Comment by crodnun** [comment]
OK fixed now. Closed
