### ISSUE TITLE
getTokenBal: Temporal field in test causes failure

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#416]
When we run the test case with out-of-range block we obtain this message:

Block 6000000 is later than the last valid block 4165754. Quitting...

Could we make the field "4165754" dynamic like with did at other test scenarios? Otherwise better to remove this test case, let me know your thoughts.

**Comment by tjayrush** [comment]
This should be fixed.

**Comment by crodnun** [comment]
Confirmed and closing
