### ISSUE TITLE
Finalize testing for tools

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#418]
I think I've finished my work on the following tools:

- [x] [getBalance](https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/tools/getBalance/README.md)
- [x] [getTokenBal](https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/tools/getTokenBal/README.md)
- [x] [ethName](https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/tools/ethName/README.md)
- [x] [getAccounts](https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/tools/getAccounts/README.md)
- [x] [isContract](https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/tools/isContract/README.md)
- [x] [whenBlock](https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/tools/whenBlock/README.md) 
- [x] [whereBlock](https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/tools/whereBlock/README.md)
- Block related interfaces:
   - [x] [getBlock](https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/tools/getBlock/README.md)
   - [x] [getBloom](https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/tools/getBloom/README.md)
- Transaction related interfaces:
   - [x] [getLogs](https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/tools/getLogs/README.md)
   - [ ] [getReceipt](https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/tools/getReceipt/README.md)
   - [x] [getTrace](https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/tools/getTrace/README.md)
   - [ ] [getTrans](https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/tools/getTrans/README.md)

Please "finalize" them by doing this:

1. Clear the caches, so you start with a fresh install
2. Read the README file,
3. Note any typos, misspellings, or confusing text,
4. If a tool has similar function to other tools, please try to make sure they are consistent (for example, getBalance and getTokenBal have similar interfaces),
5. Confirm that existing tests cover the function described in the README,
6. Confirm that the test behaves as described in the README.

Once all bugs written against a tool are closed, please check the above box. Once you check these boxes, I will try to keep my hands off of a tool until we release 0.2.0.

**Comment by crodnun** [comment]
First group of tools tested and pending to close some issues before checking the boxes.

 etBalance
 getTokenBal
 ethName
 getAccounts
 isContract
 whereBlock

All them reviewed, some of them with pending issues. Let me know when the rest are available to test.

**Comment by tjayrush** [comment]
I think I'm ready to close this one. It may not be fully true, but I feel like we've at least looked at all the tools. Once 0.2.0 is release, I will be re-opening hundreds of issues, so this won't matter any longer. You may close this unless you think there's something yet to be done.

**Comment by crodnun** [comment]
Closing,  we have finalize the first round of tests for the moment.
