### ISSUE TITLE
Environment variable required before "make test"

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#423]
All our test cases assume that TEST_MODE is set. Both you and me have this variable set at environment but a final user will not have it in place and the test cases will fail.

I think that we should include a step somewhere to reflect this, if you unset this variable, most of the tests will fail, because the gold files we compare with, include debugging lines like the following:

getBalance argc: 3 [1:$doa] [2:0x12]
getBalance $doa 0x12
...
...
...
...

**Comment by tjayrush** [comment]
TEST_MODE set in the `make test` command. Will users be running test cases without using `make test`? [Here](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/tools/scripts/testCheck.py#L127)

**Comment by crodnun** [comment]
OK, closing. I did a test using ctest directly instead of "make test". Let's skip this for the moment, as you stated.
