### ISSUE TITLE
We can not use getBalance against the "special" block "first"

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#424]
If we run:

./getBalance "0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359" first 

It errors out as follows:

getBalance argc: 3 [1:0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359] [2:first] 
getBalance 0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359 first 

  'first' does not appear to be a valid block. Quitting...

  Usage:    getBalance [-l|-n|-d|-v|-h] <address> [address...] [block...]  
  Purpose:  Retrieve the balance (in wei) for one or more addresses at the given block(s).
             
  Where:    
        address_list          one or more addresses (0x...) from which to retrieve balances (required)
        block_list            optional list of one or more blocks at which to report balances, see notes
        -l  (--list fn)       an alternative way to specify an address_list; place one address per line in the file 'fn'
        -n  (--noZero)        suppress the display of zero balance accounts
        -d  (--data)          render results as tab delimited data
        -v  (--verbose)       set verbose level. Either -v, --verbose or -v:n where 'n' is level
        -h  (--help)          display this help screen

  Powered by QuickBlocks

****# If this is a bug, we should uncomment the test case:

getBalance_special_block_3

At CMakeLists.txt (now commented out)****

**Comment by tjayrush** [comment]
This should be fixed.

**Comment by crodnun** [comment]
OK closing, tested and confirmed the fix.
