### ISSUE TITLE
Doubt regarding ether/dollars options

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#425]
Are they operative?

At getBalance the --ether returns a conversion but --dollars fails after a while trying to connect somewhere?. It says: "Cannot load price data. Quitting."

Are they operative, should we test them? I we add them at help (README.md for getBalance) what is the expected behaviour for getBalance

--ether     |   specify value in ether
--dollars   |   specify value in US dollars

**Comment by tjayrush** [comment]
Is this repeatable? Can you give me steps to repeat it? When I delete the price database (~/.quickBlocks/cache/prices/poloniex.bin)  it simply re-creates it on the fly (as it should) and the test passes. It works for --ether and it also works for --dollars. Please provide explicit instructions to reproduce.

**Comment by crodnun** [comment]
Hi Thomas, 
The root cause probably is that when I install the .quickBlocks folder from scratch using github (cmake + make), it does not generate a folder for "prices" anywhere, so I never have this folder in my server, neither the poloniex.bin.

Steps I did:

1) git pull (at root github directory)
2) cd build
3) cmake ../src
4) make
5) cd $HOME/.quickBlocks/cache
6) ls -ltras  (only names and abis are present)

    total 16
4 drwxrwxr-x 4 carlos carlos 4096 Oct  5 06:41 .
4 drwxrwxr-x 2 carlos carlos 4096 Oct  5 06:41 names
4 drwxrwxr-x 6 carlos carlos 4096 Oct  5 06:41 ..
4 drwxrwxr-x 2 carlos carlos 4096 Oct  5 06:41 abis

5) I run then a getBalance command for dollars (seems to return wei anyways):

 >  getBalance  0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359  4000000 --dollars


getBalance argc: 4 [1:0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359] [2:4000000] [3:--dollars] 
getBalance 0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359 4000000 --dollars 
Balance of address 0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359 at block 4000000: 4098334073083150747787

5) I run then a getBalance this time without --dollars  (seems to return the same):

> getBalance  0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359  4000000 


getBalance argc: 3 [1:0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359] [2:4000000] 
getBalance 0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359 4000000 
Balance of address 0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359 at block 4000000: 4098334073083150747787

**Comment by tjayrush** [comment]
I was able to reproduce pretty easily and fixed this as per the above push. Please close if you agree.

**Comment by crodnun** [comment]
I do not see any improvement after latest pull.

I have done the pull right now and then run the same commands with the same results reported before:

1) With --dollars it returns the wei again:

git pull
cd build
cmake ../src
make (100% OK)
cd ../bin

Using the latest binary generated right now:
1084 -rwxrwxr-x 1 carlos carlos 1107872 Oct  8 17:57 getBalance

./getBalance 0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359 4000000 --dollars

getBalance argc: 4 [1:0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359] [2:4000000] [3:--dollars] 
getBalance 0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359 4000000 --dollars 
Balance of address 0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359 at block 4000000: 4098334073083150747787

I could not see any improvement at this issue, after latest update. is this really updated?


Additional information:

Only when I run once this command using "--ether" seems that it updates the .quickBlocks cache and then I am able to run it with --dollars correctly.

It is strange, but seems that only when running "--ether" we are able to work with all he options (--dollars, --ether, --wei). If we download it from scratch and only use the --dollar option, never is updated the cache/prices folder and never is returned the exact value in dollars.

**Comment by tjayrush** [comment]
I think I know what's going on here. I will update shortly.

**Comment by tjayrush** [comment]
I think this should be fixed now. The trouble is that there was no 'price database' because the folder it lives in was not created. This didn't happen if you had previously run the 'ethprice' tool (as we do in the sequence of 'make test'). This happened because you were starting getBalance without first having run the tests. Very nice find. This kind of bug report gives me comfort that we're really testing this thing well. You should be able to close this now. It works on my ubuntu box.

**Comment by crodnun** [comment]
Perfect, reviewed and now prices folder is created when not present. Closing
