### ISSUE TITLE
getBalance using empty input file (option --file:fn) does not error out

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#426]
If I create an empty file:

> touch empty.txt

and run the following command:

 ./getBalance --file:empty.txt

I obtain:

getBalance argc: 2 [1:--file:empty.txt] 
getBalance --file:empty.txt 

I expected here to error out the same we do when running:

./getBalance         (without parameters)

**Comment by tjayrush** [comment]
Nice find. Weird. It fails correctly if I do `getBalance -f:empty.txt` but it doesn't fail if I do `getBalance --file:empty.txt`. I will comment here when it's fixed.

**Comment by tjayrush** [comment]
Fixed with recent commit. Nice find.

**Comment by crodnun** [comment]
OK confirmed the fix.
