### ISSUE TITLE
ethName README.md improvements and feedback

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#428]
1) What does ENS mean at the first paragraph? maybe a link or reference here could help.

2) If we run the command indicated in the help, as one of the use cases for this tool, it errors out:

ethscan.py `ethName -a DAO`

ERROR: Specify only a single transaction hash, account address, or block number

3)  When we refer to terms we should be consistent everywhere, maybe we can use the same syntax we use at getBalance and getTokenBal, and say "search_term_list" to indicate that it will be a list of terms.

ethName [-a|-c|-o|-l|-m|-s|-v|-h] <search_terms_list>

4)  We should describe that terms are space separated list.

5) The purpose statement says:

Purpose: Find a name given an Ethereum address, or find an address given a name.

but we can search using both :-).

6) Seems not clear for me how we obtain the matching between the names and addreses, I remember that we used a kind of file (names.txt) where we store all this information but how?, maybe a third party? ENS? We should describe a bit more what is the way we can generate this information or at least how we want to do it. If the tools is incomplete we should not recommend to use it for the moment.

7) By the way, at names.txt we have a typo  "seperated" at first line:

#  This is the ethName database. Format records as tab seperated lines with the following format:
#
#      Optional Symbol <tab> Name <tab> Address <tab> Source of the data <tab> Description <newline>
#

**Comment by tjayrush** [comment]
1) What does ENS mean at the first paragraph? maybe a link or reference here could help.

2) If we run the command indicated in the help, as one of the use cases for this tool, it errors out:

ethscan.py `ethName -a DAO`

ERROR: Specify only a single transaction hash, account address, or block number


3)  When we refer to terms we should be consistent everywhere, maybe we can use the same syntax we use at getBalance and getTokenBal, and say "search_term_list" to indicate that it will be a list of terms.

ethName [-a|-c|-o|-l|-m|-s|-v|-h] <search_terms_list>

4)  We should describe that terms are space separated list.

5) The purpose statement says:

Purpose: Find a name given an Ethereum address, or find an address given a name.

but we can search using both :-).

6) Seems not clear for me how we obtain the matching between the names and addreses, I remember that we used a kind of file (names.txt) where we store all this information but how?, maybe a third party? ENS? We should describe a bit more what is the way we can generate this information or at least how we want to do it. If the tools is incomplete we should not recommend to use it for the moment.

7) By the way, at names.txt we have a typo  "seperated" at first line:

> #  This is the ethName database. Format records as tab seperated lines with the following format:

**Comment by tjayrush** [comment]
> 1. What does ENS mean at the first paragraph? maybe a link or reference here could help.

**Comment by tjayrush** [comment]
> 2. If we run the command indicated in the help, as one of the use cases for this tool, it errors out:
> ethscan.py ethName -a DAO
> ERROR: Specify only a single transaction hash, account address, or block number

**Comment by tjayrush** [comment]
> When we refer to terms we should be consistent everywhere, maybe we can use
> the same syntax we use at getBalance and getTokenBal, and say "search_term_list"
> to indicate that it will be a list of terms.
> ethName [-a|-c|-o|-l|-m|-s|-v|-h] <search_terms_list>

**Comment by tjayrush** [comment]
> 4. We should describe that terms are space separated list.

**Comment by tjayrush** [comment]
> 5. The purpose statement says:
>          Purpose: Find a name given an Ethereum address, or find an address given a name.
>  but we can search using both :-).

**Comment by tjayrush** [comment]
> 6. Seems not clear for me how we obtain the matching between the names and addreses, I remember that we used a kind of file (names.txt) where we store all this information but how?, maybe a third party? ENS? We should describe a bit more what is the way we can generate this information or at least how we want to do it. If the tools is incomplete we should not recommend to use it for the moment.

**Comment by tjayrush** [comment]
> By the way, at names.txt we have a typo "seperated" at first line:
> This is the ethName database. Format records as tab seperated lines with the following format:

**Comment by tjayrush** [comment]
I answered each item separately above. I believe this issue may be closed.

**Comment by crodnun** [comment]
OK, closing. Most of them are ready, the rest are postponed by Thomas request
