### ISSUE TITLE
ethName test cases seem that were passed using a different names.txt

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#429]
When I run test cases using a fresh names.txt generated after cmake+make.

I obtain that my descriptions at names.txt differ from those expected at test cases:

Example:

< { "symbol": "QTUM", "name": "Qtum", "addr": "0x9a642d6b3368ddc662ca244badf32cda716005bc", "source": "Etherscan.io", "description": "Build Decentralized Applications that mobile devices" }
---
> { "symbol": "QTUM", "name": "Qtum", "addr": "0x9a642d6b3368ddc662ca244badf32cda716005bc", "source": "Etherscan.io", "description": "Build Decentralized Applications that Simply Work Executable on mobile devices, compatible with major existing blockchain ecosystem" }
7c7

The description seems different comparing the gold test case with the one I obtain now, at my names.txt the description is the longest one, seems it changed.

Any explanation for this? Do we ignore this part?

**Comment by tjayrush** [comment]
You should be able to delete ~/.quickBlocks/cache/names/names.* (i.e. clear the cache), and it should work. I think this is an issue with the cache holding on to data. Regular users should not experience this problem since they won't have a cache.

**Comment by crodnun** [comment]
OK, closing
