### ISSUE TITLE
cmake broken at step 0, missing scripts directory under monitors

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#435]
When executing:

> cd build
> cmake ../src

-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ======== LOOKING FOR PYTHON ========================
-- Found PythonInterp: /usr/bin/python (found version "2.7.13") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "2.7.13") 
-- ======== LOOKING FOR CURL ========================
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.52.1") 
CMake Error at monitors/CMakeLists.txt:15 (add_subdirectory):
  add_subdirectory given source "scripts" which is not an existing directory.

-- Configuring incomplete, errors occurred!
See also "/home/carlos/quickBlocks/build/CMakeFiles/CMakeOutput.log".

--------------------------------------------------------------------------------------------------------------
Seems that you are dealing with some new directories that are not public for me, I fixed it locally just moving the add_directory() statements to the if-clause

--------------------------------------------------------------------------------------------------------------

if(0)
add_subdirectory(cacheMan)
add_subdirectory(scripts)
...
...
endif()

Let me know if this is correct and update when fixed.

**Comment by tjayrush** [comment]
My bad. Just delete that line from the CMake file. Sorry.

**Comment by tjayrush** [comment]
This is fixed. Sorry.

**Comment by crodnun** [comment]
OK, now it is fixed. Closing
