### ISSUE TITLE
Doubt regarding getAccounts

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#436]
When I start from a fresh installation (removed cmpletely .quickBlocks directory) and execute this tool I obtain 3 addresses:

./getAccounts

0x0000000000000000000000000000000000000000
0x0000000000000000000000000000000000000001
0x0000000000000000000000000000000000000002
0x0000000000000000000000000000000000000003

What is their purpose? How I could remove/add them to the node's keystore?

I think that this information is really important at this tool and should be displayed at README.md, as a user I would like to know how this keystore is managed and how we can add/delete addresses there.

**Comment by tjayrush** [comment]
In testing mode, the tool reports on accounts 1,2,3, and 4. In actual use, it will display the actual public keys of the accounts on the user's machine. If the end user runs `getAccounts` on his/her own machine it will report on his/her own keys. Currently, it only lists the public keys.

I agree with you. This could be very useful, but....and I've made this choice on purpose...I don't want to get involved with the keystore. If there's a bug in my code, and I somehow ruin a person's keystore, it would be quite a bad thing. Until I get a little bit further along in the project (and have time to really think about it), I want to stay away from playing around with the keystore.

It's a good suggestion though. I wrote this issue #439, which I 'delayed' to keep track of the thought. You may close this.

**Comment by crodnun** [comment]
Understood, closing now.
