### ISSUE TITLE
getAccounts README.md comments and  general feedback

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#437]
Here you have my comments, after testing and reviewing the next tool "getAccounts".

1) It is not clear for me how you can add/remove addresses to/from node's keystore. Help explained this will be welcome for everybody.

2) When you run it it displays 4 addresses by default, what are they?:
0x0000000000000000000000000000000000000000
0x0000000000000000000000000000000000000001
0x0000000000000000000000000000000000000002
0x0000000000000000000000000000000000000003

3) The commands described at README.md are not accurate or fail. We should review all them because if you copy and paste them into the command line, the results are not what we say at README.md.

Example:   getTokenBal `ethName -a singular` `getAccounts -n | xargs`  (this fails)

4) The gold files defined for this tool contain some data that it is not present at my box, how I can test the same?.

In general, I miss here more information about how this tool works, this is probably the root of all the issues. Of course we should review those commands that are not accurate.

By the way, we need a tag for this tool at github!!!

**Comment by tjayrush** [comment]
> Here you have my comments, after testing and reviewing the next tool "getAccounts".
> 
> 1) It is not clear for me how you can add/remove addresses to/from node's keystore. Help explained this will be welcome for everybody.
> 
> 
I agree with you, but please see my notes on #436

> 2) When you run it it displays 4 addresses by default, what are they?:
> 0x0000000000000000000000000000000000000000
> 0x0000000000000000000000000000000000000001
> 0x0000000000000000000000000000000000000002
> 0x0000000000000000000000000000000000000003

If I didn't do this, it would leak my addresses in the test files. Please see my notes on #436

> 3) The commands described at README.md are not accurate or fail. We should review all them because if you copy and paste them into the command line, the results are not what we say at README.md.
> 
> Example:   getTokenBal `ethName -a singular` `getAccounts -n | xargs`  (this fails)

Does `getAccounts -n | xargs` work?  Does `ethName -a singular` work? What error message does it report?

> 4) The gold files defined for this tool contain some data that it is not present at my box, how I can test the same?.

I'm going to remove the test cases. I don't want to leak my public keys in the test files. In fact, I'm going to double check that my API keys and public keys are not exposed.

> In general, I miss here more information about how this tool works, this is probably the root of all the issues. Of course we should review those commands that are not accurate.
> 
> By the way, we need a tag for this tool at github!!!

Added a tag. I'm thinking maybe I should remove this tool from the CMakefile.txt so it doesn't build. I don't think it's actually ready yet. And it's not really all that useful (yet). I don't want to delay, so I think what I'm going to do is remove it from the build, but leave it in the documentation. (and note that it's currently not ready. We are only at version 0.2.0 after all.) I'll create a reminder issues and make a note here when I do that.

**Comment by tjayrush** [comment]
For now, I think it's okay to close this issue. I'm going to delay this tool until after 0.2.0.

**Comment by crodnun** [comment]
Closing this issue, tool is not ready yet for this release.

**Comment by tjayrush** [comment]
I actually decided to put this back into the build, but I commented out all the test cases. The tool is very useful, but I don't really want to promote it just yet. So it builds and it will run from command line but it's not being tested.

**Comment by tjayrush** [comment]
Re-enabled the test cases. Closing this issue.
