### ISSUE TITLE
isContract README.md feedback

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#438]
For this tool I see the following improvements at README.md

1) Again, to be consistent, we should use always "address_list" everywhere:

isContract [-d|-n|-v|-h] address_list

2) Indicate at --nodiff that we need exactly 2 addresses to use this option. The address_list in this case should have 2 items.

3) Indicate that addresses should start with 0x like we do at other commands.

**Comment by tjayrush** [comment]
> For this tool I see the following improvements at README.md
> 
> Again, to be consistent, we should use always "address_list" everywhere:
> isContract [-d|-n|-v|-h] address_list
> 

I appreciate your comments, but I'm going to argue against this. I read a page on wiki-pedia how to specify an optional list, and optional list where at least one item is needed, etc., and according to that page, the listing in the first line text is right. I agree it should be consistent below, but then it would seriously mess up the spacing, and I like the way the spacing works. Any user sophisticated enough to use these tools, will understand immediately what <address> [address...] and address_list mean even if they are not identical. I like the way it looks, so I think I am going to keep it this way and try to make sure it's the same for all tools.

> Indicate at --nodiff that we need exactly 2 addresses to use this option. The address_list in this case should have 2 items.

This is already there when I say "(exactly) two..." I think. Maybe that's not clear enough?

> Indicate that addresses should start with 0x like we do at other commands.

I added a Notes section that appears when you do `isContract --help -v` 

I think you can go ahead and close this one. I'm going to do my best to make everything consistent, but this is 0.2.0 and I really do want to finish this soon.

**Comment by crodnun** [comment]
Seems not pushed yet, will close this when changes available at repository.

**Comment by tjayrush** [comment]
Should be fixed now.

**Comment by crodnun** [comment]
I could not see yet the option you mentioned in action:

"I added a Notes section that appears when you do isContract --help -v"

But closing anyways

**Comment by tjayrush** [comment]
Are you on master or develop? Can you confirm that `isContract --help` and `isContract --help -v` give two different messages? The second should include "notes" section.
