### ISSUE TITLE
getBlock readme should indicate that we also support block ranges

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#447]
The following command is a valid usage:

./getBlock 1-5

xxxx
xxxx
xxxx
xxxx
xxxx

But is not indicated in the README.md. 

Indeed testing the same I discover that there is a limit at range usage: "at most 1000 blocks". So this should be reflected at the README.md somehow.

**Comment by tjayrush** [comment]
If you do

    getBlock -vh

(i.e. verbose help) or look at the README.md file, you see this note:

    `block_list` is a space-separated list of values, **_a start-end range_**, a special, or any combination.

Doesn't that suffice?

I changed the limit to 10,000. I think, if a user, tries to show more than 10,000 blocks and gets this message, it will be apparent.

These changes should be pushed, and you may close this issue.

**Comment by crodnun** [comment]
Confirmed the fix, closing
