### ISSUE TITLE
getBlock  ranges using special blocks

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#448]
If we run the tool using as input a range of "special blocks":

./getBlock first-stateclear

We obtain the following error message:

getBlock argc: 2 [1:first-stateclear] 
getBlock first-stateclear 

  **'stop' must be strictly larger than 'start'**

  Usage:    getBlock [-r|-t|-c|-v|-h] <block> [block...]  
  Purpose:  Returns block(s) from local cache or directly from a running node.
             
  Where:    
        block_list            a space-separated list of one or more blocks to retrieve (required)
        -r  (--raw)           pull the block data from the running Ethereum node (no cache)
        -t  (--terse)         display only transaction hashes, default is to display full transaction details
        -c  (--check)         compare results between qblocks and Ethereum node, report differences, if any
        -v  (--verbose)       set verbose level. Either -v, --verbose or -v:n where 'n' is level
        -h  (--help)          display this help screen

  Powered by QuickBlocks

-------------------------------------------------------

I expected here to error out with "too broad range", it is a huge range, but it returns this confusing error message.

**Comment by tjayrush** [comment]
This should be fixed. Nice find.

**Comment by crodnun** [comment]
Confirmed the fix, closing
