### ISSUE TITLE
getBlock of "latest" block returns an unexpected error

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#449]
If we run:

> getBlock latest

We obtain this error:

getBlock argc: 2 [1:latest] 
getBlock latest 
getLatestBlockFromCache failed: 2: File does not exist: /home/carlos/.quickBlocks/cache/fullBlocks.bin

        From client: 4350696 inCache: 0 Behind (maybe empty): 4350696

**Comment by tjayrush** [comment]
This is an excellent find. It should be fixed now. You may close this issue if you agree.

**Comment by crodnun** [comment]
Confirmed the fix, closing
