### ISSUE TITLE
getBlock, undocumented option

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#450]
Running:

> getBlock  --terse 100000

We obtain that:

  --terse options work only with --source:raw. Quitting...

I do not see this option "--source" documented, in fact it is something new comparing this tool with the previous ones. We should unify/clarify this part.

**Comment by tjayrush** [comment]
This should be fixed. Nice find. By the way, this applies to multiple tools since they all use the same command line parsing code. You may close this if you think it's fixed.

**Comment by crodnun** [comment]
Confirmed the fix, closing
