### ISSUE TITLE
getBlock does not check input range

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#451]
Executing:

> getBlock rrr-ttt

it should verify the blocks format, but now returns:

'stop' must be strictly larger than 'start'

**Comment by tjayrush** [comment]
This should be fixed. Nice find. By the way, this applies to multiple tools since they all use the same command line parsing code. You may close this if you think it's fixed.

**Comment by crodnun** [comment]
Confirmed the fix. Closing
