### ISSUE TITLE
getBloom with latest block seems not working

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#452]
if we run

./getBloom latest

we obtain this message:

getBloom argc: 2 [1:latest] 
getBloom latest 
getLatestBlockFromCache failed: 2: File does not exist: /home/carlos/.quickBlocks/cache/fullBlocks.bin

        From client: 4353812 inCache: 0 Behind (maybe empty): 4353812

**Comment by tjayrush** [comment]
This should now work. This is now also working in getBlock on machines without the fullBlockIndex.bin file. You may close this if you agree.

**Comment by crodnun** [comment]
Confirmed, it is solved. Closing
