### ISSUE TITLE
Duplicate option "-e" at getBloom usage

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#453]
Usage: getBloom [-r|-e|-e|-c|-v|-h] 

The option "-e" is duplicated at usage message and at table describing the purpose of the option:

-e | --enhanced | retrieve the enhanced bloom filter for a given block (see documentation)
-e | --receipts | display receipt level blooms, default is to display only block-level blooms

**Comment by tjayrush** [comment]
Should be fixed with above commit. Please close if you agree.

**Comment by crodnun** [comment]
OK, fixed. Closing
