### ISSUE TITLE
getBloom --check <block_number> seems not operative

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#456]
When I run:

./getBloom --check 2000

I obtain empty output:

getBloom argc: 3 [1:--check] [2:2000] 
getBloom --check 2000 

I expected the same behaviour we have at getBlock, just to compare cache with node,

Is this option working as intended? Is it supported?

**Comment by tjayrush** [comment]
This was a mistake in the list of options for this tool. There is no --check mode for getBloom. You may close this if you confirm.

**Comment by crodnun** [comment]
Confirmed, closing
