### ISSUE TITLE
Long option --enhanced at getBloom seems not working

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#457]
If we run:

./getBloom --enhanced 10000

We obtain, the  following "invalid option" error:

getBloom argc: 3 [1:--enhanced] [2:10000] 
getBloom --enhanced 10000 

  Invalid option: --enhanced

  Usage:    getBloom [-r|-e|-e|-c|-v|-h] <block> [block...]  
  Purpose:  Returns bloom filter(s) from local cache or directly from a running node.
             
  Where:    
        block_list            a space-separated list of one or more blocks from which to retrieve blooms (required)
        -r  (--raw)           pull the bloom filter from the running Ethereum node (no cache)
        -e  (--enhanced)      retrieve the enhanced bloom filter for a given block (see documentation)
        -e  (--receipts)      display receipt level blooms, default is to display only block-level blooms
        -c  (--check)         compare results between qblocks and Ethereum node, report differences, if any
        -v  (--verbose)       set verbose level. Either -v, --verbose or -v:n where 'n' is level
        -h  (--help)          display this help screen

  Powered by QuickBlocks

-----------------------------------------------------------------------------------

If this options supported? correctly documented? We should fix it or/and the help message displayed.

**Comment by tjayrush** [comment]
I hid this option. I will remember it, but for the time being it does not need to be documented. You may close this issue.

**Comment by crodnun** [comment]
OK, option is no longer available now. Closing
