### ISSUE TITLE
Minor typos at getLogs README.md and its help

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#458]
Line 2:

"a block hash **plus** plus transaction index"

At notes, second bullet:

This tool checks for valid input **sytax**, but does not check that the transaction requested exists

The same typos are present at the README.md of the following tools (apart from getLogs):

getReceipt
getTrace

At getTrans we only have the second one:  **sytax**

**Comment by tjayrush** [comment]
Nice find. These should all be fixed now. You may close this.

**Comment by crodnun** [comment]
Fixed. Closing
