### ISSUE TITLE
getLogs supports the undocumented option --parity

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#459]
Is this option required now? Do we need to document it?

If we remove it, we need to remove those test cases that currently are using the same.

Seems available at other tools too. We should clarify what to do with this hidden and undocumented option

**Comment by tjayrush** [comment]
I think I'm going to ask you to just close this issue. I know this is undocumented, but it's okay. I will have to make a change to a single file, and I will do that, but I don't want to expose this feature now. This is documented in one of the 'delayed' bugs, I know that, but I don't feel like finding it now. So you can just close this one. Thanks.

**Comment by crodnun** [comment]
Delayed and closing per Thomas request
