### ISSUE TITLE
Questions for database examples in the samples folder

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#460]
What are the dependancies of the database software?

How long does it take to store the data into the database?
How much hard disc space does the data take up?
How long does it take to export the data to the screen?

Test cases for each different database:
- Run for 1000 blocks
   - store the data in mongo
   - print the data to screen
   - time everything vs. mysql and quickBlocks

User must know to pick up headers from `/usr/local/qblocks/include` and libraries from `/usr/local/qblocks/libs`

**Comment by tjayrush** [comment]
Only do this if you have time. Do this last.

**Comment by tjayrush** [comment]
How does one install a database?

Two tables, created dynamically

Block
=========
blockNumber         uint64
timestamp              uint64

Transactions
============
blockNumber         uint64
indexInTheBlock   uint32
string from              
string to                  
bignum value         uint256
string input

Receipt
=========
blockNumber         uint64
indexInTheBlock   uint32
string                     result

**Comment by crodnun** [comment]
Uploaded  today a quick example of mysql stuff, not completed yet but a good reference if you want to play around with it. We can look at it today at our meeting.

**Comment by tjayrush** [comment]
Perfect

**Comment by tjayrush** [comment]
Closing. This is mostly conversational.
