### ISSUE TITLE
Within general options we support both --nocolors and --nocolor (in singular)

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#461]
Stupid issue I discovered while testing, I made a mistake and detected that both are supported so maybe we should keep only one.

I know that this is not a big deal, but I create an issue to note down the same.

If you keep only --nocolors, you will not have to modify the documentation. It is the only one documented so far.

If you consider that we can close this directly, I will do it. :-).

**Comment by tjayrush** [comment]
I removed the plural version and updated all the docs (they are automatically generated, so it was no big deal). Nice find. You may close this if you agree.

**Comment by crodnun** [comment]
Fixed. Closing
