### ISSUE TITLE
Discrepancy in getTrans test-cases output

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#464]
When running the test cases "getTrans_from_node" / "getTrans_from_node_long" I do not obtain the same result expected at gold files.

The commands run by these test cases are (respectively):

> ./getTrans -r 4000000.5
>./getTrans --raw 4000000.5

I obtain exactly the same output that we have as gold file, except the last id field:

At /home/carlos/quickBlocks/test/gold/tools/getTrans/getTrans_from_node.txt we have a line ending with:

**,"id":3}**

But I obtain a line ending with:

**,"id":86}**

Does it have an explanation? Why I obtain at my node different output? Maybe this field is dynamic?

**Comment by tjayrush** [comment]
This should be fixed. It was temporal data due to the fact that I'm running against a local node when I test, and you're running against FALLBACK=infura. It should work in both cases now. You may close this if you agree.

**Comment by crodnun** [comment]
OK fixed. Closing
