### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by adamski** [Great-Hill-Corporation/quickBlocks#468]
Can quickBlocks run on Windows? I'm interested in embedding it into a cross-platform desktop app. Trying to avoid depending on a centralised server where possible.

**Comment by tjayrush** [comment]
Currently, no, we don't have a windows version. Have you tried compiling it on Windows? @crodnun mentioned some sort of Linux command line emulator, but I don't remember what it was called. If you want to take a stab at compiling it on Windows, I would certainly make myself available to help you out if you get stuck.

**Comment by tjayrush** [comment]
Thanks for reporting this issue. We're about a week away from making our first beta release. I want to have all issue closed before the release; therefore, I am going to close this. But first, I am going mark it 'delayed' and note it in #293 which is our list of 'delayed' issues. All of the 'delayed' issues will be reopened once the beta release goes out.

**Comment by adamski** [comment]
Thanks, I'll be working in the Mac version first so no rush. I'll revisit once I've got that working!

**Comment by tjayrush** [comment]
I'd be very interested in hearing your experiences with the Mac version. Please stay in touch.

**Comment by tjayrush** [comment]
Closing as dup of #249
