### ISSUE TITLE
Un-documented option --trace at getTrans

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#469]
At getTrans README.md (second paragraph) . We say: 

"Use the --trace option to display a trace of the transaction as well."

What is the usage of this option?? I do not see it documented and seems new at this tool. Is is a general option or maybe a typo?

**Comment by tjayrush** [comment]
This was just an oversight. It should be removed now.

**Comment by crodnun** [comment]
Fixed. Closing
