### ISSUE TITLE
Doubt regarding getBloom -a "option"

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#470]
I have seen that we have a test case that runs this way:

> getBloom --parity  -a  2769609 2799895 2872831 3076260

What does the -a option mean? I do not see it at usage and seems that when I use it, I am not able to retrieve the information.

If I run:

> getBloom 2769609

I obtain valid data:

etBloom argc: 2 [1:2769609] 
getBloom 2769609 
{
    "logsBloom": "0x00000000000000000000000000000000000000000400000000000000000000000000000000000000000000000080000008000000004040000004000000000000000000000000000004000080000000000001000000000000000104000004000000100000000000000000000000000000000000000000000000020000000010000000000000000002000000000004000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000100000000000020000000000000000400000000400000000000002",
    "blockNumber": 2769609
}

But when I run it with the un-documented option "-a", I obtain different information (seems empty):

> getBloom -a 2769609

getBloom argc: 3 [1:-a] [2:2769609] 
getBloom -a 2769609 
{
    "logsBloom": "0x0",    ----------------------------- Nothing here
    "blockNumber": 0   -------------------------------  Nothing here
}

**Comment by tjayrush** [comment]
This is equivalent to --source:cache. Since we documented that issue in #454, we can close this as a duplicate.

**Comment by crodnun** [comment]
Perfect, understood now
