### ISSUE TITLE
Minor typos at README.md

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#471]
https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/other/install/INSTALL.md

At first line:

"The only **depenencies** for QuickBlocks are"

At third paragraph:

The ethslurp tool will not run without an API key from EtherScan.io (registration is required). The tool will **requst** a key from that site before running.

At the same readme, at finish installation instructions:

The installation installs the QuickBlocks command line tools in the folder /usr/local/qblocks/bin. You may wish to add this path to your ${PATH} **enviorment** variable.

At same readme, at final section:

After you're done building and installing the library and tools, you may wish to try your hand at building some QuickBlocks **applicaitons** or tools

--------------------------------------------------------------------------------

At https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/other/install/RUNNING_A_NODE.md.

We store our QuickBlocks cache on an external SSD hard drive. We've found this SSD drive to be quite **execllent** for this purpose.

---------------------------------------------------------------------------------

At this page:

https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/apps/README.md

latest paragraphs, we talk about "chafra", I think that this is a typo and we wanted to refer to chifra.

Here:

grabABI: This is the basis of the **## chafra** application. Given an Etheruem address, this tool first grabs the ABI from where ever it can find it (http://etherscan.io, ENS, etc.). It then parses the ABI and writes all the C++ necessary to build an Ethereum address monitor. **## chafra** uses this tool extensively.

makeClass: This tool is used by grabABI to write the actual C++ code generated during the **## chafra** process. Many of the source files found in etherlib are also generated automatically using this tool.

**Comment by tjayrush** [comment]
These are all amazing finds. Nice job. All should be fixed. You may close this if you agree.

**Comment by crodnun** [comment]
Is this correct in english? Never seen before, but maybe I am wrong:

At

https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/other/install/INSTALL.md

At first line:

"The only **dependancies** for QuickBlocks are"

**Comment by tjayrush** [comment]
Fixed. It was a misspelling.

**Comment by crodnun** [comment]
Confirmed, closing
