### ISSUE TITLE
Broken links at documentation

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#472]
The link to twitter at 

https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/apps/ethslurp/README.md
line 3

https://twitter.com/ethslurp ---- does not exist

--------------------------------------------------------------------

At main readme:  https://github.com/Great-Hill-Corporation/quickBlocks/tree/develop.

We have a couple of links broken related with RPC and vote

Higher Information Content

An Ethereum node knows nothing about Solidity source code. It can only return hexadecimal bytes. In order to make the data useful, each user must re-translate the data back into the language of the smart contract. For example, **## this complicated RPC data is simply a yes vote** on a proposal. While QuickBlocks is able to return raw hexadecimal data identical to the RPC, by default it returns what we call articulated data.

----------------------------------------------------------------------------

At  https://github.com/Great-Hill-Corporation/quickBlocks/tree/develop/src/monitors

The links to tools, apps, libs point to the same monitors page here:

Monitors take advantage of **## the apps, tools and libraries** that comprise the system.

----------------------------------------------------------------------------
At 

https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/apps/README.md

we mention the miniBlocks but its links does not exist.

**Comment by tjayrush** [comment]
All of these should be fixed. If you agree, you may close this.

**Comment by crodnun** [comment]
Confirmed, closing
