### ISSUE TITLE
At documentation (readme files) we mention and option not documented for getBlock

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#473]
At document:

https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/other/install/RUNNING_A_NODE.md

We say:

 QuickBlocks does not cache every request. For example, the getBlock command only caches if you tell it to **with the --force option**, thus:

But this option is not documented at current release.

**Comment by tjayrush** [comment]
Hidden options are documented here: https://github.com/Great-Hill-Corporation/quickBlocks/issues/238.  I added a note about the README file so we don't forget it. You may close this.

**Comment by crodnun** [comment]
Closing per Thomas request
