### ISSUE TITLE
ethslurp scenario without API key

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#474]
I was trying to test what happens when I do not have an API key for ethslurp and run it for the first time.

I removed the API_KEY I own from the cache and run the following command:

> ethslurp 0x2a65aca4d5fc5b5c859090a6c34d164135398226 

I obtain the expected warning but the option to enter the API_KEY at command line seems not working and it aborts the execution of the program. Users do not have the option to enter the key or type exit here, the command just finishes and we can never enter the key (imagine that we recently got one and we want to configure it at the first time we use the tool).

ethslurp argc: 2 [1:0x2a65aca4d5fc5b5c859090a6c34d164135398226] 
ethslurp 0x2a65aca4d5fc5b5c859090a6c34d164135398226 
Processing: 0x2a65aca4d5fc5b5c859090a6c34d164135398226

  ***Warning***
  This program needs an api_key from EtherScan in order to work. You may get one at
  http://etherscan.io/apis. See our online help file for more information.
  Please provide an API key or type 'exit'

------------------- **I expected to stop here and be able to enter the key, but it finishes  inmediately**------

  > carlos@ubuntu-4gb-fra1-01:~/quickBlocks/bin

**Comment by tjayrush** [comment]
It looks like you may have TEST_MODE exported in your environment (I can tell because of the 'argc' printout in your output). If that's the case, the ethslurp tool does not accept input (if it did, the test hangs). Try running it again without TEST_MODE in your environment.

**Comment by crodnun** [comment]
OK understood now, my mistake with environment. Closing
