### ISSUE TITLE
Review all README files

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#484]
Please visit each README file looking only for two things: (1) spelling mistakes, (2) "serious" mistakes in "sense."  The documents do not have to be perfect (they will all be rewritten before 0.5.0), but we want to remove anything that makes no sense. Check the box once the item is reviewed, even if you've written an issue against. Do the "Help File" last. You may have already done this for some of these. If so, simply check the box, don't review it again.

#### Top
- [x] [./README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/README.md)
- [x] [./src/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/README.md)
- [x] [Help File](http://quickblocks.io/docs)
#### Apps
- [x] [./apps/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/apps/README.md)
- [x] [./apps/ethprice/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/apps/ethprice/README.md)
- [x] [./apps/ethslurp/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/apps/ethslurp/README.md)
- [x] [./apps/grabABI/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/apps/grabABI/README.md)
- [x] [./apps/makeClass/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/apps/makeClass/README.md)
#### Apps (0.5.0)
- [x] ~~[./apps/blockAcct/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/apps/blockAcct/README.md)~~
- [x] [./apps/blockScrape/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/apps/blockScrape/README.md)
- [x] [./apps/chifra/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/apps/chifra/README.md)
- [x] [./apps/chifra/templates/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/apps/chifra/templates/README.md)
- [x] ~~[./apps/miniBlocks/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/apps/miniBlocks/README.md)~~
#### Libs
- [x] [./libs/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/libs/README.md)
- [x] [./libs/acctlib/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/libs/acctlib/README.md)
- [x] [./libs/etherlib/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/libs/etherlib/README.md)
- [x] [./libs/utillib/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/libs/utillib/README.md)
- [x] [./libs/tokenlib/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/libs/tokenlib/README.md)
- [x] [./libs/walletlib/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/libs/walletlib/README.md)
- [x] [./libs/test-libs/abilib/abiTest/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/libs/test-libs/abilib/abiTest/README.md)
- [x] [./libs/test-libs/acctlib/acctTree/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/libs/test-libs/acctlib/acctTree/README.md)
- [x] [./libs/test-libs/etherlib/convert/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/libs/test-libs/etherlib/convert/README.md)
- [x] [./libs/test-libs/etherlib/dataUpgrade/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/libs/test-libs/etherlib/dataUpgrade/README.md)
- [x] [./libs/test-libs/etherlib/printFloat/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/libs/test-libs/etherlib/printFloat/README.md)
- [x] [./libs/test-libs/etherlib/serialize/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/libs/test-libs/etherlib/serialize/README.md)
- [x] [./libs/test-libs/etherlib/sha3/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/libs/test-libs/etherlib/sha3/README.md)
- [x] [./libs/test-libs/utillib/apiTest/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/libs/test-libs/utillib/apiTest/README.md)
- [x] [./libs/test-libs/utillib/bigIntTest/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/libs/test-libs/utillib/bigIntTest/README.md)
- [x] [./libs/test-libs/utillib/cmdLineTest/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/libs/test-libs/utillib/cmdLineTest/README.md)
- [x] [./libs/test-libs/utillib/colorTest/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/libs/test-libs/utillib/colorTest/README.md)
- [x] [./libs/test-libs/utillib/exportContext/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/libs/test-libs/utillib/exportContext/README.md)
- [x] [./libs/test-libs/utillib/jsonTest/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/libs/test-libs/utillib/jsonTest/README.md)
- [x] [./libs/test-libs/utillib/stringTest/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/libs/test-libs/utillib/stringTest/README.md)
- [x] [./libs/test-libs/utillib/tomlTest/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/libs/test-libs/utillib/tomlTest/README.md)
- [x] [./libs/test-libs/utillib/typesTest/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/libs/test-libs/utillib/typesTest/README.md)
#### Monitors
- [x] [./monitors/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/monitors/README.md)
- [x] [./monitors/cacheMan/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/monitors/cacheMan/README.md)
#### Tools
- [x] [./tools/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/tools/README.md)
- [x] [./tools/ethName/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/tools/ethName/README.md)
- [x] [./tools/getAccounts/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/tools/getAccounts/README.md)
- [x] [./tools/getBalance/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/tools/getBalance/README.md)
- [x] [./tools/getBlock/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/tools/getBlocks/README.md)
- [x] [./tools/getBloom/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/tools/getBloom/README.md)
- [x] [./tools/getLogs/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/tools/getLogs/README.md)
- [x] [./tools/getReceipt/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/tools/getReceipt/README.md)
- [x] [./tools/getTokenBal/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/tools/getTokenBal/README.md)
- [x] [./tools/getTrace/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/tools/getTrace/README.md)
- [x] [./tools/getTrans/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/tools/getTrans/README.md)
- [x] [./tools/isContract/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/tools/isContract/README.md)
- [x] [./tools/scripts/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/tools/scripts/README.md)
- [x] [./tools/whenBlock/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/tools/whenBlock/README.md)
- [x] [./tools/whereBlock/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/tools/whereBlock/README.md)
#### Other
- [x] [./other/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/other/README.md)
- [x] [./other/articles/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/other/articles/README.md)
- [x] [./other/docs/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/other/docs/README.md)
- [x] [./other/papers/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/other/papers/README.md)
#### Samples
- [x] [./samples/README.md](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/samples/README.md)

**Comment by crodnun** [comment]
Hi Thomas, I have completed the full review of the documentation enumerated above, some issues have been created to review the doubts/typos/mispelling I have found so far. Feel free to close this issue whenever you want.

**Comment by tjayrush** [comment]
Closing. Thanks for your work.
