### ISSUE TITLE
Make sure all sample build without CMakeLists structure

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#485]
If a user downloads, builds, and installs QuickBlocks, he should be able to build the samples (and they should work) without needing to build the entire source tree, and each sample should be "stand-alone."

In other words, if the user copied the ./src/samples/simple folder to ~/simple on his/her hard drive, he/she should be able to go to ~/simple and do `make` and then `make test` and it should build and run.

**Comment by crodnun** [comment]
Hi Thomas, I did a first attempt for this doing the following:

1) The samples folder will have a Makefile that invokes the rest (make -C dir)
2) For the moment only bloomScan is available (just to confirm that this is what you were looking for)

When possible do a git pull and confirm that this was your goal at this issue and I will update the rest of tools.

Of course, take into account that using Makefile, windows is not supported yet and a pre-requisite is to install qblocks first.

Anyways give it a look and let me know your feedback about this first step, before going ahead with the rest.

**Comment by tjayrush** [comment]
I did this:

     cd build
     cmake ../src
     make
     make install

I then moved to my home folder

     cd ~

And then 

     cp -pR quickBlocks/src/samples .

To create a folder unrelated to the quickBlocks repo and then I tried to build. I first thought there would be a Makefile in ~/samples to build all the samples (can you do this?).  I then moved into the ~/samples/bloomScan and did `make` and it worked, and the tool ran fine.

     cd ~/samples
     make (failed because no Makefile)
     cd bloomScan
     make (build bin/bloomScan, which builds and runs fine)

To do:

1. Identify the samples we want to include (perhaps only `simple` and `bloomScan` but also database examples if we can get them done).
2. Add all other subfolders to .gitignore so only the selected samples appear in the repo

**Comment by crodnun** [comment]
OK, my mistake. I forgot to push the root Makefile, should be present now when doing the pull.
Let me know what binaries should be included here:
simple & bloomScan only?

**Comment by tjayrush** [comment]
That worked. Include bloomScan, simple and txCounter. You may close this whenever you like. I don't have to re-test it.

**Comment by tjayrush** [comment]
When you done, let me know. I will test it one more time and then close this.

**Comment by tjayrush** [comment]
In this line: https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/samples/bloomScan/Makefile#L15 . Add the tokenlib.a and the walletlib.a files. The samples will eventually need them, even though they won't use them yet.

**Comment by crodnun** [comment]
OK, completed. If  I dit not make any mistake you can pull my changes and test it at your side. If it is OK, you may close the issue.

**Comment by tjayrush** [comment]
Closing it looks good.
