### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#487]
Get it to compile
Add it to the installation instructions
This is low priority. If it does not get completed by the time we release 0.2.0 that's okay. We won't wait.

**Comment by crodnun** [comment]
No luck with this, after tweaking a bit the CMakeLists.txt and build the curl library. 

I am able to generate a full Visual Studio solution with all our toosl but we have the great disadvantage that most of the standard headers we use at our code are not present at windows.

To make it work at windows we should port them and add many "ifdef WIN32" in our code :-(  :-( :-(.

Examples of header files that generate errors when compiling quickblocks at visual studio solution:

#include <glob.h>
#include <libgen.h>
#include <pwd.h>
#include <unistd.h>
#include <utime.h>
#include <sys/time.h>
...
...

Most of them could be easy to port, but will require a lot of investigation and effort, so feel free to close this for the moment.

**Comment by tjayrush** [comment]
I think we'll put this one on the back burner. I understand that I am losing a large number of potential users, but one must draw lines sometimes. Thanks for trying.
