### ISSUE TITLE
Typo at apps README

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#488]
https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/apps/README.md

The **cacheMan** section has these typos:

cacheMan: This tool allows one to explore **the a monitor's binary** cache data file. It **preforms** various checks on the data.

**Comment by tjayrush** [comment]
Fixed. I moved the cacheMan text. This may be closed, I think.

**Comment by crodnun** [comment]
Confirmed fix, closing
