### ISSUE TITLE
ethslurp section not required (in my opinion)

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#489]
If you go to:

https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/apps/ethslurp/README.md

The section "Building from source" is redundant (we already inform how to install everything at different README file), looks not uniform (the rest of apps do not have the same) and it has a broken link to INSTALL.md instructions, seems no longer available.

**Comment by tjayrush** [comment]
I re-wrote this. Don't bother re-reading it. Let's just close this. This tool will eventually disappear once it's replaced with a monitoring tool.

**Comment by crodnun** [comment]
OK closing
