### ISSUE TITLE
Links provided at issue #484 are from master branch (merge is pending)

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#490]
Hi Thomas, the links provided at this issue, the one you opened yesterday to review everything are from master branch, I am doing them in the develop branch. A merge will be required later. Take this into account.

**Comment by tjayrush** [comment]
Oh. This brings up an issue. I'm asking your advice here. Should the links be:

1. Always linking into 'master,'
2. Always linking into 'develop'
3. Always be relative so they work in both to the same repo?

I think (3), but I ask your advice.

**Comment by crodnun** [comment]
If you refer to the links inside documents, always use relative links, they should work at any branch. Never you the branch name in them.

If you refer to links posted at issues, always use develop branch, we always fix issues at develop, never at master branch.

Feel free to close the issue if you keep in mind that working at issues we must always touch the develop files.

**Comment by tjayrush** [comment]
I understand. I should always link relatively unless I am referencing an issue, and then always link to 'develop' since that's where we fix things. Got it. I'm closing this issue now.
