### ISSUE TITLE
Typos and comments about grabABI readme

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#491]
At 

quickBlocks/src/apps/grabABI/README.md

We have a mispelling at first paragraph, here (I think, sometimes not sure with the British and USA english...lol):

grabABI **retreives** an ABI file either from a local cache, from the Ethereum Name Service (ENS), or from Etherscan. Once **retreived**, 

Apart, an improvement/suggestion:

The notes section has a different format comparing it with the tools one, we should use the same format everywhere

**Comment by tjayrush** [comment]
Fixed.

**Comment by crodnun** [comment]
Reviewed and closing
