### ISSUE TITLE
Typos at blockScrape readme

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#492]
- At  https://github.com/Great-Hill-Corporation/quickBlocks/tree/develop/src/apps/blockScrape  first line we have this typo:

Note: This tool is **availble** through our website.

- The same typo is present at chifra doc here:

https://github.com/Great-Hill-Corporation/quickBlocks/tree/develop/src/apps/chifra

- Also at the end of the blockScrape page, after copyright we have an strange "W" character. Here

https://github.com/Great-Hill-Corporation/quickBlocks/tree/develop/src/apps/blockScrape

**Comment by tjayrush** [comment]
Fixed. Nice find.

**Comment by crodnun** [comment]
Reviewed and closed
