### ISSUE TITLE
Typo at chifra doc

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#493]
- Here: https://github.com/Great-Hill-Corporation/quickBlocks/tree/develop/src/apps/chifra at the end of the second paragraph we have this typo:

addresses and the code to build an **interative** transactional debugging/auditing program.

**Comment by tjayrush** [comment]
I fixed this. You may close it.

**Comment by crodnun** [comment]
Reviewed and closing
