### ISSUE TITLE
This sentence is written on purpose or is a typo?

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#494]
At 

https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/libs/README.md

we say:

The etherlib library. "**The core of the core of the system**"

Just a doubt if the previous sentence is written on purpose to describe this library or it is just a typo

**Comment by tjayrush** [comment]
This is on purpose. You may close this.

**Comment by crodnun** [comment]
Perfect, then no more to say. Closing
