### ISSUE TITLE
Improvements and typos in etherlib readme

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#495]
- Here

https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/libs/etherlib/README.md

at the end of the section "Communication with Node" we say:

**The reader is invited to read about using the node’s RPC in documentation to be found outside of this white paper [3][4]**

we mention some white papers with numbers but no links, maybe a link is welcome here to improve the reading.

-  At same readme, at the beginning of the next section "Mirroring of blockchain data":

We say:

**The mirroring (or caching) of the blockchain data is provided by six classes: CBlock, CTransaction, CReceipt, CLogEntry, CTrace, and CStructLog. Each of these classes is documented in Appendix D.**

As a reader, I would like to know what is the Appendix D?

- Idem for the section:

https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/libs/etherlib/README.md#convenience-functions-for-traversing-blocks-transactions-and-accounts

We again mention an Appendix E that would like to know where it is...lol

- At CAbi class section here
https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/libs/etherlib/README.md#cabi

at the end of the paragraph we have this typo

in others we need to find **an name given an encoding**

- At the Cparameterr section of this readme, here

https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/libs/etherlib/README.md#cparameter

 we mention again a new Appendix, the Appendix A:

**makeClass application as detailed in Appendix A.**

- At the last section, last paragraph we mention again another appendix:

**In Appendix C,** we’ve included the configuration files

**Comment by tjayrush** [comment]
Item 1) The **The reader is invited to read...** issue: Fix by removing the paragraph entirely.

Item 2) The **mirroring (or caching) of the blockchain** issue: I just referenced the white papers directly.

Item 3) The "mention an Appendix E" issue: I linked to the white papers.

Item 4) Fixed "an name" to "a name."

Item 5) The final two "Appendix" issues: I linked to the white papers.

This whole README file will be re-written. It's not well done, but it's good enough. Thanks. I think you can close this one.

**Comment by crodnun** [comment]
Reviewed and closing
