### ISSUE TITLE
Sentence that has no meaning

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#496]
At the end of this readme:

https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/libs/tokenlib/README.md

we say:

**This feature is described in the next session.**

It has no meaning in this context, isn't it? What do you mean with this?

The same happens at:

https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/libs/walletlib/README.md

Both readme seems to have the same content :-) :-)

**Comment by tjayrush** [comment]
Fixed. You may close this one.

**Comment by crodnun** [comment]
Confirmed and closing
