### ISSUE TITLE
Same content at both readme

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#497]
At:

https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/libs/tokenlib/README.md

and

https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/libs/walletlib/README.md

we have exactly the same content. Was this done on purpose or is a bug?

**Comment by tjayrush** [comment]
This was done on purpose. Please close this bug, but I marked it as delayed and added to #293. We can open it back up later.

**Comment by crodnun** [comment]
Cool, closing
