### ISSUE TITLE
Dates missing at articles table

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#499]
What is the meaning of the Date tags at articles table?

Here

https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/other/articles/README.md

we have some articles with the date defined but others is missing, is it pending?

**Comment by tjayrush** [comment]
This should be fixed now. Thanks.

**Comment by crodnun** [comment]
Minor typo at date now:

A Neglected Aspect of Smart Contract Security: Auditability | **Auguest** 24, 2016

**Comment by tjayrush** [comment]
Done. Sorry for the carelessness.

**Comment by crodnun** [comment]
No worries, it is my duty ;-). Confirmed and closing
