### ISSUE TITLE
Help documentation review

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#500]
- At Help documentation here:

http://quickblocks.io/docs/introduction.html

at Architecture section, the paragraph after the image has a broken link here:

See **this FAQ item**, in response the nagging question in your head about the quality and accuracy of the data.

- At http://quickblocks.io/docs/techref.html#blockscraper-application

we have a minor typo here:

This process is fully described in our three **white papers,.**      ( , and then . is used)

**Comment by tjayrush** [comment]
These should be fixed. You may close this.

**Comment by crodnun** [comment]
Confirmed, closing
