### ISSUE TITLE
watchContract.py core dumps when started with parity already running.

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#518]
At this line:

https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/monitors/scripts/watchContract.py#L121

If parity is already running, proc is undefined, which causes this line:

https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/monitors/scripts/watchContract.py#L137

to fail. As a result, parity is not restarted and fills the disk defeating the purpose of the program.

**Comment by crodnun** [comment]
Hi Thomas, added a new function to obtain the correct PID (the running PID) in all the scenarios.

It is not portable (not supported in Windows) but should work at your MAC, please kindly check this solution and let me know results.

The function added is this:

**def get_parity_pid():
    #pid = os.system('pidof %s' % parity_proc_name)
    # Get PID from name, this is only valid under Linux like environments
    pid = subprocess.check_output("pgrep " + parity_proc_name, shell=True)
    #print(pid)
    return pid**

This way we get the PID always based on running process, not in launched one.

**Comment by tjayrush** [comment]
Okay. I will use it and re-open if it doesn't work. It looks good to me.
