### ISSUE TITLE
Need new whenBlock test case

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#519]
With the latest version (develop), whenBlocks has its own configuration file called ~/.quickBlocks/whenBlock.toml. (Note: each tool will, in the future, potentially have its own configuration file.)

I want to do this to make it easier to explain how to customize the data for a particular tool. For example, someone who is studying ICO behavior, might like to have a list block numbers that includes particular block numbers for those ICOs.

I need a way to test that this is working. The user may edit the file ~/.quickBlocks/whenBlock.txt to add his/her own dates/blocks. Can we test this functionality? The test would have to somehow save the existing file, change an entry to customize a block name, run the test, then set the config file back to its previous contents.

I don't know how to do this in cmake or Python. Can you please add a test for making custom data/block pairs for the whenBlock tool.

**Comment by crodnun** [comment]
Hi Thomas, I have been struggling a bit to find a generic solution for this and here you have my idea (it made me sweat, you bet!!!).

My idea is to make it generic (not only for whenBlock), supported everywhere and if feasible do not modify our current test architecture, not easy...lol!!!

My idea is to keep using the same test architecture but make smarter the python script we use at low level.

To do this, my idea is to say "OK, run the test but if you have a folder with a different configuration, put it under .quickBlocks, run the test and then restore the original one".

If we create a new folder called "custom_config" or whatever your consider under:

/quickBlocks/test/**custom_config**/

We can add there customized configuration for a given test. I put here just an example for the whenBlock tool but you could use it for every tool:

We define the following structure of directories:

/quickBlocks/test/**custom_config**/tools
/quickBlocks/test/**custom_config**/tools/whenBlock/testName
/quickBlocks/test/**custom_config**/tools/whenBlock/testName/whenBlock.toml

With this structure we are saying:  for test "testName" we want to use the customized whenBlock.toml present at the folder with the same name. Of course if not present, no customization is requested.

This way when we run the current test script (python one), it can look at this folder where we store customized configuration for each tool and specific test and use it if present, when not present we will keep the current behaviour using the configuration present under .quickBlocks directory.

Under this directory you can add in the future more customized files, that will be used to run the test if present. For example:

/quickBlocks/test/**custom_config**/tools/whenBlock/testName/whenBlock.toml
/quickBlocks/test/**custom_config**/tools/whenBlock/testName/whereBlock.toml
/quickBlocks/test/**custom_config**/tools/whenBlock/testName/getBalance.toml
...
...

If you run the test "testName", it will use the customized files present there instead the default ones (temporary, they will be restored after the test).

Let me know what you think about this idea, problems that you see, etc,... it is the best that came to my mind after hours trying to be backwards compatible and at the same time think on the future.

**Comment by tjayrush** [comment]
Sounds great. So if I want to add a custom config file to a particular test I can do that simply by placing a file in the right ./test/custom_config.... folder? Is that right? That would be great. In other words, I could add a new custom test without having to program anything. Is that right?

If yes, then yes, please proceed using the `whenBlock` test case (a new one) as an example.

**Comment by crodnun** [comment]
That's the idea!!!, to modify the python test script to use the custom_config (if available), otherwise just execute it with current configuration as usual. I will update you when this is ready.

**Comment by crodnun** [comment]
This feature should be in place now. Changes done:

1) The core of the tests (the testCheck.py script) is updated now with this new feature. If a custom configuration is defined at the suitable path, it uses it, runs the test and then restores the original one.

It should support any customized file in the future, just adding it here:
https://github.com/Great-Hill-Corporation/quickBlocks/blob/000732ef446afd6a6cbecbad87cf23753dccfe81/src/tools/scripts/testCheck.py#L127

2) Under github, appears a new directories structure:

    test/custom_config/

    This structure will allow us to define customized tests when required, just creating subfolders here with 
    the customized configuration we want to use for a given test.

3) I pushed also and example for whenBlock. Steps done:

    3-1)  You define the test at CMakeLists.txt as usual. My example is the following:
             **run_test("whenBlock_customized_1" "myblock")**

    3-2)  Then you define the customized configuration for this test under:
            
             **test/custom_config/tools/whenBlock/whenBlock_customized_1/** 

             Notice here that an individual directory is required for each test, to put there the customized 
             configuration you want to use. In this case I just put a different whenBlock.toml with my 
             customized block "myblok2 = 666

     3-3)  You need to create the gold file as usual, at the same directory we are using to work with, the 
             only difference is that this time it is using a different configuration, so you need to run it first get 
             the output and define the expected gold file.

Test it and let me know if it is working as intended: does not break existing testing tools, is flexible and will support in the future more customization if required.

**Comment by tjayrush** [comment]
This is excellent. I totally understand what you're doing. I wonder if I can ask for a small change.

This line

https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/tools/scripts/testCheck.py#L127

requires me to make two changes to initiate a customized test. I have to (a) place the customized file in the proper folder, and (b) make a change to the CMakeList.txt file. I would rather only have to do (a). So, for example, if there was an existing test called `whenBlock_test` then all I would have to do is put a file in ./test/custom_config/tools/whenBlocks/whenBlock_test and it would work. What it could do is make a list of existing files in the custom_config folder, backup those files (if found) in ~/.quickBlocks, copy the files, run the tests, then remove the custom files and replace the backup files.

I think you should be able to build the CUSTOM_FILES variable by listing whatever files you find in the custom folder. Allow for files that are not already present in the ~/.quickBlocks folder just in case a particular file is not already present.

**Comment by crodnun** [comment]
At ./src/CMakeLists.txt you have the following low level functions we defined long time ago:

run_the_test
run_the_special_test

But remember that you created wrappers for them at each individual CMakeLists.txt called:

run_test
run_special_test

If you want to create run_custom and run_custom_special, maybe it is worth/easier to create them individually at each level as you did with these ones.

Just cloning these functions and renaming them, I think that you will have the results you are looking for.

It is not the best solution, but should work doing it at each individual CMakeLists.txt where you want to work with customized tests. 

Let me know if it is the solution you want.

**Comment by tjayrush** [comment]
This works as I wish.
