### ISSUE TITLE
Re-direct tokenomics domain name to samples.quickblocks.io

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#532]
I own a domain name called tokenomics.io. I want it to point to http://samples.quickblocks.io. I have the login information, etc. for http://namecheap.com where I can assign the name servers. Can you please give me instructions here on how to make http://tokenomics.io resolve to the sample's site?

**Comment by crodnun** [comment]
Hi Thomas, I reviewed this issue and need your help to complete it.

To redirect a domain, you need to do the following steps (I will need your help for step 1):

1) Login into your domain provider and make the domain point to our staging server:  165.227.107.233

2)  Configure the staging server to point to the right directory that will serve this domain. This is s done using virtualhosts at apache. I will do it, no worries. Just ping me here when step done is ready.

I did a quick test and seems that this domain is not pointing to any IP address yet. If you do:

# **ping samples.quickblocks.io**
PING samples.quickblocks.io (**165.227.107.233**) 56(84) bytes of data.
64 bytes from ubuntu-2gb-nyc3-01 (165.227.107.233): icmp_seq=1 ttl=64 time=0.011 ms
64 bytes from ubuntu-2gb-nyc3-01 (165.227.107.233): icmp_seq=2 ttl=64 time=0.034 ms
64 bytes from ubuntu-2gb-nyc3-01 (165.227.107.233): icmp_seq=3 ttl=64 time=0.042 ms
64 bytes from ubuntu-2gb-nyc3-01 (165.227.107.233): icmp_seq=4 ttl=64 time=0.034 ms
^C
--- samples.quickblocks.io ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3058ms
rtt min/avg/max/mdev = 0.011/0.030/0.042/0.012 ms

# **ping staging.quickblocks.io**
PING staging.quickblocks.io (165.227.107.233) 56(84) bytes of data.
64 bytes from ubuntu-2gb-nyc3-01 (165.227.107.233): icmp_seq=1 ttl=64 time=0.011 ms
64 bytes from ubuntu-2gb-nyc3-01 (165.227.107.233): icmp_seq=2 ttl=64 time=0.034 ms
64 bytes from ubuntu-2gb-nyc3-01 (165.227.107.233): icmp_seq=3 ttl=64 time=0.034 ms
^C
--- staging.quickblocks.io ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2055ms
rtt min/avg/max/mdev = 0.011/0.026/0.034/0.011 ms

As you can the previous domains are pointing to our staging server, but when you try with the new one, seems not pointing to any address yet.


**# ping tokenomics.io**
**_ping: tokenomics.io: Temporary failure in name resolution_**

I need your help to complete this step and then I can continue from there.

**Comment by tjayrush** [comment]
It works now. Thanks. Closing this.
