### ISSUE TITLE
Header files interfere with other unrelated builds on Mac

### ISSUE THREAD

**Issue by songlinm** [Great-Hill-Corporation/quickBlocks#536]
quickBlock's installation appears to include putting lots of header files directly under folder /usr/local/include (as far as I can tell from install_manifest.txt). One particular file, "block.h", has been causing strange issues when I build other totally unrelated projects (specifically, a Rust 'Cargo' build).

One failure example is its follows.
```
[ 74%] Building C object CMakeFiles/git2.dir/src/tag.c.o

--- stderr
fatal: Not a git repository (or any of the parent directories): .git
-- Found Security /System/Library/Frameworks/Security.framework
-- Found CoreFoundation /System/Library/Frameworks/CoreFoundation.framework
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_CXX_COMPILER
    CMAKE_CXX_FLAGS


In file included from .cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.17/libgit2/src/stransport_stream.c:10:
In file included from /System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:43:
In file included from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:72:
In file included from /usr/local/include/Block.h:13:
In file included from /usr/local/include/ethtypes.h:10:
In file included from /usr/local/include/utillib.h:9:
/usr/local/include/basetypes.h:30:10: fatal error: 'algorithm' file not found
#include <algorithm>
         ^~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/git2.dir/src/stransport_stream.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/git2.dir/all] Error 2
make: *** [all] Error 2
```

These errors can be very confusing, i.e. the missing header is not actually missing, but is due to attempt to include a C++ header for a C source file. However,  the root cause is as follows

- The system header, "CFBase.h", attempts to include "Block.h", which should be resolved to /usr/include/Block.h
- However, quickBlock has put a file 'block.h' under directory /usr/local/include/
- As OS X's file system is case-insensitive, also, in this build, as /usr/local/include has precedence over /usr/include, quickBlock's header incorrectly replaces the system header.

Questions
- Rather than being directly placed under /usr/local/include, would it be better if all the quickBlock header files are managed by one directory under /usr/local/include, e.g. /usr/local/include/quickblock ? 
- Some of the installed header have names that can easily confuse developers. Examples include 'list.h', 'parameters.h', 'rpc.h'. It's very easy to mistake them for real system headers. Although, presumably this can be mitigated by the suggestion above.

**Comment by tjayrush** [comment]
Carlos, can you please look into this?

**Comment by crodnun** [comment]
I have added and small change at installation path policy, kindly check it at your side and let me know if it works now when installing. This change is pushed at develop branch so once tested we should make it available at master branch.

**Comment by tjayrush** [comment]
Thanks Carlos. I updated master branch, so @songlinm should be able to re-download and let us know if it works. Carlos--can you please point to the line you fixed with a link in a comment here?

**Comment by tjayrush** [comment]
@songlinm Please let us know if this fixed the problem, so we can close this issue. The install is supposed to install into /usr/local/qblocks folder.

**Comment by songlinm** [comment]
Many thanks for the fix. I have just tried a fresh build from a fresh clone. Interesting there appears to be an error I didn't encounter before:
```-- Establishing configuration folders at /Users/t/.quickBlocks
CMake Error at /Users/t/build/quickBlocks/src/other/install/qb_config.cmake:37 (file):
  file COPY cannot find
  "/Users/t/build/quickBlocks/build/other/install/../../../bin/makeClass".


make[2]: *** [other/install/CMakeFiles/qb_config] Error 1
make[1]: *** [other/install/CMakeFiles/qb_config.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 44%] Built target wallet
make: *** [all] Error 2
```

**Comment by tjayrush** [comment]
The path referenced above looks a bit odd. When you re-downloaded the code how did you do that? Did you do `git clone...` or `git pull`? The reason I'm asking is due to of the double occurrence of word `build` in the path. I just tried it on both Mac and Ubuntu and it seems to build fine. The more help you can give, the easier it will be for me to help you. Thanks.

**Comment by songlinm** [comment]
Thanks @tjayrush , Please ignore. I think the error was because I did a 'make -j2', which made the build run in parallel. It seems to work with a simple 'make'. 

Just tested "sudo make install". It appears to have fixed the original issue. @crodnun Many thanks for the fix!

**Comment by tjayrush** [comment]
Thanks.
