### ISSUE TITLE
I would like help to connect to infura

### ISSUE THREAD

**Issue by Xumtt** [Great-Hill-Corporation/quickBlocks#554]
I am very inexperienced in Linux, so I am not sure what I am doing wrong.  I want to connect to infura.  I am not running a local node.

I installed Fedora 27 and followed the installation instructions.  I added a quickblockspath.sh to etc/profile.d/ to add a path to /usr/local/qblocks/bin.

On line 98 of node_curl.cpp, I changed "https://pmainnet.infura.io/" to "https://mainnet.infura.io/<REMOVED>" (which is the API key infura gave me).  I then recompiled it with 
cmake ../src
make
sudo make install

This is the output from my terminal:

[root@localhost build]# getBlock 1234567

	Warning: The request to the Ethereum node resulted in
	following error message: Couldn't connect to server.
	It is impossible for QuickBlocks to proceed. Quitting...

[root@localhost build]# FALLBACK=infura getBlock 1234567

	Warning:The Ethereum node  resulted in an empty
	response. It is impossible forQuickBlocks to proceed. Quitting...

The second error message is exactly from node_curl.cpp (it has a double space after 'Ethereum' and no space between 'for' and 'QuickBlocks').

What do you suggest that I do?  Thank you in advance.

**Comment by tjayrush** [comment]
The first message is definitely because there was no running node at the localhost, so you were correct in trying to run with FALLBACK=infura.  I don't think you should have had to change the code (https://pmainnet.infura.io should be available for anyone to use). What happens when you put line 98 of node_curl.cpp back to what it was before?

Also -- are you using develop or master? I would use develop as master is a few commits behind. 

Also -- pull a fresh copy of the develop branch and then uncomment the commented line in curl_code.cpp that says //#define DEBUG_RPC. That won't help the problem but it should spit out a bunch more information to help understand what's going on.

Finally -- you seem to be comfortable changing code, so just go ahead and insert any 'cout << ' lines that will help you figuring it out.  Post any further information you get here (particularly the respond from the remote node).

My best guess about what's happening is that the URL you're using is returning no response and our code is doing a poor job of reporting the exact error.

Thanks for posting the bug report.

**Comment by Xumtt** [comment]
I got it to work.

I replaced https://pmainnet.infura.io back in node_curl.cpp
cmake ../src
make
sudo make install

[fedora@localhost build]$ getBlock 1234567

	Warning: The request to the Ethereum node resulted in
	following error message: Couldn't connect to server.
	It is impossible for QuickBlocks to proceed. Quitting...

[fedora@localhost build]$ FALLBACK=infura getBlock 1234567  //I wait two minutes for it to return
{
    "gasLimit": 0,
    "gasUsed": 0,
    "hash": "0x0",
    "blockNumber": 1234567,
    "parentHash": "0x0",
    "miner": "0x0",
    "difficulty": 0,
    "price": 0,
    "timestamp": 0,
    "transactions": []
}
[fedora@localhost build]$ FALLBACK=infura getBlock 2323456  //again, a wait
{
    "gasLimit": 0,
    "gasUsed": 0,
    "hash": "0x0",
    "blockNumber": 2323456,
    "parentHash": "0x0",
    "miner": "0x0",
    "difficulty": 0,
    "price": 0,
    "timestamp": 0,
    "transactions": []
}

I downloaded the code from github on January 21.
rm -rf quickBlocks
 Now I download the develop and install it.  In node_curl.cpp, I remove the "//" before the #define DEBUG_RPC

[root@localhost build]# getBlock 1234567
{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":"1"}

	Warning: The request to the Ethereum node resulted in
	following error message: Couldn't connect to server.
	It is impossible for QuickBlocks to proceed. Quitting...

[root@localhost build]# FALLBACK=infura getBlock 1234567
{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":"1"}
{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":"1"}
============================================================
received: {"jsonrpc":"2.0","result":"0x4d9302","id":1}

{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x12d687",true],"id":"2"}
============================================================
received: {"jsonrpc":"2.0","result":{"author":"0x2a65aca4d5fc5b5c859090a6c34d164135398226","difficulty":"0x1453ac042727","extraData":"0xd783010305844765746887676f312e352e31856c696e7578","gasLimit":"0x47e7c4","gasUsed":"0x0","hash":"0x19af4aa4e3bc592f8d5dc535a16b4bfc9732862957f36cfd49212009b968b838","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","miner":"0x2a65aca4d5fc5b5c859090a6c34d164135398226","mixHash":"0x053d612dcbde0d0a62e4b99b71d7bff12e4d173487a24a47781351ff5ce00f16","nonce":"0xd47631ed8ea8c2d0","number":"0x12d687","parentHash":"0xacc1728d558f47fc847b749e0972097fd7e95c6c96eadef06bd356c0cf248710","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","sealFields":["0xa0053d612dcbde0d0a62e4b99b71d7bff12e4d173487a24a47781351ff5ce00f16","0x88d47631ed8ea8c2d0"],"sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","size":"0x21d","stateRoot":"0xa167c5bb58f60cf1ca725c6024bec16b76ce62819c4e9ba403a1b58a38c1404c","timestamp":"0x56f989a5","totalDifficulty":"0x99a0deec1971f9b7","transactions":[],"transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","uncles":[]},"id":2}

{
    "gasLimit": 4712388,
    "gasUsed": 0,
    "hash": "0x19af4aa4e3bc592f8d5dc535a16b4bfc9732862957f36cfd49212009b968b838",
    "blockNumber": 1234567,
    "parentHash": "0xacc1728d558f47fc847b749e0972097fd7e95c6c96eadef06bd356c0cf248710",
    "miner": "0x2a65aca4d5fc5b5c859090a6c34d164135398226",
    "difficulty": 22349600794407,
    "price": 0,
    "finalized": 1,
    "timestamp": 1459194277,
    "transactions": []

It works.


I remember reading that getBalance didn't work with infura. 
[root@localhost tools]# FALLBACK=infura getBalance 0x1C751d421330734BEd2b8bF1abaFA94B9970894d
{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":"1"}
{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":"1"}
============================================================
received: {"jsonrpc":"2.0","result":"0x4d9320","id":1}

{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":"2"}
============================================================
received: {"jsonrpc":"2.0","result":"0x4d9320","id":2}

{"jsonrpc":"2.0","method":"eth_getBalance","params":["0x1C751d421330734BEd2b8bF1abaFA94B9970894d","5083936"],"id":"3"}
============================================================
received: {"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params: Invalid block number: missing 0x prefix."},"id":3}

    Balance for account 0x1C751d421330734BEd2b8bF1abaFA94B9970894d at block 5083936 is 0
[root@localhost tools]# 



ethSlurp seems to work with FALLBACK=infura. 
[root@localhost bin]# ethSlurp 0x6DD266B6CafE20750AF6C5b5b0bD5Ec16aac8963
Processing: 0x6DD266B6CafE20750AF6C5b5b0bD5Ec16aac8963
{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":"1"}

	Warning: The request to the Ethereum node resulted in
	following error message: Couldn't connect to server.
	It is impossible for QuickBlocks to proceed. Quitting...

[root@localhost bin]# FALLBACK=infura ethSlurp 0x6DD266B6CafE20750AF6C5b5b0bD5Ec16aac8963
Processing: 0x6DD266B6CafE20750AF6C5b5b0bD5Ec16aac8963
{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":"1"}
{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":"1"}
============================================================
received: {"jsonrpc":"2.0","result":"0x4d934b","id":1}


  ***Warning***
  This program needs an api_key from EtherScan in order to work. You may get one at
  http://etherscan.io/apis. See our online help file for more information.
  Please provide an API key or type 'exit'
  > 1GQN1A4DGB7S9D4XBIRXXYZDEPWMPE7M73
	Slurping 0x6dd266b6cafe20750af6c5b5b0bd5ec16aac8963
	Slurping new transactions from blockchain...
	Downloaded 10 potentially new transactions.
	Download contains blocks from 4263722 to 4866815
	Found new transaction at block 4866815. Importing...
	Writing 10 new records to cache
	Loaded 10 total records in 0.226070 seconds
	Filter passed 10 visible records of 10 in 1.00136e-05 seconds

        {
"hash":"0x906008dbfb1969df8a1856e0783083719c0c34d501ab453a5e0962e8e85e8dcd","blockHash":"0x3a3bced71fbecdcf710eccf620db97e3ce9fc580a62a3b47b0650e69c6dd04eb","blockNumber":"4263722","transactionIndex":"179","nonce":"0","timestamp":"1505166388","from":"0x7c4d20c6841536391d30dc0570ab12b2016b885f","to":"0x6dd266b6cafe20750af6c5b5b0bd5ec16aac8963","value":"100000000000000000","gas":"90000","gasPrice":"21000000000","input":"0x","isError":"0","isInternal":"0","gasUsed":"21000","date":"2017-09-11 21:46:28 UTC","ether":"0.100000000000000000"
        },
        {
"hash":"0xa98d2a2b97a74d55ee8a3b6e18fd6ac9fe322a7394ceaf93b3536335e67d3858","blockHash":"0xab06e7be703b48811b52ea2a14fcbc9575bd7fc217b00df5dcb89580db6c353f","blockNumber":"4331818","transactionIndex":"71","nonce":"0","timestamp":"1506990780","from":"0x6dd266b6cafe20750af6c5b5b0bd5ec16aac8963","to":"0x8d12a197cb00d4747a1fe03395095ce2a5cc6819","value":"90000000000000000","gas":"250000","gasPrice":"8000000000","input":"0xd0e30db0","isError":"0","isInternal":"0","gasUsed":"44493","date":"2017-10-03 00:33:00 UTC","ether":"0.090000000000000000"
        },
        {
"hash":"0x47b282bb3f1165fed3db42d78bf85ff08b797407452acafff061acfa69ee0035","blockHash":"0xb9bb755d7863f3ee1febac6ede86687631b47f7ab0403b0eb6d8d23d09156f1a","blockNumber":"4577870","transactionIndex":"6","nonce":"1","timestamp":"1511036398","from":"0x6dd266b6cafe20750af6c5b5b0bd5ec16aac8963","to":"0x8d12a197cb00d4747a1fe03395095ce2a5cc6819","value":"0","gas":"250000","gasPrice":"4000000000","input":"0x0a19b14a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001b2cc8252d6100000000000000000000000000000d8775f648430679a709e98d2b0cb6250d2887ef0000000000000000000000000000000000000000000000ce1707f3b46c080000000000000000000000000000000000000000000000000000000000000045da9200000000000000000000000000000000000000000000000000000000b0fc658b0000000000000000000000009c17e14768936a8f17f5ffa343e825ad2da745da000000000000000000000000000000000000000000000000000000000000001c136448b66dd18540d5848be7a59064512ff85f5a7d12f97b789ffe483ebc07ed3e60deff5f9498eefcd964aa033de20cbb9def18c5cd6678f66e25b20b6bc5cd0000000000000000000000000000000000000000000000000001d4758ead00cd","isError":"0","isInternal":"0","gasUsed":"108050","date":"2017-11-18 20:19:58 UTC","ether":"0.000000000000000000"
        },
        {
"hash":"0x26965d5cee36f805fcea0938bd391e2836024bff5808cdc22696bb4f7be3e732","blockHash":"0xb9bb755d7863f3ee1febac6ede86687631b47f7ab0403b0eb6d8d23d09156f1a","blockNumber":"4577870","transactionIndex":"7","nonce":"2","timestamp":"1511036398","from":"0x6dd266b6cafe20750af6c5b5b0bd5ec16aac8963","to":"0x8d12a197cb00d4747a1fe03395095ce2a5cc6819","value":"0","gas":"250000","gasPrice":"8000000000","input":"0x0a19b14a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000251d85029d1880000000000000000000000000000d8775f648430679a709e98d2b0cb6250d2887ef0000000000000000000000000000000000000000000000a991b863254de000000000000000000000000000000000000000000000000000000000000000423f260000000000000000000000000000000000000000000000000000000067b9ea0f0000000000000000000000004cd4d9485c27f23932b625e87e23afa0ebed958a000000000000000000000000000000000000000000000000000000000000001c4a205185b7f91a8d0bc8f6209cd6122b8ccf462b3145d675b6f14378d73616a33f4a7fdf5f67ca4024ff40f6a7151d06f81e5fe839b3a71585be30d2558fa0870000000000000000000000000000000000000000000000000003099e33487000","isError":"1","isInternal":"0","gasUsed":"250000","date":"2017-11-18 20:19:58 UTC","ether":"0.000000000000000000"
        },
        {
"hash":"0x11afadcff9df2a64fa1422eea5bc8884849cb59c82debac1bdda3007f7edf976","blockHash":"0x317cf0aaaff0268e0f07471a4cffd4954dfea36f886de3b06310d4004807f157","blockNumber":"4782933","transactionIndex":"184","nonce":"3","timestamp":"1514037981","from":"0x6dd266b6cafe20750af6c5b5b0bd5ec16aac8963","to":"0x8d12a197cb00d4747a1fe03395095ce2a5cc6819","value":"0","gas":"250000","gasPrice":"4000000000","input":"0x9e281a980000000000000000000000000d8775f648430679a709e98d2b0cb6250d2887ef0000000000000000000000000000000000000000000000000de0b6b3a763f9e5","isError":"0","isInternal":"0","gasUsed":"47869","date":"2017-12-23 14:06:21 UTC","ether":"0.000000000000000000"
        },
        {
"hash":"0x6bbb17ee6c8c4ff3ed68039a439ee64d4137ef01438c3be1c3a7a016be1d9ca8","blockHash":"0xf0bcb49b975f94ceb8d47beb77d239fc2cf402861f41f36b76864a7b879b5228","blockNumber":"4782947","transactionIndex":"83","nonce":"4","timestamp":"1514038234","from":"0x6dd266b6cafe20750af6c5b5b0bd5ec16aac8963","to":"0x0d8775f648430679a709e98d2b0cb6250d2887ef","value":"0","gas":"250000","gasPrice":"4000000000","input":"0xa9059cbb00000000000000000000000004e3bb257af6735cc1811fec50a48fe28568b0d60000000000000000000000000000000000000000000000000de0b6b3a763f9e5","isError":"0","isInternal":"0","gasUsed":"36916","date":"2017-12-23 14:10:34 UTC","ether":"0.000000000000000000"
        },
        {
"hash":"0x76d0ef10a150e23047fa9f8841805438de48d355e28225c8fd5b21cfc07b35bc","blockHash":"0x18972f994778a8ff432a052bf843293556aa529030c6b3196519de28e8de9c9f","blockNumber":"4825726","transactionIndex":"142","nonce":"5","timestamp":"1514662652","from":"0x6dd266b6cafe20750af6c5b5b0bd5ec16aac8963","to":"0x8d12a197cb00d4747a1fe03395095ce2a5cc6819","value":"0","gas":"250000","gasPrice":"4000000000","input":"0x0a19b14a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001c3a8e8c3f6f1cf00000000000000000000000000d8775f648430679a709e98d2b0cb6250d2887ef0000000000000000000000000000000000000000000000dc89968fb1e1584bf5000000000000000000000000000000000000000000000000000000000049a2910000000000000000000000000000000000000000000000000010ca6f82978f6d000000000000000000000000955051f2cf3ba245ae8ee9057458836eae3b1fec000000000000000000000000000000000000000000000000000000000000001cd70df80fab58ac98258e8c2744984084b385d0e9dc1a739a52e4ebf0fd29ea9558818ea61963320005111b26658873520db7b89dce45ac94088c1df853f8ff3c00000000000000000000000000000000000000000000000000b1a2a4e64e17fc","isError":"0","isInternal":"0","gasUsed":"108498","date":"2017-12-30 19:37:32 UTC","ether":"0.000000000000000000"
        },
        {
"hash":"0x57db94100edc35472c7d64a18900519306eb9be1ba3a877ed03cfd7491175ac1","blockHash":"0xc77ae4dca71f202241a90cc6be1147bb4a7cdf7a6b2010e1371f5588f352125b","blockNumber":"4825742","transactionIndex":"21","nonce":"6","timestamp":"1514662851","from":"0x6dd266b6cafe20750af6c5b5b0bd5ec16aac8963","to":"0x8d12a197cb00d4747a1fe03395095ce2a5cc6819","value":"0","gas":"250000","gasPrice":"4000000000","input":"0x9e281a980000000000000000000000000d8775f648430679a709e98d2b0cb6250d2887ef0000000000000000000000000000000000000000000000056bc75e2d630ff841","isError":"0","isInternal":"0","gasUsed":"47933","date":"2017-12-30 19:40:51 UTC","ether":"0.000000000000000000"
        },
        {
"hash":"0xf23a85e6b478b6c004dd81d1dc99afc81e2191c75b58b613eac0633fb513c2f1","blockHash":"0xb32bbc20631e2e4243d1a58d096d28779acb578dccd05ba1c85cccbc183dac97","blockNumber":"4825749","transactionIndex":"76","nonce":"7","timestamp":"1514662946","from":"0x6dd266b6cafe20750af6c5b5b0bd5ec16aac8963","to":"0x0d8775f648430679a709e98d2b0cb6250d2887ef","value":"0","gas":"250000","gasPrice":"4000000000","input":"0xa9059cbb00000000000000000000000004e3bb257af6735cc1811fec50a48fe28568b0d6000000000000000000000000000000000000000000000002b5e3af16b1880000","isError":"0","isInternal":"0","gasUsed":"36852","date":"2017-12-30 19:42:26 UTC","ether":"0.000000000000000000"
        },
        {
"hash":"0x77d78540504c23f82f816b656962ff0f799745b6f1f4758740d16d89ef423fa9","blockHash":"0x6e3473c41bd1b9cd4aa78e4de469f518aaf065b2cdb5ee5f845e576126b5d19a","blockNumber":"4866815","transactionIndex":"19","nonce":"8","timestamp":"1515294661","from":"0x6dd266b6cafe20750af6c5b5b0bd5ec16aac8963","to":"0x8d12a197cb00d4747a1fe03395095ce2a5cc6819","value":"0","gas":"250000","gasPrice":"15000000000","input":"0x2e1a7d4d000000000000000000000000000000000000000000000000008a8e4b1a3d8000","isError":"0","isInternal":"0","gasUsed":"37900","date":"2018-01-07 03:11:01 UTC","ether":"0.000000000000000000"

**Comment by tjayrush** [comment]
Ethslurp will always work because it only looks at the Etherscan API, so FALLBACK or not, it will return data. The trouble is, it only returns external transactions.

getBalance works with Infura, but only for recent blocks. If you do `getBalance 0x2302409....` it will return the balance for the most recent block. If you do `getBalance 0x2302409.... 3000000` (asking for the balance at the 3,000,000 block, it will always return zero since Infura does not store historical balances.

It looks like you're getting data, so does it work? It looks like it does.
