### ISSUE TITLE
Etherlib access blockchain files

### ISSUE THREAD

**Issue by smartmapping** [Great-Hill-Corporation/quickBlocks#574]
etherlib_init function currently access block chain through an ethereum client. Does this implementation support accessing files of blockchain data

**Comment by tjayrush** [comment]
An Ethereum client must be present in order for QuickBlocks to work. That client is best if it is on the same machine as QuickBlocks is running, but QuickBlocks can also use remote nodes (such as Infura or QuickNode). 

When you say "...support accessing files of blockchain data..." I'm not exactly clear what you mean. Can you elaborate?

**Comment by tjayrush** [comment]
Are you asking if it reads the node's database files directly? If that's what you're asking, then "No." It does not. We did this on purpose to avoid the situation where the internal storage of the node is modified and thereby breaks our code. I am going to close this. If you were asking something else, please re-open and elaborate.
