### ISSUE TITLE
Compilation of utillib/memmap.cpp fails with error: ‘invalid_argument’ is not a member of ‘std’

### ISSUE THREAD

**Issue by Sirverik** [Great-Hill-Corporation/quickBlocks#577]
"#include \<stdexcept\>" is missing in memmap.cpp, throws error during quickblocks installation.

**Comment by tjayrush** [comment]
What operating system are you compiling on? What commands did you use to compile?

**Comment by Sirverik** [comment]
Debian Jessie, and I compiled with make, according to the instructions. Adding #include \<stdexcep\t> to the file fixed the problem.

**Comment by Sirverik** [comment]
This issue is not present when attempting installation in ubuntu 16.04

**Comment by tjayrush** [comment]
This is fixed.
