### ISSUE TITLE
Open-source friendly

### ISSUE THREAD

**Issue by wildmolasses** [Great-Hill-Corporation/quickBlocks#581]
Because we plan on open-sourcing this QuickBlocks repo, I'll make a CONTRIBUTING.md that's as nice as [Brave browser's](https://github.com/brave/browser-laptop/blob/master/CONTRIBUTING.md).

[This article](https://medium.com/gitcoin/tutorial-leverage-gitcoins-firehose-of-talent-to-do-more-faster-dcd39650fc5) about gitcoin bounties is a gem; many items on this list apply to any task, with or without a bounty (provide acceptance criteria, over-communicate, etc).

- [ ] README.md
- [ ] CONTRIBUTING.md
- [ ] Branch/release pattern
- [ ] Formalize a communication standard

**Comment by tjayrush** [comment]
Delayed to Mermaid release. Closing, but will re-open.

**Comment by tjayrush** [comment]
Reorganizing all issues, therefore closing this one.
