### ISSUE TITLE
"Missing vtable" error when compiling simple.cpp

### ISSUE THREAD

**Issue by toro09** [Great-Hill-Corporation/quickBlocks#610]
New here. Tried compiling the simple.cpp file included. Keep getting the following error:

Stephens-MacBook-Pro:quickBlocks toro$ g++ -Wall -std=c++17 simple.cpp
Undefined symbols for architecture x86_64:
  "qblocks::CNameValue::finishParse()", referenced from:
      vtable for qblocks::CNameValue in simple-94f0bb.o
  "qblocks::CNameValue::readBackLevel(qblocks::SFArchive&)", referenced from:
      vtable for qblocks::CNameValue in simple-94f0bb.o
  "qblocks::CNameValue::setValueByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      vtable for qblocks::CNameValue in simple-94f0bb.o
  "qblocks::CNameValue::Serialize(qblocks::SFArchive&)", referenced from:
      vtable for qblocks::CNameValue in simple-94f0bb.o
  "qblocks::CParameter::finishParse()", referenced from:
      vtable for qblocks::CParameter in simple-94f0bb.o
  "qblocks::CParameter::readBackLevel(qblocks::SFArchive&)", referenced from:
      vtable for qblocks::CParameter in simple-94f0bb.o
  "qblocks::CParameter::setValueByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      vtable for qblocks::CParameter in simple-94f0bb.o
  "qblocks::CParameter::Serialize(qblocks::SFArchive&)", referenced from:
      vtable for qblocks::CParameter in simple-94f0bb.o
  "qblocks::CRPCResult::finishParse()", referenced from:
      vtable for qblocks::CRPCResult in simple-94f0bb.o
  "qblocks::CRPCResult::readBackLevel(qblocks::SFArchive&)", referenced from:
      vtable for qblocks::CRPCResult in simple-94f0bb.o
  "qblocks::CRPCResult::setValueByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      vtable for qblocks::CRPCResult in simple-94f0bb.o
  "qblocks::CRPCResult::Serialize(qblocks::SFArchive&)", referenced from:
      vtable for qblocks::CRPCResult in simple-94f0bb.o
  "qblocks::CPriceQuote::finishParse()", referenced from:
      vtable for qblocks::CPriceQuote in simple-94f0bb.o
  "qblocks::CPriceQuote::readBackLevel(qblocks::SFArchive&)", referenced from:
      vtable for qblocks::CPriceQuote in simple-94f0bb.o
  "qblocks::CPriceQuote::setValueByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      vtable for qblocks::CPriceQuote in simple-94f0bb.o
  "qblocks::CPriceQuote::Serialize(qblocks::SFArchive&)", referenced from:
      vtable for qblocks::CPriceQuote in simple-94f0bb.o
  "qblocks::CAccountName::finishParse()", referenced from:
      vtable for qblocks::CAccountName in simple-94f0bb.o
  "qblocks::CAccountName::readBackLevel(qblocks::SFArchive&)", referenced from:
      vtable for qblocks::CAccountName in simple-94f0bb.o
  "qblocks::CAccountName::setValueByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      vtable for qblocks::CAccountName in simple-94f0bb.o
  "qblocks::CAccountName::Serialize(qblocks::SFArchive&)", referenced from:
      vtable for qblocks::CAccountName in simple-94f0bb.o
  "qblocks::CTraceAction::finishParse()", referenced from:
      vtable for qblocks::CTraceAction in simple-94f0bb.o
  "qblocks::CTraceAction::readBackLevel(qblocks::SFArchive&)", referenced from:
      vtable for qblocks::CTraceAction in simple-94f0bb.o
  "qblocks::CTraceAction::setValueByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      vtable for qblocks::CTraceAction in simple-94f0bb.o
  "qblocks::CTraceAction::Serialize(qblocks::SFArchive&)", referenced from:
      vtable for qblocks::CTraceAction in simple-94f0bb.o
  "qblocks::CTraceResult::finishParse()", referenced from:
      vtable for qblocks::CTraceResult in simple-94f0bb.o
  "qblocks::CTraceResult::readBackLevel(qblocks::SFArchive&)", referenced from:
      vtable for qblocks::CTraceResult in simple-94f0bb.o
  "qblocks::CTraceResult::setValueByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      vtable for qblocks::CTraceResult in simple-94f0bb.o
  "qblocks::CTraceResult::Serialize(qblocks::SFArchive&)", referenced from:
      vtable for qblocks::CTraceResult in simple-94f0bb.o
  "qblocks::CTransaction::finishParse()", referenced from:
      vtable for qblocks::CTransaction in simple-94f0bb.o
  "qblocks::CTransaction::readBackLevel(qblocks::SFArchive&)", referenced from:
      vtable for qblocks::CTransaction in simple-94f0bb.o
  "qblocks::CTransaction::setValueByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      vtable for qblocks::CTransaction in simple-94f0bb.o
  "qblocks::CTransaction::Serialize(qblocks::SFArchive&)", referenced from:
      vtable for qblocks::CTransaction in simple-94f0bb.o
  "qblocks::etherlib_init(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void (*)(int))", referenced from:
      _main in simple-94f0bb.o
  "qblocks::CExportContext::CExportContext()", referenced from:
      qblocks::CStringExportContext::CStringExportContext() in simple-94f0bb.o
  "qblocks::defaultQuitHandler(int)", referenced from:
      _main in simple-94f0bb.o
  "qblocks::CAbi::finishParse()", referenced from:
      vtable for qblocks::CAbi in simple-94f0bb.o
  "qblocks::CAbi::readBackLevel(qblocks::SFArchive&)", referenced from:
      vtable for qblocks::CAbi in simple-94f0bb.o
  "qblocks::CAbi::setValueByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      vtable for qblocks::CAbi in simple-94f0bb.o
  "qblocks::CAbi::Serialize(qblocks::SFArchive&)", referenced from:
      vtable for qblocks::CAbi in simple-94f0bb.o
  "qblocks::CBlock::finishParse()", referenced from:
      vtable for qblocks::CBlock in simple-94f0bb.o
  "qblocks::CBlock::readBackLevel(qblocks::SFArchive&)", referenced from:
      vtable for qblocks::CBlock in simple-94f0bb.o
  "qblocks::CBlock::setValueByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      vtable for qblocks::CBlock in simple-94f0bb.o
  "qblocks::CBlock::Serialize(qblocks::SFArchive&)", referenced from:
      vtable for qblocks::CBlock in simple-94f0bb.o
  "qblocks::CTrace::finishParse()", referenced from:
      vtable for qblocks::CTrace in simple-94f0bb.o
  "qblocks::CTrace::readBackLevel(qblocks::SFArchive&)", referenced from:
      vtable for qblocks::CTrace in simple-94f0bb.o
  "qblocks::CTrace::setValueByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      vtable for qblocks::CTrace in simple-94f0bb.o
  "qblocks::CTrace::Serialize(qblocks::SFArchive&)", referenced from:
      vtable for qblocks::CTrace in simple-94f0bb.o
  "qblocks::CReceipt::finishParse()", referenced from:
      vtable for qblocks::CReceipt in simple-94f0bb.o
  "qblocks::CReceipt::readBackLevel(qblocks::SFArchive&)", referenced from:
      vtable for qblocks::CReceipt in simple-94f0bb.o
  "qblocks::CReceipt::setValueByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      vtable for qblocks::CReceipt in simple-94f0bb.o
  "qblocks::CReceipt::Serialize(qblocks::SFArchive&)", referenced from:
      vtable for qblocks::CReceipt in simple-94f0bb.o
  "qblocks::SFUintBN::~SFUintBN()", referenced from:
      qblocks::CTraceAction::~CTraceAction() in simple-94f0bb.o
      qblocks::CTransaction::~CTransaction() in simple-94f0bb.o
      std::__1::__vector_base<qblocks::SFUintBN, std::__1::allocator<qblocks::SFUintBN> >::~__vector_base() in simple-94f0bb.o
  "qblocks::getBlock(qblocks::CBlock&, unsigned long long)", referenced from:
      _main in simple-94f0bb.o
  "qblocks::CBaseNode::initialize()", referenced from:
      qblocks::CBlock::initialize() in simple-94f0bb.o
  "qblocks::CBaseNode::parseCSV(char*, unsigned long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const*)", referenced from:
      vtable for qblocks::CNameValue in simple-94f0bb.o
      vtable for qblocks::CAccountName in simple-94f0bb.o
      vtable for qblocks::CParameter in simple-94f0bb.o
      vtable for qblocks::CFunction in simple-94f0bb.o
      vtable for qblocks::CAbi in simple-94f0bb.o
      vtable for qblocks::CLogEntry in simple-94f0bb.o
      vtable for qblocks::CReceipt in simple-94f0bb.o
      ...
  "qblocks::CBaseNode::parseJson(char*)", referenced from:
      vtable for qblocks::CNameValue in simple-94f0bb.o
      vtable for qblocks::CAccountName in simple-94f0bb.o
      vtable for qblocks::CParameter in simple-94f0bb.o
      vtable for qblocks::CFunction in simple-94f0bb.o
      vtable for qblocks::CAbi in simple-94f0bb.o
      vtable for qblocks::CLogEntry in simple-94f0bb.o
      vtable for qblocks::CReceipt in simple-94f0bb.o
      ...
  "qblocks::CBaseNode::parseJson(char*, unsigned long&)", referenced from:
      vtable for qblocks::CNameValue in simple-94f0bb.o
      vtable for qblocks::CAccountName in simple-94f0bb.o
      vtable for qblocks::CParameter in simple-94f0bb.o
      vtable for qblocks::CFunction in simple-94f0bb.o
      vtable for qblocks::CAbi in simple-94f0bb.o
      vtable for qblocks::CLogEntry in simple-94f0bb.o
      vtable for qblocks::CReceipt in simple-94f0bb.o
      ...
  "qblocks::CBaseNode::parseText(char*, unsigned long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const*)", referenced from:
      vtable for qblocks::CNameValue in simple-94f0bb.o
      vtable for qblocks::CAccountName in simple-94f0bb.o
      vtable for qblocks::CParameter in simple-94f0bb.o
      vtable for qblocks::CFunction in simple-94f0bb.o
      vtable for qblocks::CAbi in simple-94f0bb.o
      vtable for qblocks::CLogEntry in simple-94f0bb.o
      vtable for qblocks::CReceipt in simple-94f0bb.o
      ...
  "qblocks::CBaseNode::CBaseNode()", referenced from:
      qblocks::CBlock::CBlock() in simple-94f0bb.o
  "qblocks::CBaseNode::~CBaseNode()", referenced from:
      qblocks::CNameValue::~CNameValue() in simple-94f0bb.o
      qblocks::CAccountName::~CAccountName() in simple-94f0bb.o
      qblocks::CParameter::~CParameter() in simple-94f0bb.o
      qblocks::CFunction::~CFunction() in simple-94f0bb.o
      qblocks::CAbi::~CAbi() in simple-94f0bb.o
      qblocks::CLogEntry::~CLogEntry() in simple-94f0bb.o
      qblocks::CReceipt::~CReceipt() in simple-94f0bb.o
      ...
  "qblocks::CFunction::finishParse()", referenced from:
      vtable for qblocks::CFunction in simple-94f0bb.o
  "qblocks::CFunction::readBackLevel(qblocks::SFArchive&)", referenced from:
      vtable for qblocks::CFunction in simple-94f0bb.o
  "qblocks::CFunction::setValueByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      vtable for qblocks::CFunction in simple-94f0bb.o
  "qblocks::CFunction::Serialize(qblocks::SFArchive&)", referenced from:
      vtable for qblocks::CFunction in simple-94f0bb.o
  "qblocks::CLogEntry::finishParse()", referenced from:
      vtable for qblocks::CLogEntry in simple-94f0bb.o
  "qblocks::CLogEntry::readBackLevel(qblocks::SFArchive&)", referenced from:
      vtable for qblocks::CLogEntry in simple-94f0bb.o
  "qblocks::CLogEntry::setValueByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      vtable for qblocks::CLogEntry in simple-94f0bb.o
  "qblocks::CLogEntry::Serialize(qblocks::SFArchive&)", referenced from:
      vtable for qblocks::CLogEntry in simple-94f0bb.o
  "qblocks::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, qblocks::CBlock const&)", referenced from:
      _main in simple-94f0bb.o
  "qblocks::CNameValue::SerializeC(qblocks::SFArchive&) const", referenced from:
      vtable for qblocks::CNameValue in simple-94f0bb.o
  "qblocks::CNameValue::getValueByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
      vtable for qblocks::CNameValue in simple-94f0bb.o
  "qblocks::CNameValue::getRuntimeClass() const", referenced from:
      vtable for qblocks::CNameValue in simple-94f0bb.o
  "qblocks::CNameValue::Format(qblocks::CExportContext&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void*) const", referenced from:
      vtable for qblocks::CNameValue in simple-94f0bb.o
  "qblocks::CParameter::SerializeC(qblocks::SFArchive&) const", referenced from:
      vtable for qblocks::CParameter in simple-94f0bb.o
  "qblocks::CParameter::getValueByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
      vtable for qblocks::CParameter in simple-94f0bb.o
  "qblocks::CParameter::getRuntimeClass() const", referenced from:
      vtable for qblocks::CParameter in simple-94f0bb.o
  "qblocks::CParameter::Format(qblocks::CExportContext&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void*) const", referenced from:
      vtable for qblocks::CParameter in simple-94f0bb.o
  "qblocks::CRPCResult::SerializeC(qblocks::SFArchive&) const", referenced from:
      vtable for qblocks::CRPCResult in simple-94f0bb.o
  "qblocks::CRPCResult::getValueByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
      vtable for qblocks::CRPCResult in simple-94f0bb.o
  "qblocks::CRPCResult::getRuntimeClass() const", referenced from:
      vtable for qblocks::CRPCResult in simple-94f0bb.o
  "qblocks::CRPCResult::Format(qblocks::CExportContext&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void*) const", referenced from:
      vtable for qblocks::CRPCResult in simple-94f0bb.o
  "qblocks::CPriceQuote::SerializeC(qblocks::SFArchive&) const", referenced from:
      vtable for qblocks::CPriceQuote in simple-94f0bb.o
  "qblocks::CPriceQuote::getValueByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
      vtable for qblocks::CPriceQuote in simple-94f0bb.o
  "qblocks::CPriceQuote::getRuntimeClass() const", referenced from:
      vtable for qblocks::CPriceQuote in simple-94f0bb.o
  "qblocks::CPriceQuote::Format(qblocks::CExportContext&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void*) const", referenced from:
      vtable for qblocks::CPriceQuote in simple-94f0bb.o
  "qblocks::CAccountName::SerializeC(qblocks::SFArchive&) const", referenced from:
      vtable for qblocks::CAccountName in simple-94f0bb.o
  "qblocks::CAccountName::getValueByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
      vtable for qblocks::CAccountName in simple-94f0bb.o
  "qblocks::CAccountName::getRuntimeClass() const", referenced from:
      vtable for qblocks::CAccountName in simple-94f0bb.o
  "qblocks::CAccountName::Format(qblocks::CExportContext&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void*) const", referenced from:
      vtable for qblocks::CAccountName in simple-94f0bb.o
  "qblocks::CTraceAction::SerializeC(qblocks::SFArchive&) const", referenced from:
      vtable for qblocks::CTraceAction in simple-94f0bb.o
  "qblocks::CTraceAction::getValueByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
      vtable for qblocks::CTraceAction in simple-94f0bb.o
  "qblocks::CTraceAction::getRuntimeClass() const", referenced from:
      vtable for qblocks::CTraceAction in simple-94f0bb.o
  "qblocks::CTraceAction::Format(qblocks::CExportContext&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void*) const", referenced from:
      vtable for qblocks::CTraceAction in simple-94f0bb.o
  "qblocks::CTraceResult::SerializeC(qblocks::SFArchive&) const", referenced from:
      vtable for qblocks::CTraceResult in simple-94f0bb.o
  "qblocks::CTraceResult::getValueByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
      vtable for qblocks::CTraceResult in simple-94f0bb.o
  "qblocks::CTraceResult::getRuntimeClass() const", referenced from:
      vtable for qblocks::CTraceResult in simple-94f0bb.o
  "qblocks::CTraceResult::Format(qblocks::CExportContext&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void*) const", referenced from:
      vtable for qblocks::CTraceResult in simple-94f0bb.o
  "qblocks::CTransaction::SerializeC(qblocks::SFArchive&) const", referenced from:
      vtable for qblocks::CTransaction in simple-94f0bb.o
  "qblocks::CTransaction::getObjectAt(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) const", referenced from:
      vtable for qblocks::CTransaction in simple-94f0bb.o
  "qblocks::CTransaction::getValueByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
      vtable for qblocks::CTransaction in simple-94f0bb.o
  "qblocks::CTransaction::getRuntimeClass() const", referenced from:
      vtable for qblocks::CTransaction in simple-94f0bb.o
  "qblocks::CTransaction::Format(qblocks::CExportContext&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void*) const", referenced from:
      vtable for qblocks::CTransaction in simple-94f0bb.o
  "qblocks::CAbi::SerializeC(qblocks::SFArchive&) const", referenced from:
      vtable for qblocks::CAbi in simple-94f0bb.o
  "qblocks::CAbi::getObjectAt(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) const", referenced from:
      vtable for qblocks::CAbi in simple-94f0bb.o
  "qblocks::CAbi::getValueByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
      vtable for qblocks::CAbi in simple-94f0bb.o
  "qblocks::CAbi::getRuntimeClass() const", referenced from:
      vtable for qblocks::CAbi in simple-94f0bb.o
  "qblocks::CAbi::Format(qblocks::CExportContext&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void*) const", referenced from:
      vtable for qblocks::CAbi in simple-94f0bb.o
  "qblocks::CBlock::SerializeC(qblocks::SFArchive&) const", referenced from:
      vtable for qblocks::CBlock in simple-94f0bb.o
  "qblocks::CBlock::getObjectAt(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) const", referenced from:
      vtable for qblocks::CBlock in simple-94f0bb.o
  "qblocks::CBlock::getValueByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
      vtable for qblocks::CBlock in simple-94f0bb.o
  "qblocks::CBlock::getRuntimeClass() const", referenced from:
      vtable for qblocks::CBlock in simple-94f0bb.o
  "qblocks::CBlock::Format(qblocks::CExportContext&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void*) const", referenced from:
      vtable for qblocks::CBlock in simple-94f0bb.o
  "qblocks::CTrace::SerializeC(qblocks::SFArchive&) const", referenced from:
      vtable for qblocks::CTrace in simple-94f0bb.o
  "qblocks::CTrace::getObjectAt(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) const", referenced from:
      vtable for qblocks::CTrace in simple-94f0bb.o
  "qblocks::CTrace::getStringAt(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) const", referenced from:
      vtable for qblocks::CTrace in simple-94f0bb.o
  "qblocks::CTrace::getValueByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
      vtable for qblocks::CTrace in simple-94f0bb.o
  "qblocks::CTrace::getRuntimeClass() const", referenced from:
      vtable for qblocks::CTrace in simple-94f0bb.o
  "qblocks::CTrace::Format(qblocks::CExportContext&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void*) const", referenced from:
      vtable for qblocks::CTrace in simple-94f0bb.o
  "qblocks::CReceipt::SerializeC(qblocks::SFArchive&) const", referenced from:
      vtable for qblocks::CReceipt in simple-94f0bb.o
  "qblocks::CReceipt::getObjectAt(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) const", referenced from:
      vtable for qblocks::CReceipt in simple-94f0bb.o
  "qblocks::CReceipt::getValueByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
      vtable for qblocks::CReceipt in simple-94f0bb.o
  "qblocks::CReceipt::getRuntimeClass() const", referenced from:
      vtable for qblocks::CReceipt in simple-94f0bb.o
  "qblocks::CReceipt::Format(qblocks::CExportContext&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void*) const", referenced from:
      vtable for qblocks::CReceipt in simple-94f0bb.o
  "qblocks::CBaseNode::jsonFromArray(std::__1::vector<qblocks::CFieldData, std::__1::allocator<qblocks::CFieldData> > const&) const", referenced from:
      vtable for qblocks::CNameValue in simple-94f0bb.o
      vtable for qblocks::CAccountName in simple-94f0bb.o
      vtable for qblocks::CParameter in simple-94f0bb.o
      vtable for qblocks::CFunction in simple-94f0bb.o
      vtable for qblocks::CAbi in simple-94f0bb.o
      vtable for qblocks::CLogEntry in simple-94f0bb.o
      vtable for qblocks::CReceipt in simple-94f0bb.o
      ...
  "qblocks::CBaseNode::toJson(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
      vtable for qblocks::CNameValue in simple-94f0bb.o
      vtable for qblocks::CAccountName in simple-94f0bb.o
      vtable for qblocks::CParameter in simple-94f0bb.o
      vtable for qblocks::CFunction in simple-94f0bb.o
      vtable for qblocks::CAbi in simple-94f0bb.o
      vtable for qblocks::CLogEntry in simple-94f0bb.o
      vtable for qblocks::CReceipt in simple-94f0bb.o
      ...
  "qblocks::CBaseNode::toJson() const", referenced from:
      vtable for qblocks::CNameValue in simple-94f0bb.o
      vtable for qblocks::CAccountName in simple-94f0bb.o
      vtable for qblocks::CParameter in simple-94f0bb.o
      vtable for qblocks::CFunction in simple-94f0bb.o
      vtable for qblocks::CAbi in simple-94f0bb.o
      vtable for qblocks::CLogEntry in simple-94f0bb.o
      vtable for qblocks::CReceipt in simple-94f0bb.o
      ...
  "qblocks::CBaseNode::toJson1() const", referenced from:
      vtable for qblocks::CNameValue in simple-94f0bb.o
      vtable for qblocks::CAccountName in simple-94f0bb.o
      vtable for qblocks::CParameter in simple-94f0bb.o
      vtable for qblocks::CFunction in simple-94f0bb.o
      vtable for qblocks::CAbi in simple-94f0bb.o
      vtable for qblocks::CLogEntry in simple-94f0bb.o
      vtable for qblocks::CReceipt in simple-94f0bb.o
      ...
  "qblocks::CBaseNode::isKindOf(qblocks::CRuntimeClass const*) const", referenced from:
      vtable for qblocks::CNameValue in simple-94f0bb.o
      vtable for qblocks::CAccountName in simple-94f0bb.o
      vtable for qblocks::CParameter in simple-94f0bb.o
      vtable for qblocks::CFunction in simple-94f0bb.o
      vtable for qblocks::CAbi in simple-94f0bb.o
      vtable for qblocks::CLogEntry in simple-94f0bb.o
      vtable for qblocks::CReceipt in simple-94f0bb.o
      ...
  "qblocks::CFunction::SerializeC(qblocks::SFArchive&) const", referenced from:
      vtable for qblocks::CFunction in simple-94f0bb.o
  "qblocks::CFunction::getObjectAt(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) const", referenced from:
      vtable for qblocks::CFunction in simple-94f0bb.o
  "qblocks::CFunction::getValueByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
      vtable for qblocks::CFunction in simple-94f0bb.o
  "qblocks::CFunction::getRuntimeClass() const", referenced from:
      vtable for qblocks::CFunction in simple-94f0bb.o
  "qblocks::CFunction::Format(qblocks::CExportContext&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void*) const", referenced from:
      vtable for qblocks::CFunction in simple-94f0bb.o
  "qblocks::CLogEntry::SerializeC(qblocks::SFArchive&) const", referenced from:
      vtable for qblocks::CLogEntry in simple-94f0bb.o
  "qblocks::CLogEntry::getStringAt(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) const", referenced from:
      vtable for qblocks::CLogEntry in simple-94f0bb.o
  "qblocks::CLogEntry::getValueByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
      vtable for qblocks::CLogEntry in simple-94f0bb.o
  "qblocks::CLogEntry::getRuntimeClass() const", referenced from:
      vtable for qblocks::CLogEntry in simple-94f0bb.o
  "qblocks::CLogEntry::Format(qblocks::CExportContext&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void*) const", referenced from:
      vtable for qblocks::CLogEntry in simple-94f0bb.o
  "typeinfo for qblocks::CBaseNode", referenced from:
      typeinfo for qblocks::CNameValue in simple-94f0bb.o
      typeinfo for qblocks::CAccountName in simple-94f0bb.o
      typeinfo for qblocks::CParameter in simple-94f0bb.o
      typeinfo for qblocks::CFunction in simple-94f0bb.o
      typeinfo for qblocks::CAbi in simple-94f0bb.o
      typeinfo for qblocks::CLogEntry in simple-94f0bb.o
      typeinfo for qblocks::CReceipt in simple-94f0bb.o
      ...
  "vtable for qblocks::CExportContext", referenced from:
      qblocks::CExportContext::~CExportContext() in simple-94f0bb.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for qblocks::CStringExportContext", referenced from:
      qblocks::CStringExportContext::CStringExportContext() in simple-94f0bb.o
      qblocks::CStringExportContext::~CStringExportContext() in simple-94f0bb.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Stephens-MacBook-Pro:quickBlocks toro$

**Comment by tjayrush** [comment]
To fix this, you need to remove the `/usr/local/qblocks` files from the previous version. Once you do that, you can re-install these files with the new build by doing `sudo make install` from the `./build` folder.

Sorry for the hassle, but currently, this is the only way to do this. Let me know if that works. In a near-future release, we will be building a better install/uninstall mechanism.

**Comment by toro09** [comment]
Tried your recommendation with no change in results unfortunately. I have been looking through all of the .h files in /usr/local/qblocks/include and it appears like all of the virtual member functions are defined.

I'm still learn
ing C++ but I'll help if I can

**Comment by tjayrush** [comment]
@toro09 

Sorry. I didn't notice before. You're not linking to the libraries.  You're using this command: `g++ -Wall -std=c++17 simple.cpp`.  That won't link to any of the static libraries.

Instead, try this. Change to the folder containing `simple.cpp`.  You should see a file in that folder called `makefile`. (If you don't let me know.) If you do see `makefile` simply type `make` in that folder and it should build.

You'll find the compiled program in `./bin/sample`.

Let me know.

**Comment by tjayrush** [comment]
Closing this. It seems to have been resolved.
