### ISSUE TITLE
ABI problems when running grabABI. Etherscan returns incorrect format.

### ISSUE THREAD

**Issue by agericke** [Great-Hill-Corporation/quickBlocks#617]
When you run **grabABI** with generate option and a general address, inside **main()**  function it queries for "_0xTokenLib_" and _"0xWalletLib"_ ABI's (grabABI.cpp line 205) via **acquireABI()** function. This function looks for those files inside **~/.quickBlocks/cache/abis/** folder, and if it does not find them it queries it to Etherscan API.

The problem is that at first, "_0xTokenLib.json_" and _"0xWalletLib.json"_ are inside _libs/tokenlib/_ and _libs/walletlib/_ folders but not in _cache/abis_ folder. So, as they do not have the format of an Ethereum address, Etherscan will return an error.

For avoiding this error, "_0xTokenLib.json_" and _"0xWalletLib.json"_ files must be copied to **~/.quickBlocks/cache/abis/** folder and this error will dissapear. Maybe this action of copying the files could be done during initialization to avoid having to copy them manually.

**Comment by tjayrush** [comment]
Thanks for posting this. This will be fixed in the next release.

**Comment by tjayrush** [comment]
Reorganizing all issues, therefore closing this one.
