### ISSUE TITLE
Account Scraper tutorial error

### ISSUE THREAD

**Issue by toro09** [Great-Hill-Corporation/quickBlocks#620]
Get an error when compiling the example account scraper program from the Medium post. I am using a Makefile that I modified from the simple.cpp example. When I run “make all” it is throwing an error with respect to the forEveryAddress. 
![image](https://user-images.githubusercontent.com/19812434/43672638-2e1cd8b2-9767-11e8-908b-53c32f230fe0.png)
![pasted_image_at_2018-08-02__10_17_pm](https://user-images.githubusercontent.com/19812434/43672643-45ef6680-9767-11e8-8882-e9ba6c0478d7.png)

To fix this use `block.forEveryAddress(visitAddress, NULL, NULL)` instead of `block.forEveryAddress(visitAddress)`.

**Comment by tjayrush** [comment]
Next release (currently in develop branch) will accept the single param version as in the medium post.
