### ISSUE TITLE
INFURA mode doesn't seem to work any more

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#624]
Infrua twitter recently tweeted that they will be dropping support for pmainnet.infura.io which is what we use. Perhaps that's the problem.

**Comment by raiden12** [comment]
I found that the program hangs on attempt to set curl options. The replacement of the URL from "https://pmainnet.infura.io/" to "https://mainnet.infura.io/" in node_curl.cpp enables the program to go on.

**Comment by tjayrush** [comment]
Closing. This was fixed. Still need to fix #969
