### ISSUE TITLE
QuickBlocks compilation fails on Arch Linux due to compiler warnings 

### ISSUE THREAD

**Issue by paulkuhle** [Great-Hill-Corporation/quickBlocks#641]
When compiling on Arch Linux using GCC 8.2.1, the compiler throws the following warnings:

![image](https://user-images.githubusercontent.com/38229644/45110361-519cf980-b142-11e8-8001-1ac0217118eb.png)

(The Spanish error messages translate to " *Warning:* The specified limit depends on the input/original argument" and "*Note:* The length is calculated here")

![image](https://user-images.githubusercontent.com/38229644/45110473-a93b6500-b142-11e8-86ca-b5b9d80d5db7.png)

Since the flag -Werror is set in the ./src/CMakeLists.txt file, all warnings are automatically raised to errors and the compilation process fails.

The first warning seems to be about overflowing the destination buffer: [https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wno-stringop-overflow](url)

I think the second warning is thrown because the recommended way is to throw errors by value and catch by reference.

**Comment by tjayrush** [comment]
These errors don't happen on our Ubuntu builds. May I ask, do you have any suggestions for setting up an Arch Linux box? We use Digital Ocean, but the don't provide an option for Arch linux.

**Comment by paulkuhle** [comment]
osboxes.org has a few Arch Linux images available for VMware and VirtualBox, but personally I just have a normal installation,

**Comment by tjayrush** [comment]
This should be fixed. Please confirm and close.

**Comment by tjayrush** [comment]
Still working on testing this.

**Comment by tjayrush** [comment]
This should now build with no problems. We add a 'Fedora' build to our system which has the same version of the compiler.
