### ISSUE TITLE
Is there any way to set custom node URL or change infura API key for EthSlurp util?

### ISSUE THREAD

**Issue by dzarezenko** [Great-Hill-Corporation/quickBlocks#651]
I am using `EthSlurp` , but looks like it stuck on run last times. I think this problem is connected with infura restrictions. How can I change infura node to my custom node or change infura API key?

**Comment by tjayrush** [comment]
EthSlurp doesn’t use Infura, it uses EtherScan.

Do you have an API key for Infura or EtherScan?

If Infrua, then you need to go to EtherScan to get an API key. Here: https://etherscan.io/myapikey

Please let me know if that works by posting to this issue.
Thanks.

-------------------------------
Thomas Jay Rush
QuickBlocks.io
jrush@quickblocks.io
(610) 519-9413

**Comment by dzarezenko** [comment]
I have read [this issue](https://github.com/Great-Hill-Corporation/quickBlocks/issues/342) before, so I thought that it uses Infura + EtherScan. 

I know how to receive EtherScan API key but how can I set my custom API key in the ethSlurp configuration?

**Comment by tjayrush** [comment]
There's a link here to get an API key or EtherScan https://etherscan.io/apis

**Comment by tjayrush** [comment]
Reorganizing all issues, therefore closing this one.
