### ISSUE TITLE
Block hash does not appear to be a valid block hash.

### ISSUE THREAD

**Issue by LilithVL** [Great-Hill-Corporation/quickBlocks#657]
I'm not sure why this is having issues:
![image](https://user-images.githubusercontent.com/39088556/47553684-f9939f80-d907-11e8-9a3d-7640a0c51f56.png)

Any help would be greatly appreciated.

**Comment by tjayrush** [comment]
Can you copy in this hash as text instead of as an image? I can't really test it the way it is.

**Comment by LilithVL** [comment]
`Liliths-MacBook-Pro-465:monitor lilithvl$ getBlock 100
{

    "gasLimit": 121840312,
    "gasUsed": 0,
    "hash": "0x89e75dea558fda6fd54ef208a89bb04463cf0217658de35873e1fcbd0723191e",
    "blockNumber": 100,
    "parentHash": "0x20481beb36821744732192edc98c0e0702a96e96b7a947cac0d62f0e282768fd",
    "miner": "0x0",
    "difficulty": 137514,
    "price": 0,
    "finalized": 0,
    "timestamp": 1541000064,
    "transactions": []
}
Liliths-MacBook-Pro-465:monitor lilithvl$ getBlock 0x89e75dea558fda6fd54ef208a89bb04463cf0217658de35873e1fcbd0723191e
Block hash '0x89e75dea558fda6fd54ef208a89bb04463cf0217658de35873e1fcbd0723191e' does not appear to be a valid block hash. Quitting...Liliths-MacBook-Pro-465:monitor lilithvl$ `

**Comment by tjayrush** [comment]
Confirmed bug. Very nice. Thanks. I'll fix this shortly.

**Comment by tjayrush** [comment]
Reorganizing all issues, therefore closing this one.
