### ISSUE TITLE
Slow data access when scanning entire chain. 

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#658]
Im trying to use quickblocks to get txns per eth account. It takes a long time though. im using `./getBlock --addrs 0-6589600 | grep 0xa92f7Fb19972622C5C3af5C4F98eCe2e3C3AC689`

**Comment by Sledro** [comment]
so what are the possible solutions?

**Comment by tjayrush** [comment]
Reorganizing all issues, therefore closing this one.
