### ISSUE TITLE
No transactions returned / Block 6579337 is later than the last valid block 195357

### ISSUE THREAD

**Issue by Sledro** [Great-Hill-Corporation/quickBlocks#659]
I was playing around with getBlock and tried `./getBlock 6579337`. I found I can't get the transactions with the block so I think maybe I need to turn on archiving? so I tried `parity --jsonrpc-hosts all --jsonrpc-interface all --tracing on --pruning archive`. Then when I run `./getBlock 6579337` again I get  Block 6579337 is later than the last valid block 195357. Quitting... Am i running the node in the correct mode? Why is there no txns returning with the block?

**Comment by Sledro** [comment]
Fixed.

**Comment by tjayrush** [comment]
When this happens, it's almost always the case that your node is not synced.
