### ISSUE TITLE
What is the recommended way to run a node?

### ISSUE THREAD

**Issue by mds1** [Great-Hill-Corporation/quickBlocks#660]
I want to start playing around with QuickBlocks using an archive node. I plan to retrieve data from every block, and from [this page](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/other/install/RUNNING_A_NODE.md) it seems I'd need at least 1 TB, so 1.5-2 TB of storage to be on the safe side.

2 TB SSDs are pretty pricey, so I was thinking of running a node on an AWS EC2 instance. I was hoping you could recommend a certain instance type and configuration that would allow me to get a node running for as cheap as possible.

**Comment by tjayrush** [comment]
We haven't experimented with AWS, but from what little we know, it will be more expensive to run on AWS. Our understanding (not tested) is that AWS instances consume ~ 100 $ US per month in bandwidth with syncing alone. Over a couple of months this should pay for a 2TB SSD.

However--at this point, I'm 2 TB won't be big enough for a full archive node for long. A full archive node already takes up 1.7 TB.

**Comment by mds1** [comment]
So it seems like there's currently no affordable way to run a full archive node, which is a bit concerning from a decentralization standpoint. And it also means some QuickBlocks/RPC features can't be easily used by hobbyists like myself.

Are there are plans in the works to reduce this burden somehow? The only ways the come to mind off the top of my head are allowing partial archive nodes over selected time-periods/block ranges, or somehow reducing the storage requirements of a full archive node

**Comment by tjayrush** [comment]
We had our own Linux box built with a 4TB SSD hard drive. Other than that it's basically a pretty good gamer box.

Unfortunately, there is nearly nothing we can do related to the size of the archive node. That is the function of the core Ethereum node software itself. I've started putting together a list of possible things to fix / change, but I've not had time to move it forward. Here's my notes for that: https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/docs/OSBEN/possibleEIPs.md

**Comment by mds1** [comment]
Interesting list, I'd like to see those implemented. It would certainly help make auditing and analysis easier.

Looking forward to the medium post, too!
