### ISSUE TITLE
isContract --whenDep issues

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#668]
`whenDep` means "when deployed". This option is used to figure out when a smart contract was first deployed. Currently it only works for smart contracts. It works by querying the smart contract's code. If the code is present today, then it does a binary search to figure out when the code was deployed. It works fine, but it has a number of issues.

- `whenDep` is a terrible name for this option
- `whenDep` only works for smart contracts (it uses getCode). Can we get it to work for regular accounts?
- If the node is not synced, `--whenDep` reports the latest block as the contract's creation date
- If the code is suicided, `--whenDep` will think the address is not a smart contract and will fail.
- Can we use the account's nonce to find the first deployment (this doesn't work either because a smart contract or a regular account can accept ether prior to making its first nonce-changing transaction.

See also #670

**Comment by AeroFin** [comment]
Hi Jay,

When running: 
$ isContract -d -w 0x4DC3643DbC642b72C158E7F3d2ff232df61cb6CE

I get:
0x4dc3643dbc642b72c158e7f3d2ff232df61cb6ce	true

Shouldn't I get something like:
0x4dc3643dbc642b72c158e7f3d2ff232df61cb6ce	true 4301735

With the blockNumber when it was deployed?? So then I can use that number with  | cut -f3

Thank you,
Álvaro

**Comment by tjayrush** [comment]
Fixed
