### ISSUE TITLE
quickblocks.toml cache location gets overridden if commented

### ISSUE THREAD

**Issue by wildmolasses** [Great-Hill-Corporation/quickBlocks#723]
When working on the wildmolasses machine, we commented out the cache path location.

We then `make test` again, (and also `cmake ../src`) and it overwrote the commented out path.

**Comment by tjayrush** [comment]
This would also happen in the case of using cpptoml. In fact, the commented lines are not even stored in the data of ccptoml, so it's impossible for that code to read a comment and then write it out and have it be preserved.
