### ISSUE TITLE
Exclusions

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#825]
We use exclusions (found in ~/.quickBlocks/quickBlocks.toml) in the `blockScrape` and the `acctScrape` apps but not in the montor apps.

I think. This may be fixed.

**Comment by wildmolasses** [comment]
What are exclusions? I don't believe I have them. My quickblocks.toml is as follows:

```toml
[version]
current=0.2.0

[settings]
blockCachePath=/Users/ed/.quickBlocks/cache/

[[tools]]
list = [
    { name = "getBlock",    value = "block"    },
    { name = "getTrans",    value = "trans"    },
    { name = "getReceipt",  value = "receipt"  },
    { name = "getLogs",     value = "logs"     },
    { name = "getTrace",    value = "trace"    },
    { name = "getBloom",    value = "bloom"    },
    { name = "getAccounts", value = "accounts" },
    { name = "getBalance",  value = "balance"  },
    { name = "getTokenBal", value = "tokenbal" },
    { name = "isContract",  value = "contract" },
    { name = "ethName",     value = "name"     },
    { name = "whenBlock",   value = "when"     },
    { name = "whereBlock",  value = "where"    },
]
```

**Comment by tjayrush** [comment]
On wildmolasses, the qblocks test cases are probably failing because of the 'tools' item in this file. 

To fix, simply delete that array. It will get re-created with the proper values. The trouble is I changed `getTokenBal` to `getTokenInfo` but didn't do so in a backwards-compatible way. We can documentat the bug as part of the 'copy files is not backwards compatible' issue. Since we have so few users, we can fix them if they experience problems.

**Comment by tjayrush** [comment]
There's a mistake in the first comment of this issue. The `exclusions` item is in the blockScrape.toml config file. This issue relates more to `blockScrape` than the Toml issue, so I re-assigned it there. Ignore this issue for Toml.
