### ISSUE TITLE
Printing a double rounded to a consistent number of decimals

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#857]
[This function](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/libs/utillib/conversions.cpp#L252) has been a perpetual pain. I can't figure out how to get this to print with

1. The decimal rounded to a certain number of decimal places including negative
2. The width of the string that gets printed is that same number of decimals, but takes up a consistent width (maybe a missing third param with default value). I need this because I frequently print tables of doubles and the get misaligned

```
What I want                                     What I get
     0.00000   0.00001       0.00000   0.00001
    10.00000   0.00001      10.00000   0.00001
  1000.00000   0.00001      1000.000   0.00001
  -120.00000   0.00001      -120.00000   0.00001
     0.00000   0.00001      0.00000   0.00001
```

It gets totally bad when I use tabs instead of spaces to separate the columns (I do this because I want to print to the screen and then possibly later import into Excel.

This is probably way easier than I'm making it out to be. There's a lot of formatting options on `cout` and `cerr` that I don't know how to use.

Also, create a test case under ./src/libs/test-libs/utillib by duplicating an existing test case.

**Comment by wildmolasses** [comment]
Hi Jay, the hyperlink you posted in this issue is broken. Do you mind posting it?

**Comment by tjayrush** [comment]
Fixed the comment above. https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/libs/utillib/conversions.cpp#L252

**Comment by tjayrush** [comment]
Closing
