### ISSUE TITLE
Add testing tools to the repo

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#875]
There are at least four shell scripts that I use to do testing:

```
doTesting
doTestingAll
diffTest
cpTest
```

I don't want these tools to become part of the official 'product' (to the extent we have a product), but they are very useful in my testing flow. 

Figure out some way to make these tools available (probably modify a `CMakeLists.txt` file somewhere) by copying them into the `./bin/test folder`.

**Comment by wildmolasses** [comment]
They're there!

**Comment by tjayrush** [comment]
Great. Closing.
