### ISSUE TITLE
No Special Blocks on Linux

### ISSUE THREAD

**Issue by LilithVL** [Great-Hill-Corporation/quickBlocks#876]
Hello!

I built a little application using quickBlocks, which works fine on OSX. However, it requests the latest block, using whenBlock latest, as such:

> Liliths-MacBook-Pro-3332:blockchain-app lilithvl$ whenBlock latest
> block #77717 : 1542718658 : 2018-11-20 12:57:38 UTC

On Ubuntu 16.04 however, I get this result:

> lilith:~/blockchain-app$ whenBlock latest
> The given value 'latest' is not a numeral or a special named block. Quitting...

Upon further inspection it seems that the Ubuntu build has no special names at all:

> lilith:~/blockchain-app$ whenBlock
> 
>   Not enough arguments presented.
> 
>   Usage:    whenBlock [-d|-l|-v|-h] < block | date > [ block... | date... ]  
>   Purpose:  Finds the nearest block prior to a date, or the nearest date prior to a block.
>             Alternatively, search for one of special 'named' blocks.
>              
>   Where:    
> 	block                 one or more block numbers (or a 'special' block), or...
> 	date                  one or more dates formatted as YYYY-MM-DD[THH[:MM[:SS]]]
> 	-d  (--data)          display the result as data (tab delimited; useful for scripting)
> 	-l  (--list)          list names and block numbers for special blocks
> 	-v  (--verbose)       set verbose level. Either -v, --verbose or -v:n where 'n' is level
> 	-h  (--help)          display this help screen
> 
>   Notes:  
> 	\- Use the following names to represent `special` blocks:
> 	  - 
> 
>   Powered by QBlocks (0.5.5-alpha)

**Comment by tjayrush** [comment]
There should be a file called ~/.quickblocks/whenblock.toml. Is that file present?  What’s in it?

 Since you first installed, did you ever delete ~/.quickblocks?

**Comment by tjayrush** [comment]
If there is any further information you can give us about your system, that would help.

**Comment by LilithVL** [comment]
The mention of this whenBlock.toml file led me to the solution
The file defaulted to denying access, so after fixing that, it's working now.

**Comment by tjayrush** [comment]
Thanks for getting back to us. Closing.
