### ISSUE TITLE
ethSlurp does not fetch DEX transactions

### ISSUE THREAD

**Issue by akshatdev0** [Great-Hill-Corporation/quickBlocks#958]
I have been playing with QuickBlocks, but have observed that `ethSlurp` does not fetch DEX transactions.

For example, have a look at below transaction:
[https://etherscan.io/tx/0x08c6c56223b1de6a51502e5cf9e5642fee4611dc46609055957c34b3753796d6](https://etherscan.io/tx/0x08c6c56223b1de6a51502e5cf9e5642fee4611dc46609055957c34b3753796d6)

**Comment by tjayrush** [comment]
What command line are you using for ethSlurp?

**Comment by akshatdev0** [comment]
`ethSlurp <contract-address>`

**Comment by tjayrush** [comment]
Ethslurp (unlike other tools such as `blockScrape` and `acctScrape`) only pulls data from EtherScan, so whatever results EtherScan returns are the results `ethslurp` will return. There is an option to pull three different types of `transactions` as defined by EtherScan. See the `type` option:

```
(develop)@./build:jrush>$ ethslurp

  Usage:    ethslurp [-b|-t|-f|-b|-s|-v|-h] addrs
  Purpose:  Fetches data from EtherScan for an arbitrary address. Formats the output to your specification.

  Where:
	addrs                 one or more addresses to slurp (required)
	-b  (--blocks range)  an optional range of blocks to slurp
	-t  (--type val)      extract either [ ext | int | token | miner | all ] type of transactions
	-f  (--fmt val)       pretty print, optionally add ':txt,' ':csv,' or ':html'
	-b  (--blocks range)  export records in block range (:0[:max])
	-s  (--silent)        Run silently (only freshen the data, do not display it)
	-v  (--verbose)       set verbose level. Either -v, --verbose or -v:n where 'n' is level
	-h  (--help)          display this help screen

  Powered by QBlocks (0.5.5-alpha)
```

**Comment by tjayrush** [comment]
I am going to close this. You can re-open it if you have further questions.
