### ISSUE TITLE
Infura mode don't work

### ISSUE THREAD

**Issue by raiden12** [Great-Hill-Corporation/quickBlocks#966]

**Comment by tjayrush** [comment]
Duplicate of #624

**Comment by tjayrush** [comment]
Thanks for your submission. We're aware of this issue, but we're working on a release for dAppNode right now and don't have the resources to fix this issue right now. If you're a developer, we can help you get started in debugging and fixing this issue. Please join our slack https://quickblocks.slack.com/ and we'll help you get started.

**Comment by tjayrush** [comment]
We are closing this in lieu of issue #977
