### ISSUE TITLE
Let user set RPCENDPOINT on the command line

### ISSUE THREAD

**Issue by wildmolasses** [Great-Hill-Corporation/quickBlocks#970]
Similar to how we set FALLBACK=infura, a user could set RPCENDPOINT=http://localhost:5151

Then users could hit any RPC url they'd like.

e.g.

`RPCENDPOINT=http://localhost:5151 getBlock 1010101`

`RPCENDPOINT=http://mainnet.infura.io getBlock 1010101`

Does this obviate the need for a separate FALLBACK variable?

Follows from #966 

Relates to issues with hardcoded infura url: #921, #700, #554 

Perhaps relates to #357.

**Comment by tjayrush** [comment]
Tx-Providers link has a bunch of related issues.

**Comment by tjayrush** [comment]
Let's call this Provider instead of RPCENDPOINT to more closely mimic web3.js: https://web3js.readthedocs.io/en/1.0/web3.html#setprovider

**Comment by tjayrush** [comment]
Closing this in lieu of issue #977
