### ISSUE TITLE
Hm

### ISSUE THREAD

**Issue by AvatarSovius** [Great-Hill-Corporation/quickBlocks#999]
ERRORWindows build is not supported yet
======== LOOKING FOR PYTHON ========================
======== LOOKING FOR CURL ========================
CMake Error at C:/Users/sova/Desktop/cmake-3.13.3-win64-x64/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Users/sova/Desktop/cmake-3.13.3-win64-x64/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Users/sova/Desktop/cmake-3.13.3-win64-x64/share/cmake-3.13/Modules/FindCURL.cmake:74 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:40 (find_package)

**Comment by tjayrush** [comment]
Yep. We're working on a docker container but it's not quite ready yet.

May I ask a question? Does CMake work on Windows? The reason we don't yet support Windows is because we have no windows computers to test things on. Do you know CMake?

**Comment by tjayrush** [comment]
We currently have no ability to test the build on Windows. I'm going to close this. If you wish to help us understand how to fix the Windows build, please reopen.
